### ISSUE TITLE
Menu takes long to open

### ISSUE THREAD

**Issue by blaumeise20** [wulkano/Kap#1010]
**macOS version:**    Big Sur (11)
**Kap version:**      3.3.2

I love this program because you can record the screen as GIFs, but I noticed one thing: When you right-click at the Kap symbol it takes soooo long until the menu opens up. What could that be?

**Comment by skllcrn** [comment]
We are aware of performance issues triggering Kap from the menubar and while cropping the recording area. Amongst other things we're looking to upgrade Electron to better support M1 devices.
