### ISSUE TITLE
404 when clicking on Download the latest release link

### ISSUE THREAD

**Issue by aheze** [wulkano/kap#1013]
**macOS version:** N/A
**Kap version:** N/A

#### Steps to reproduce
Press the "Download the latest release" link at the top of the README

#### Current behavior
Goes to https://kap.vercel.app/api, which is a 404:

![Screen Shot 2021-05-11 at 10 46 58 AM](https://user-images.githubusercontent.com/49819455/117861380-39ac9a80-b246-11eb-9581-c6c629e432de.png)

#### Expected behavior
The latest release should be downloaded

#### Workaround
Install via homebrew

**Comment by timothyis** [comment]
Thank you!
