### ISSUE TITLE
It doesn't offer Kap as option for camera permissions! Mac os Mojave

### ISSUE THREAD

**Issue by ernestofv01** [wulkano/Kap#1023]
macOS version:        10.14.6
Kap version:          3.3.2
Step to reproduce:    Using the extension to record my face, I just start recording and it say "you have to allow kap", but it is not in the options
Current behavior:     
Expected behavior:    How you expected Kap to behave.
Workaround:          I have TRIED to open through packeges and open using terminal, it works to record but I cannot save the recording, another error appears

**Comment by skllcrn** [comment]
If you're still experiencing this, please create an issue in the plugin repository: https://github.com/karaggeorge/kap-camera
