### ISSUE TITLE
Enable ASAR when building

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#103]
Right now, Kap, is not built with ASAR. ASAR can considerably improve the startup time of the app by putting all JS files into one file. @matheuss disabled it initally as it caused some problems with Aperture.js. ASAR should in theory handle child processes, but if we can't work it out, we can use the electron-builder [`asarUnpack` option](https://github.com/electron-userland/electron-builder/wiki/Options).

This should happen after Kap 1.0.

---

Alternatively, we could switch from `execa` (it uses `.spawn` underneath) to `.execFile`: http://electron.atom.io/docs/tutorial/application-packaging/#executing-binaries-inside-asar-archive

**Comment by sindresorhus** [comment]
I look into this today and opened an Electron issue about it: https://github.com/electron/electron/issues/9459

We also need to set this in the "build" config of package.json:

```json
"asarUnpack": [
   "vendor/ffmpeg"
]
```

**Comment by albinekb** [comment]
@sindresorhus should we just enable asar and `asarUnpack` the `aperture` (and ffmpeg) binary? Wouldn't that work 🤔

**Comment by sindresorhus** [comment]
@albinekb I've tried before but got stuck on a problem. Maybe you could give it a try too?

Here's a start: https://github.com/wulkano/kap/commit/bb5749e976724348f2b27d96d0a7e58a57ea87ad 

<img width="532" alt="screen shot 2017-10-27 at 16 19 29" src="https://user-images.githubusercontent.com/170270/32097110-a1ae83e6-bb32-11e7-96b8-8f660ea048c3.png">

I can't seem to find the Aperture binary.
