### ISSUE TITLE
preferences dialog does not have a scrollbar

### ISSUE THREAD

**Issue by tekumara** [wulkano/Kap#1030]
**macOS version:**
sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

**Kap version:**

Version 3.3.2 (3.3.2.1718)

#### Steps to reproduce

Open Kap Preferences

#### Current behaviour

<img width="592" alt="Screen Shot 2021-08-26 at 1 29 02 pm" src="https://user-images.githubusercontent.com/125105/130895925-31d51805-1d2d-46c4-8ea6-49537c7f8e98.png">

#### Expected behaviour

A scrollbar on the right hand side that can be dragged to reach the other preferences.

#### Workaround

Select text and drag

**Comment by skllcrn** [comment]
The scrollbar should appear when scrolling using a mouse or similar. If you'd like to always show scrollbars, you can head into your System Preferences to toggle the setting: https://support.apple.com/guide/mac-help/change-general-preferences-mchlp1225/mac
