### ISSUE TITLE
FR: Title frame.

### ISSUE THREAD

**Issue by hemanth** [wulkano/kap#104]
It would be nice to have title frame for a give amount of time before the actual gif/video starts.

P.S: If it feels like a good add-on, I would like to work on it.

**Comment by skllcrn** [comment]
By this, do you mean a countdown in the main app window before the recording starts? There are some technical limitations here I believe, @matheuss can provide more detail. However, we've discussed having the record button pulsate slightly while it's getting ready, see "Pulse" here https://daneden.github.io/animate.css/

**Comment by hemanth** [comment]
Yes, something like below:

![](https://nmotw.in/images/email-prompt/email-prompt.gif)

**Comment by doot0** [comment]
Hey @hemanth.

To get some more clarity on what you're asking - are you asking for the ability to add an image to the start of a recording made with Kap?

**Comment by hemanth** [comment]
Yes, basically a frame with desired text for a desired duration.

**Comment by skllcrn** [comment]
Ah! Misunderstood you at first. Kap is not a video editor and doesn't try to be. We've considered and are still considering trimming and cropping, but we won't go further into editing than that. We have plans for supporting plugins, so in the future you might be able to create your own solution to this!

**Comment by hemanth** [comment]
> countdown in the main app window before the recording starts

I miss interpreted that line, cool, looking forward for the plugin integration system.
