### ISSUE TITLE
Can't install Kap

### ISSUE THREAD

**Issue by natashaTpT** [wulkano/Kap#1040]
When I try to install Kap, I get the message: 

> **"Kap" can't be opened because Apple cannot check it for malicious software.** 
> This software needs to be updated. Contact the developer for more information.

**macOS version:** Mac 11.6 - Big Sur
**Kap version:** 3.4.0

#### Steps to reproduce
Download Kap from https://getkap.co/. Double click to install. Try opening it. 

#### Current behaviour
I can't open Kap after download - I get the above error message. 

#### Expected behaviour
 I should be able to open it. I have it running on my other computer. 

#### Workaround
None

![image](https://user-images.githubusercontent.com/69636141/134898773-4f2e2ec3-a3fa-4efb-9b6f-f9c589dc1bd4.png)

**Comment by sindresorhus** [comment]
Right-click the app and select "Open". You only need to do this once.

**Comment by natashaTpT** [comment]
Ah right, I forgot about this. Thank you!!
