### ISSUE TITLE
macOS 12.0.1 & Kap 3.4.1: Camera is not showing up when recording and camera video is not getting recorded

### ISSUE THREAD

**Issue by christianblessing-me** [wulkano/Kap#1047]
macOS version:        12.0.1
Kap version:          3.4.1
Step to reproduce:    Activate the Camera Plugin, start the recording
Current behavior:     The camera window is not showing up when recording neither is the camera recorded when playing back the recorded video.
Expected behavior:    The camera window is showing up while recording and the image of the camera is actually getting recorded.
Workaround:           none

**Comment by skllcrn** [comment]
This sounds like an issue with permissions, I'd check in your Security & Privacy preferences to ensure Kap is allowed access to your camera. If that doesn't resolve it, please open the issue in the `kap-camera` repository: https://github.com/karaggeorge/kap-camera

**Comment by christianblessing-me** [comment]
@skllcrn thank you, already checked permissions but this doesn't resolve the issue. I will open an issue in the kap-camera repo.
