### ISSUE TITLE
 arm64 version is downloaded by default from website.

### ISSUE THREAD

**Issue by mordv** [wulkano/Kap#1067]
On Big Sure/Intel mac **arm64.dmg is downloaded from getkap.co

**Comment by orlandovallejos** [comment]
Same issue here.... is there any workaround?

**Comment by perkinsjr** [comment]
@orlandovallejos you can go to the releases section in GitHub to download https://github.com/wulkano/Kap/releases/tag/v3.5.1 and pic the dmg release that isn't arm64

**Comment by orlandovallejos** [comment]
I did that, but the app keeps asking for permission, and then it closes.
I'm already using another one, but it'd be nice to have this working

**Comment by timothyis** [comment]
Thanks for the report, all, I'm having a look at this soon 🙏🏼

**Comment by timothyis** [comment]
Hey all, the Kap website now downloads the Intel Mac binary by default, but also now supports downloading arm64 using https://getkap.co/api/download?system=arm64. There'll be a selector for this soon.

Resolved in https://github.com/wulkano/getkap.co/pull/45.
