### ISSUE TITLE
Option to stop Kap from auto updating

### ISSUE THREAD

**Issue by yaustar** [wulkano/Kap#1068]
**macOS version: 11.6.1 (20G224)**
**Kap version: Kap-3.3.2**

#### Steps to reproduce
Restart laptop and Kap auto updates

#### Current behaviour
Kap auto updates and I'm unable to prevent it from the preferences

#### Expected behaviour
An option to prevent auto updating

#### Workaround
Reinstall 3.3.2 on each restart

The reason I would like this behaviour is because GIF export is currently broken in the sense that it is not possible to have high quality GIFs after resizing and trimming. See https://github.com/wulkano/Kap/issues/1043

**Comment by timothyis** [comment]
Thanks for submitting this issue! While I don't think this option should be included because of errors on the latest releases (we should fix those!), I do think users should have the option to stay on a particular version if they want to. (cc @skllcrn @sindresorhus?)

**Comment by timothyis** [comment]
Removed "Help wanted" for more discussion.

**Comment by gustavohenke** [comment]
Hey all, one good use case for this is to get around issues like #921 -- downgrading from 3.5.1 to 3.4.2 helped me to record again

**Comment by timothyis** [comment]
Hi all, in this case, I think we should forgo this feature in order to keep users up-to-date on maintained versions of Kap. The most recent version should have priority to work, and if an older version doesn't work, we cannot maintain that. 

In this case, I will close the issue.

**Comment by yaustar** [comment]
> I think we should forgo this feature in order to keep users up-to-date on maintained versions of Kap

But the suggestion here is for stability. As an end user, I should be able to choose whether I want to auto update or not. At the moment, at any point I restart my Mac, Kap could change.

In my case, GIF quality got worse (https://github.com/wulkano/Kap/issues/1043) and it still has this issue. 

Now I have to re-install Kap 3.3.2 every time I reboot because of the autoupdate.

**Comment by timothyis** [comment]
More information on why this feature should exist was added to #1116. We will track the feature there.
