### ISSUE TITLE
Filenames are not customized when using Drag and Drop from the Export Complete window

### ISSUE THREAD

**Issue by kj800x** [wulkano/Kap#1074]
**macOS version:** macOS Big Sur Version 11.6 (20G165) on MacBook Pro (15-inch, 2017)
**Kap version:** Version 3.5.1 (3.5.1.1783)

#### Steps to reproduce
* Use Kap to record your screen
* Export the resulting file to any format and **change the filename**
* From the "Export Completed" dialog, drag the file into another application (tested with Chrome, Slack, and Finder). The other application will properly receive the file, but will not use the file's customized filename, instead using the default filename like `Kapture 2022-01-13 at 17.23.48.mp4`

![gif demonstrating the issue](https://user-images.githubusercontent.com/1657142/179438568-05c0782a-05c4-40c7-aa99-e51cd218ae9a.gif)

#### Current behavior
The other application sees the default filename, rather than the customized filename.

#### Expected behavior
The other application will see the file as having whatever the filename was customized to be.

#### Workaround
* One option is to simply accept that the filename will not be customized (this is a fairly minor thing in the grand scheme of things), although this can pose difficulties in situations where spaces in the filenames cause complications (i.e. dragging a Kapture into an S3 bucket means that I need to manually replace spaces with `%20` when giving the link out to people).
* Another option is to double click on the filename or preview in the "Export completed" window, which will then reveal the exported file in Finder which does have the correct filename. From there I can drag and drop the file into whatever other application I need it in and it will have the correct filename.

**Comment by FarzamMohammadi** [comment]
Hey @kj800x, may I take a stab at this?

**Comment by kj800x** [comment]
> Hey @kj800x, may I take a stab at this?

Feel free, it'd be super nice to have this bug fixed!

**Comment by FarzamMohammadi** [comment]
I'm working with windows and to avoid the "The platform "win32" is incompatible with this module." error I run "yarn install --ignore-engines --ignore-platform" and although it installs everything I still face this error when I run the app:
![image](https://user-images.githubusercontent.com/72108716/182052044-d67bc107-9adc-4576-9b5b-302ced912640.png)

Any ideas on how to go about resolving this?

**Comment by cluzier** [comment]
I see this is still open, going to give this a go 👍
