### ISSUE TITLE
I love your app but it keeps crashing when I try to record.

### ISSUE THREAD

**Issue by fraktalize** [wulkano/Kap#1079]
**macOS version:**    Monterey (12)
**Kap version:**      3.5.2

#### Steps to reproduce

Record screen

#### Current behavior

Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)

#### Expected behavior

Record screen

**Comment by skllcrn** [comment]
Closing in favour of #1063
