### ISSUE TITLE
Filenames aren't safe for work

### ISSUE THREAD

**Issue by jordyvandomselaar** [wulkano/Kap#1093]
![image](https://user-images.githubusercontent.com/12712484/153284999-f633a5ac-4dea-4b01-bc92-cbd37544914a.png)

Can't say I didn't laugh but come on man 😂️

**Comment by skllcrn** [comment]
Looks like you're using the `recording-name` plugin, you can open an issue on it's repository: https://github.com/karaggeorge/kap-recording-name
