### ISSUE TITLE
Camera plugin does't work

### ISSUE THREAD

**Issue by Tanp7** [wulkano/Kap#1094]
**macOS version:**    Monterey (12)
**Kap version:**      3.5.3

#### Workaround

#982 
I follow the https://github.com/karaggeorge/kap-camera, and enable camera plugin in Kap then I have check my Security & Privacy preferences to ensure Kap is allowed access to your camera. 

But it does't work, I can not see the camera window.

**Comment by timothyis** [comment]
Hi there, thanks for submitting an issue.

Since this problem is directly related to the kap-camera plugin, I ask that you submit an issue on the plugin's repository.

Thanks!
