### ISSUE TITLE
Kap is not working on mac Monterey 12.2.1

### ISSUE THREAD

**Issue by QianwenChen** [wulkano/Kap#1098]
**macOS version:** Monterey 12.2.1
**Kap version:** 3.5.4

#### Steps to reproduce
1. Updated Mac to 12.2.1
2. Open the original Kap on my laptop, system shows "You can't open the application 'Kap' becasue this application os not supported on this Mac"
3. Uninstalled an installed again, still have this issue  

#### Workaround

Screenshots: 
<img width="254" alt="Screen Shot 2022-02-28 at 10 46 13 AM" src="https://user-images.githubusercontent.com/14812162/156041763-0af0eccd-d320-4909-971f-82a2bc45381c.png">
<img width="384" alt="Screen Shot 2022-02-28 at 10 46 07 AM" src="https://user-images.githubusercontent.com/14812162/156041769-1e0c5e3a-a8f0-4845-bd6b-d24fbd1a793b.png">
<img width="587" alt="Screen Shot 2022-02-28 at 10 45 55 AM" src="https://user-images.githubusercontent.com/14812162/156041772-54799dae-c286-4dbb-b916-e7804edc6969.png">

**Comment by timothyis** [comment]
Hi @QianwenChen, could you tell me how you installed Kap and which version you installed? (Intel vs Apple Chip)

**Comment by jscho13** [comment]
I ran into this issue as well but installed `Apple Chip` instead of `Intel`. Installing `Intel` fixed this issue. I accidentally assumed it was apple chip since I'm using an apple computer (easy to mix up). @QianwenChen

**Comment by timothyis** [comment]
Thanks for confirming that @jscho13! I'll close this issue for now, in that case, since I think that's the issue for @QianwenChen also. If not, please let me know and we'll re-open!

**Comment by jscho13** [comment]
@timothyis Would you be open to a FAQ section for questions like this or https://github.com/wulkano/Kap/issues/1044? Can open a draft for you

**Comment by timothyis** [comment]
Yes, absolutely, the readme sounds good @jscho13, thank you!
