### ISSUE TITLE
Kap does not show a window when opening. 

### ISSUE THREAD

**Issue by dp462** [wulkano/kap#11]
Upon installing and opening Kap, nothing shows up. When I right click and do "show all available windows" on the dock....I get "no available windows."
![screen shot 2016-10-05 at 10 46 57 am](https://cloud.githubusercontent.com/assets/7724604/19118048/20a37b78-8ae9-11e6-8f72-7a91934fd896.png)

Only options are to quit the application.

**Comment by dp462** [comment]
It does!
![screen shot 2016-10-05 at 10 55 16 am](https://cloud.githubusercontent.com/assets/7724604/19118390/3e78c580-8aea-11e6-916a-5326d243b7f3.png)

**Comment by doot0** [comment]
Does it show up in your menu bar at all? The icon looks like this:

<img width="31" alt="screen shot 2016-10-05 at 16 03 36" src="https://cloud.githubusercontent.com/assets/1171137/19118744/4f691f7c-8b15-11e6-8f09-7c67405f3f5e.png">

**Comment by matheuss** [comment]
That's strange @dp462 😰 It isn't supposed to show up on the dock right when you launch it, only in the menubar. Also, [it's supposed to open the window when it's ready](https://github.com/wulkano/kap/blob/master/app/src/main/main.js#L236) 😕

**Comment by dp462** [comment]
I'll try a uninstall / reinstall. I have my other macbook I'll try it on tonight!

**Comment by dp462** [comment]
Installed on my Retina MBP and had 0 issues. It's my 2012 MBP that seems to be the problem.

**Comment by dp462** [comment]
Just some more info on this if you're interested. I could not for the life of my figure out why my 2012 MBP wasn't letting this open. I was able to install it and start the app, but it would sit on the dock and not do anything. My 2014 rMBP worked perfectly with the install.

After further troubleshooting, I figured out it has to do with my user profile on the 2012 MBP. I created a test account on the 2012 with admin permissions, and started Kap. Instantly started as it should.

Now I'm currently working on figuring out what's stopping Kap from running correctly on my user account that I always use. I'll report back!

**Comment by doot0** [comment]
@dp462 That's super helpful, thank you! Keep us posted if you can. 😄

**Comment by derek-palmer** [comment]
So I ended up rebuilding the machine and all is right in the world. No idea what was stopping it from opened after digging around. Thanks!

**Comment by skllcrn** [comment]
Glad to hear that you got it working!
