### ISSUE TITLE
Error when yarn run dev

### ISSUE THREAD

**Issue by thoaihuynh2509** [wulkano/Kap#1100]
I clone source code from main branch and yarn run dev.

It is not working. Can you help me?

![Screen Shot 2022-03-03 at 6 43 46 PM](https://user-images.githubusercontent.com/30824675/156558825-155b0879-ce2f-4b98-8da7-008767edd15f.png)

**Comment by timothyis** [comment]
Please read the [contributing guide](https://github.com/wulkano/Kap/blob/main/contributing.md#contributing). 

The command should be `yarn start`.
