### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by YoRolling** [wulkano/Kap#1111]
**Sentry Issue:** [KAP-AV1](https://sentry.io/organizations/wulkano-l0/issues/2679533611/)

**macOS version:**    Monterey (12)
**Kap version:**      3.5.4

```
Unhandled Promise Rejection

Error: Command was killed with SIGSEGV (Segmentation fault): /Users/yo/Library/Application Support/Kap/plugins/node_modules/macos-key-cast/key-cast -s normal -t 0.5 -d 69733568 -b {"bounds":[[0,0],[1680,1050]]}
    at makeError (/macos-key-cast/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/macos-key-cast/node_modules/execa/index.js:114:26)
    at async /Users/yo/Library/Application Support/Kap/plugins/node_modules/macos-key-cast/index.js:45:20
```

Since I install it by `brew install kap`, it feel like freeze, every action in kap  so slow. I am not reboot mac right now .

**Comment by timothyis** [comment]
Hi @YoRolling. Do you have the Keycast plugin installed, by any chance?

**Comment by YoRolling** [comment]
@timothyis  yes,the  keycast plugin is installed. So ,that's the problem?should I uninstall the plugin ? Tks for your works.

**Comment by timothyis** [comment]
Thanks for confirming. Yes, I believe the keycast plugin is the issue here, from the error. Please try uninstalling and trying again. If that's the issue, please submit an issue to https://github.com/karaggeorge/kap-key-cast

**Comment by YoRolling** [comment]
Many thanks 。 Without `keycast`plugin, it works, error was disappeard.
