### ISSUE TITLE
Okey Button for plugin options is half cut off

### ISSUE THREAD

**Issue by leland359** [wulkano/Kap#1113]
Anytime I open up the options for a plugin the okey button (I think that's what it's called but I can't see it) is half cut off

**macOS version:**    Monterey (12.3.1)
**Kap version:**      3.5.4
<img width="480" alt="Screen Shot 2022-04-12 at 9 27 33 PM" src="https://user-images.githubusercontent.com/49353135/163102768-8a570f57-9cca-4085-a60f-c63b8cc889e2.png">

**Comment by bcastillo32** [comment]
Hi! can i grab this issue?? :)

**Comment by timothyis** [comment]
Hi @bcastillo32, apologies for the late reply, I was on holiday.

Please feel free to submit a PR for this.

**Comment by bcastillo32** [comment]
Hey! No worries! Looks like someone already submitted a fix for this? I see
it there in the issue thread. Any other issues you suggest for someone
super new like me?

For context, I’m primarily self taught..based in NY at the moment and
trying to get some practical experience that will help me land a job. Also
will want to keep contributing to open source projects too, so yeah any
insight would be great!

Brandon

**Comment by Harsh-Shedge** [comment]
Hi, Can I work on this issue?
