### ISSUE TITLE
Is Kap not compatible with macOS 12.4? Cannot make it work

### ISSUE THREAD

**Issue by irinaef** [wulkano/Kap#1123]
**macOS version: 12.4**
**Kap version: the most recent downloaded **

**Comment by nimbusgo** [comment]
I also recently upgraded to macos 12.4 and kap does not work at all. The icon shows up in the tool bar, if I click it causes the pinwheel to spin, screen flickers briefly, but nothing else happens. I can force quit the application, and restart it, but same behvaior.

**Comment by skllcrn** [comment]
Closing as this seems to be related to #1125, if you have additional information please open a new issue @irinaef.
