### ISSUE TITLE
Not compatible with Ventura Beta

### ISSUE THREAD

**Issue by steelbrain** [wulkano/Kap#1126]
**macOS version:** 13.0 Beta / 22A5286j
**Kap version:** Kap v3.5.4

#### Steps to reproduce

- Download and move Kap to Applicatons folder
- Open Kap

#### Current behaviour

- Uncaught Exception on Boot

#### Expected behaviour

- It works

#### Workaround

- None that I am aware of

#### Footnotes

Here's the screenshot from the issue

<img src="https://user-images.githubusercontent.com/4278113/176407936-640e3a93-6d60-498e-a574-3d9d00d4cfb5.png">

The issue seems to be coming from `macos-release`, I checked and it seems the package has already been updated to support Ventura as of https://github.com/sindresorhus/macos-release/commit/9c6899c29f013e97200d027074a3cb0d55ac826b

**Comment by rlogank** [comment]
Same error in Monterey 12.4, Macbook Air (M1, 2020)

**Comment by HatimDa** [comment]
Same for me , on MacOS Ventura, I get the same error

**Comment by xy1999729** [comment]
Same for me, on macOS Ventura beta 3.

**Comment by uhlhosting** [comment]
+1

**Comment by jordyvandomselaar** [comment]
@ianberdin looking at the commit history, I don't see any changes related to Ventura. The commit that moved the library to ESM, didn't change any parsing logic so if the last commonjs doesn't work, the ESM version likely won't either.

If ESM is not usable with Kap, the possibility of forking the macos-version library should be considered.

**Comment by jordyvandomselaar** [comment]
I've created a patched release here that works on Ventura on a M1 pro mac: https://github.com/jordyvandomselaar/Kap/releases/tag/v0.0.0-unofficial

**This is not official and has zero guarantees whatsoever. Please switch back to the main Kap project as soon as possible**

**Comment by sindresorhus** [comment]
https://github.com/wulkano/Kap/releases/tag/v3.5.5

**Comment by jordyvandomselaar** [comment]
Ah dang it, should've opened a PR 😭
