### ISSUE TITLE
Can't Pass Permissions Step when opening Kap

### ISSUE THREAD

**Issue by marcdstudio** [wulkano/Kap#1127]
**macOS version:**
Monterey 12.4

**Kap version:**
3.5.4

#### Steps to reproduce
Opening the app after installing asks me to give the app screen recording permissions. Once I've allowed permissions and restarted the app, it continues to ask me to allow permissions regardless of whether the permissions set to allow. I have tried to restarting the app, restarting my computer, re-downloading the app but the issue persists. 

#### Current behaviour
Currently, the App continues to ask for permissions to screen record and does allow the app to start.

#### Expected behaviour
App opens and works as expected after allowing permissions in user settings.

I've been using the app for a few years, and have only seen this problem after upgrading to the latest Mac OS version.

**Comment by markolovric** [comment]
Same thing for me. Unfortunately, I cant use the app anymore because of this bug

**Comment by timothyis** [comment]
Hi both, can you try this? https://github.com/wulkano/Kap/issues/1120#issuecomment-1165549731

**Comment by markolovric** [comment]
Yep, works for me. Thx
