### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by SjoerdvGestel** [wulkano/Kap#1130]
**Sentry Issue:** [KAP-ASE](https://sentry.io/organizations/wulkano-l0/issues/2657905893/)

**macOS version:**    Monterey (12)
**Kap version:**      3.5.4

```
Unhandled Error

TypeError: Object has been destroyed
    at Object.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:69:17)
    at Object.emitter.emit (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/@sentry/electron/dist/main/integrations/electron.js:63:25)
```

Not sure what changed, but since recent it started to become hard use kap. Clicking the icon now rarely shows up the UI, and this error just popped up. But if it works its still great :D hope it can be solved and working better again as it was. Guess Apple is working its "magic" again xD

**Comment by timothyis** [comment]
I'm sorry about the experience @SjoerdvGestel. We're trying to resolve a lot of issue at the moment that just seem to occur from dependency updates and old modules on new systems. 

I'm going to close this issue, however, to track it in #1060 since it's a duplicate.
