### ISSUE TITLE
Release Kap app to the macOS App Store plan?

### ISSUE THREAD

**Issue by GlobalGayhub** [wulkano/Kap#1138]
Are there any plans to support the release of Kap to the App Store? This installation should be more convenient.
we hope~

**Comment by timothyis** [comment]
No plans currently. I don't know if it's possible with the Electron app.

**Comment by ilqvya** [comment]
> No plans currently. I don't know if it's possible with the Electron app.

@timothyis 

You can find guide of publishing Electron app to appstore here:
https://www.electronjs.org/docs/latest/tutorial/mac-app-store-submission-guide

**Comment by timothyis** [comment]
I think there's some more rules on what you can submit, however, and I'm not sure if Kap would be eligible. Thanks for the resource, though!

We can take another look in the future, but there are a lot of areas that need focus first.
