### ISSUE TITLE
Update notification pops up while screen recording

### ISSUE THREAD

**Issue by TheFutureIsVoluntary** [wulkano/Kap#1139]
**macOS version: 12.5**
**Kap version: 3.5.4 for M1**

#### Steps to reproduce
Start a recording, wait and happen to be lucky enough to have an update notification pop up.

#### Current behaviour
Update notifications pop up while recording.

#### Expected behaviour
Update notifications are suppressed while recording, to show at some other time.

#### Workaround
None. Stop your recording, update app, and start all over again. Frustrating for long recordings.

Thanks so much for creating an overall great app!

**Comment by timothyis** [comment]
You can use a plugin for this behaviour: https://github.com/karaggeorge/kap-do-not-disturb#usage
