### ISSUE TITLE
Kap 3.5.5 can't open on macOS 10.15.7

### ISSUE THREAD

**Issue by dwenjia** [wulkano/Kap#1147]
macOS version:        macOS 10.15.7
Kap version:          3.5.5
Step to reproduce:    Download Kap-3.5.5-arm64-mac.zip released on 11 Aug, open the file
Current behavior:     I'm getting the system error message "You can’t use this version of the application “Kap” with this version of macOS. You have macOS 10.15.7. The application requires macOS 11.0 or later."
Expected behavior:    Kap should work since it only requires macOS 10.12
Workaround:           Haven't found one

<img width="659" alt="Screenshot 2022-10-18 at 1 55 14 PM" src="https://user-images.githubusercontent.com/22995462/196347353-9e1bc8c0-9436-4a0a-ad7f-dae4afe73ea3.png">
<img width="416" alt="Screenshot 2022-10-18 at 1 55 27 PM" src="https://user-images.githubusercontent.com/22995462/196347363-fb4d08ce-678f-4b5a-b093-f027fe53111f.png">

**Comment by timothyis** [comment]
Hi there, I believe you may have misunderstood the error message. Your mac version is behind the required version. Kap does not support macOS 10.x.

**Comment by dwenjia** [comment]
> Hi there, I believe you may have misunderstood the error message. Your mac version is behind the required version. Kap does not support macOS 10.x.

Ok, thanks for clarifying. I misunderstood due to this on the website - "macOS 10.12 or later required", so that should be updated.

<img width="1230" alt="Screenshot 2022-10-18 at 4 09 05 PM" src="https://user-images.githubusercontent.com/22995462/196373854-8c5d05dd-b335-453f-8c16-4caae09501f9.png">

**Comment by timothyis** [comment]
Oh, thank you for pointing that out, that is indeed and issue. I'll make sure that is fixed. Thank you!

**Comment by dwenjia** [comment]
> Oh, thank you for pointing that out, that is indeed and issue. I'll make sure that is fixed. Thank you!

No worries, thank you too :)

**Comment by timothyis** [comment]
Issue created here: https://github.com/wulkano/getkap.co/issues/49
