### ISSUE TITLE
While disabling a plugin, error thrown

### ISSUE THREAD

**Issue by onwp** [wulkano/kap#1169]
**macOS version:** 13.0.1 (22A400)
**Kap version:** Version 3.6.0 (3.6.0.1846)

#### Steps to reproduce 
I enabled hide desktop icons plugin. Then when i wanted to disable it error thrown

#### Current behaviour 
Error throws up while trying to disable hide desktop icons plugin, though it seems disabled in the end

#### Expected behaviour 
It should disable plugin without throwing such an error

**Comment by onwp** [comment]
Getting this on MBP M1 chip.

**Comment by timothyis** [comment]
Hi there, could you share the error?

**Comment by onwp** [comment]
I couldn't reproduce it. If I get it again, I will copy it. Thanks.
