### ISSUE TITLE
Add key stokes  is useful

### ISSUE THREAD

**Issue by goodpaperman** [wulkano/kap#1173]
suggest: add user keyboard activity to generated gif maybe useful

**Comment by timothyis** [comment]
Hi there. Could you elaborate please?

**Comment by doot0** [comment]
@goodpaperman Have you you considered using something like https://github.com/keycastr/keycastr to do what you're asking?

**Comment by goodpaperman** [comment]
> @goodpaperman Have you you considered using something like https://github.com/keycastr/keycastr to do what you're asking?

that is what I want, and it's great !!
