### ISSUE TITLE
Wrong icon is showed when app is in a folder in Launchpad

### ISSUE THREAD

**Issue by dreamorosi** [wulkano/kap#119]
It's not a super urgent fix to do and it doesn't prevent the user from using the app but I've noticed that when the app is placed in a folder inside Launchpad its icon becomes transparent while if it stays at 'root' level the correct one with white background is shown. Also, when the folder is opened the icon returns normal.

I'm attaching a gif that shows the behaviour.
![kapture 2016-12-15 at 16 19 48](https://cloud.githubusercontent.com/assets/7353869/21229762/f8e5ea9e-c2e2-11e6-83ab-7ca88bdedcc8.gif)

**Comment by CodeTheory** [comment]
Nice catch! Thanks for the issue, we'll get this fixed. 😄

**Comment by matheuss** [comment]
Can't reproduce 😮 🤔 
<img width="147" alt="screen shot 2017-01-01 at 3 33 00 pm" src="https://cloud.githubusercontent.com/assets/4721750/21582922/91741c20-d037-11e6-9f20-1fa426d75304.png">
I wonder from where the icon you're seeing in the Folder preview comes from – AFAIK it only exists on [getkap.co](getkap.co) 🤔 @CodeTheory @skllcrn please confirm 😅

**Comment by dreamorosi** [comment]
@matheuss not sure where it comes from anyway I'd like to add that I can't reproduce the error on a retina display either but only on a not-retina one if that can help somehow.

**Comment by CodeTheory** [comment]
I also get this behaviour @matheuss. I'll look into it tonight.
