### ISSUE TITLE
Activation of Kap is slow with large displays

### ISSUE THREAD

**Issue by spikeheap** [wulkano/kap#1196]
**macOS version:** 14.0 (running on a 14" M1 Pro)
**Kap version:** 3.6.0 (3.6.0.1846)

Thanks for making Kap 🙇. I've been using it for a while with great success on my MacBook Pro, but have run into a problem trying to use a larger display.

#### Steps to reproduce

1. Plug in an Apple 27" Studio Display
2. Trigger Kap (by clicking the tray icon or using the keyboard shortcut)

#### Current behaviour

There's a delay of between 3 to 5 seconds before the Kap bar pops up and the screen dims. 

#### Expected behaviour

I'd expect the Kap bar to pop up fairly immediately after triggering the keyboard shortcut or pressing the tray icon, or some visual feedback that things are happening.

#### Workaround

It's not really a workaround, but disconnecting from the large display and using the Macbook's 14" display only reduces the delay significantly.

Thanks for taking a look :).

**Comment by Spaider** [comment]
To me this problem is also very important. For static screenshots I'm using app which is lighting fast and when I start Kap'ping, it takes painfully long time, which makes big impact on further perception of all UX.

**Comment by cyfyifanchen** [comment]
I am using 38" monitor, I've noted there is a delay, but it isn't consistent.

**Comment by klonos** [comment]
I'm seeing the same. Gets worse with multiple displays.

**Comment by spikeheap** [comment]
Ahh, I think this is a duplicate of https://github.com/wulkano/Kap/issues/1125 (sorry I didn't see that when I first opened this 🤦). I'll close this one as it looks like there's already been some progress made there.

Thanks!
