### ISSUE TITLE
keyboard shortcuts support

### ISSUE THREAD

**Issue by istommao** [wulkano/kap#121]
keyboard shortcuts support

**Comment by CodeTheory** [comment]
Hi @istommao. Could you elaborate?
What keyboard shortcuts are you looking for?

**Comment by istommao** [comment]
start and stop
for now, i can see toolbar
![image](https://cloud.githubusercontent.com/assets/5070879/21376164/c0b8163a-c76d-11e6-8849-25b3fb8b010e.png) everytime in screen recorder

generate gif speed is slow
and i found save gif file broken, can't view

**Comment by CodeTheory** [comment]
You can use <kbd>cmd</kbd> + <kbd>5</kbd> to bring up the cropper window and use <kbd>enter</kbd> to start the recording. Does this resolve your issue?

I fail to see how the time it takes to generate the gif is relevant though 🤔

**Comment by istommao** [comment]
ok I see, i think you can show keyboard shortcuts in preferences 😄

I found another  screen recorder sofaware LICEcap generate the gif very fast

**Comment by CodeTheory** [comment]
Yes, keyboard shortcut configuration is a planned feature which will display all current shortcuts as well. 😄 

Yes, I believe LICEcap and Kap use different methods to generate GIFs. We use the highest quality conversion method available to us. In turn, that makes the generation a bit slow. But you can speed this up by lowering the frame rate, or shrinking the size, of your GIF.

**Comment by istommao** [comment]
Yes I use 15 frame rate, by the way kap GUI is awesome, now i'll use kap Instead of LICEcap!

**Comment by FezVrasta** [comment]
> Yes, keyboard shortcut configuration is a planned feature which will display all current shortcuts as well. 😄

@CodeTheory any news on this feature? Right now it interferes with the shortcuts of CodePen and it's pretty annoying.

**Comment by OliverJAsh** [comment]
@CodeTheory 

> use enter to start the recording

Is there any way to stop the recording?

**Comment by allaire** [comment]
@OliverJAsh Press `Command + Shift + 5` again to stop
