### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by drocarmo** [wulkano/kap#122]
**Platform: Mac Sierra OS 10.12.2**
**Kap Version: Latest**

Every time I open the app I get this error, once I click ok the app doesn't load. Not sure if this is a known error or a one time thing I need to fix on my local machine.

<img width="532" alt="screen shot 2016-12-20 at 11 21 51 pm" src="https://cloud.githubusercontent.com/assets/2608860/21378309/21d2a88a-c70b-11e6-97e2-4e025ad7debb.png">

**Comment by doot0** [comment]
Hey @drocarmo. Can you run `ls -lah`against `~/.config/configstore` and let me know what the results are? Thanks.

**Comment by drocarmo** [comment]
@doot0 here are the results:
```
total 8
drwxr-xr-x  3 root        staff   102B Nov  8  2013 .
drwxr-xr-x  4 pedrocarmo  staff   136B Nov  8  2013 ..
-rw-r--r--  1 pedrocarmo  admin    45B Jun 20  2014 update-notifier-bower.yml
```

**Comment by sindresorhus** [comment]
Older versions of Configstore would save with the incorrect permissions because of a bug in one of its dependencies. Seems like you're still stuck with that. Try deleting the `~/.config/configstore` directory.

**Comment by drocarmo** [comment]
that worked! cheers @sindresorhus @doot0

**Comment by binarysprocket** [comment]
Was getting this same error but turns out my problem was an absence of the `configstore` directory under `~/.config`. Once I manually created that directory, all was well.
