### ISSUE TITLE
Note re-calculated file size in the editor when Kapture size is modified

### ISSUE THREAD

**Issue by bnb** [wulkano/kap#125]
**Platform:**` Darwin Tierneys-MacBook-Pro.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64`
**Kap Version:** 1.0.0
### Current behaviour
When recording, the recording shows the size in kilobytes, megabytes, and gigabytes. Once in the editor, the user has the option to change the dimensions of the output file. Changing the dimensions of the output file changes the size of it, and may be important for users to know because of file size limitations.

### Expected behaviour
Display _estimated_ file size output for given dimensions, framerate, and other settings of a Kapture in the editor.

### Use case
 I consistently use Kap to capture GIFs for Twitter, and have to consistently re-record the GIFs because the file size is over

**Comment by skllcrn** [comment]
The estimated file size shown while recording is only that, an estimate, and an inaccurate one depending on the file type you select (as I'm sure you've noticed!) If we could implement a method to accurately estimate the file size in the various file formats then that's something we'd definitively want to show when editing!

**Comment by skllcrn** [comment]
Closing in favour of #172 since this issue isn't reflective of our current UI.
