### ISSUE TITLE
Add a copy to clipboard option

### ISSUE THREAD

**Issue by altryne** [wulkano/kap#126]
Please add copy to clipboard option on git output. 

This was previously requested in #116 but was closed due to the fact you can't paste a gif into Github, but there are definitely other usages of clipboard outside of Github. (Slack, Youtrack, Facebook)

**Comment by CodeTheory** [comment]
We have a plan for supporting this. Thanks for your issue!

**Comment by albinekb** [comment]
Should be possible now https://github.com/electron/electron/pull/9243

**Comment by kevva** [comment]
https://github.com/kevva/kap-clipboard

Requires `electron@1.7.2`.

**Comment by albinekb** [comment]
Does it work? Can you paste the gif directly into github for example? 😍  @kevva

**Comment by kevva** [comment]
Nope, I opened an issue for it https://github.com/kevva/kap-clipboard/issues/1. When pasting to GitHub (or any other place) it only pastes a PNG instead.

**Comment by sindresorhus** [comment]
> When pasting to GitHub (or any other place) it only pastes a PNG instead.

That's a bug in Chrome: https://twitter.com/sindresorhus/status/862597219517554688

**Comment by skllcrn** [comment]
https://github.com/wulkano/kap/issues/154#issuecomment-341141681
