### ISSUE TITLE
Reduce high-pixel-ratio recordings to standard pixel ratio

### ISSUE THREAD

**Issue by altryne** [wulkano/kap#127]
Hey guys, 
I've been enjoying Kap very much, but since I moved to a 27" high pixel ratio screen, all my kaptures are 10MB+ even for very low framerates. 

Can we have the option to record in standard definition, even if my screen is twice the pixel ratio? Or downscale maybe exactly by 2? 

I'd love to continue recording gifs at my regular resolution, without having them at 16-20MB all the time

**Comment by doot0** [comment]
Without adding extra UI, would adding the ability to perform basic mathematic operations in the resolution inputs be a suitable solution? This would allow a user to type something like `400/2` which would automatically resolve to `200`. Not certain if that covers your use case.

**Comment by altryne** [comment]
I would love this as a 1-time setting somewhere in settings, so I can set it and forget it. Not sure if adding mathematics to the aspect ratio  will be discoverable enough for this.

**Comment by skllcrn** [comment]
We're looking into better solutions for handling recordings of high definition screens. For now you can cut the width and height of your @2x recordings in half. There's some more information regarding compression and file size in #117!

**Comment by altryne** [comment]
Thanks @skllcrn and @doot0 , let me know if I can help test things when it comes to development of this!

**Comment by skllcrn** [comment]
Closing in favour of #234
