### ISSUE TITLE
No audio in recordings with typing behaviour

### ISSUE THREAD

**Issue by natsu90** [wulkano/kap#128]
**Platform:**

OSX 10.11.5

**Kap Version:**

1.0.0.134

### Steps to reproduce

Create a screen recording including audio while typing somewhere like renaming a file

### Current behaviour

Audio is missing in videos with typing behaviour

### Expected behaviour

Audio to be included

### Workaround

None

**Comment by skllcrn** [comment]
This is really weird, can't reproduce. Are you exporting to MP4?

**Comment by matheuss** [comment]
@natsu90 I think this is a duplicate of #124. Could you confirm?

**Comment by natsu90** [comment]
@matheuss You are right! The audio is there when I did with less than 10 secs. My bad.
