### ISSUE TITLE
Kap always shows marquee on 'system' display.

### ISSUE THREAD

**Issue by steveharman** [wulkano/kap#131]
**Platform:**
Darwin Steves-iMac.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

**Kap Version:**
1.0.0 (1.0.0.134)

### Steps to reproduce
With multiple screens attached to a desktop Mac, open Kap from a Finder window on the non-System* display.  (* where the menu bar is dragged in the Mac's Display system preference)

Click on the red 'select recording area' tool in Kap.

### Current behaviour
The marquee always appears on the Mac's *system* display, not the display I launched Kap on.

### Expected behaviour
Should show the marquee on the screen I launched Kap on, where I want to do my recording.

### Workaround
Drag marquee from the System display over to one of the other displays,.

**Comment by skllcrn** [comment]
Fixed in #494
