### ISSUE TITLE
Kap's interface gets captured in the recording

### ISSUE THREAD

**Issue by dishahsharma** [wulkano/kap#133]
When I record, Kap's interface also shows up in the first 2-3 seconds or so! Please see the exported GIF to see what I mean. Thanks!

![bug kapture 2017-01-24 at 22 55 49](https://cloud.githubusercontent.com/assets/22858698/22290339/3753e19c-e326-11e6-9641-7150908255f2.gif)

**Comment by skllcrn** [comment]
Hi @dishahsharma, this is a cuplicate or #3. I'll be closing this one, but thanks for your issue!
