### ISSUE TITLE
Move from `gulp` to `webpack`

### ISSUE THREAD

**Issue by matheuss** [wulkano/kap#135]
We should completely move our build step from `gulp` to `webpack` 🕵️

**Comment by matheuss** [comment]
https://github.com/wulkano/kap/blob/feature/a-whole-new-world/webpack.config.js ✅

**Comment by Khaledgarbaya** [comment]
@matheuss I saw your `TODO` about the `devtool` what was the value you did set ?

**Comment by matheuss** [comment]
@Khaledgarbaya IIRC I tried every option 😓
