### ISSUE TITLE
Enhancement: Add delay after new user input on canvas dimensions

### ISSUE THREAD

**Issue by onordbo** [wulkano/kap#137]
Currently when updating the canvas dimensions through the control panel, there's a minor delay occurring while the canvas is animating, after a new value has been added to an input field. Consider adding a minor delay _(maybe 100ms?)_ to the animation trigger after the `keyup` event or something in a  similar fashion, to prevent this from happening.

_An added benefit of implementing this would also be that the canvas doesn't look/feel completely spastic while updating the dimensions numerically. **See attached GIF for demo.**_

***

![spastic-canvas mov](https://cloud.githubusercontent.com/assets/4263132/22478951/4ef62f74-e7ec-11e6-9e6f-10677e7c7b84.gif)

**Comment by CodeTheory** [comment]
Perhaps we should delay this indefinitely until the user either hits enter or leaves the input? cc @onordbo

**Comment by onordbo** [comment]
I'd say both @CodeTheory. Either trigger it `onBlur` or `Return` or after `500ms` or something along those lines.

**Comment by albinekb** [comment]
I'd say, trigger it both after 500ms (debounce), but also on `blur` *or* `enter` events 👌
