### ISSUE TITLE
freeze on first run with 2 monitors

### ISSUE THREAD

**Issue by vladimirprieto** [wulkano/kap#141]
**Platform:**
Darwin MacBook-Pro-de-Vladimir.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

**Kap Version:**
Versión 1.0.0 (1.0.0.134)

### Steps to reproduce
first open: open up app **with 2 monitors connected**

### Current behaviour
works after unplug the external monitor

### Expected behaviour
no freeze

### Workaround
unplug external monitor, kill app, open app again and then work ok even when external monitor was connected -again-

**Comment by munvier** [comment]
I have dual monitor screens and your workaround works. But kind of painful ...

**Comment by skllcrn** [comment]
We haven't been able to reproduce this and have not had additional reports of it, can you try again on the latest [`master`](https://kap-artifacts.now.sh/master) @vladimirprieto and @munvier?

**Comment by vladimirprieto** [comment]
i tryed and works fine.

using version 1.0.1 (1.0.1.170)
under Mac OSX Sierra 10.12.6

thanks!

**Comment by skllcrn** [comment]
Thank you @vladimirprieto!
