### ISSUE TITLE
Can we have auto Imgur upload as well?

### ISSUE THREAD

**Issue by ahmadawais** [wulkano/kap#142]
This is not an issue but rather a request. I'd like to ask if we can build in a functionality to upload the images and gifs to Imgur via API. It's pretty simple API!

**Comment by CodeTheory** [comment]
🔜

**Comment by ahmadawais** [comment]
Also a screenshot feature with keyboard shortcuts would be nice. And the ability to mask those screenshots to a custom domain?

**Comment by StefMa** [comment]
I like the idea. Just press any shortcut, create the screenshot and it will be instantly uploaded. After the upload is finish a download url will be saved in your clipboard...

But: I don't know if this the main focus of Kap.
Don't get me wrong here and I don't want to make advertising.
But to solve the problem above I develop [Geist](https://github.com/StefMa/Geist). It is exactly what are you looking for.

As I said. I like the idea.
And a feature in Kap like a button which say "Share to imgur" is nice. But the instantly upload (after creating the shortcut) and all the stuff isn't really the problem which Kap will be solve.

**Comment by skllcrn** [comment]
https://github.com/wulkano/kap/issues/147#issuecomment-280944691

**Comment by CodeTheory** [comment]
https://github.com/kevva/kap-imgur 😄 
Plugins are nearly here!
