### ISSUE TITLE
Touch Bar support

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#143]
Depends on https://github.com/electron/electron/pull/8095.

Would be cool to display the elapsed recording time and a stop button in the Touch Bar.

If you don't have a native Touch Bar, you can use: https://red-sweater.com/touche/

**Comment by skllcrn** [comment]
https://github.com/electron/electron/issues/7781#issuecomment-278121145

**Comment by Khaledgarbaya** [comment]
it is here finally https://electron.atom.io/blog/2017/03/08/touch-bar-support but the version of electron still in beta, I would love to work on this once you guys decide to move to Electron **v1.6.3+** and of course when the version is out of the beta

**Comment by matheuss** [comment]
@Khaledgarbaya feel free to bump the dependency to 1.6.3 🙌

**Comment by Khaledgarbaya** [comment]
@matheuss @skllcrn any preferences on what you want to show in the TouchBar. 
I was thinking about start/stop recording mainly

**Comment by sindresorhus** [comment]
Note the limitation that we can only be in the Touch Bar when the Kap window is focused, so not during recording.
