### ISSUE TITLE
Recording start time is unclear

### ISSUE THREAD

**Issue by justinrobots** [wulkano/kap#146]
I initially assumed that the "Getting ready..." phase was a time to prepare before recording but realized that Kap will actually start recording during that phase, before it says recording has begun. 

All of the "Getting ready..." phase is shown when previewing a capture:
![kap-pre-save](https://cloud.githubusercontent.com/assets/3358707/22942484/f9b41150-f2a6-11e6-8603-e3c688abd058.gif)

However, the saved capture appears to have trimmed some (not all) of that phase off:
![kap-no-delay](https://cloud.githubusercontent.com/assets/3358707/22942192/bb5c3b5e-f2a5-11e6-9e43-9715c48e859c.gif)

This is confusing, makes timing a recording difficult, and increases the need to edit post-recording.

Not showing the first part of the recording that will be trimmed off during preview would be helpful. An option to set a recording delay and display a countdown that lets users know _exactly_ when the recording starts would be even more helpful.

**Comment by matheuss** [comment]
@justinrobots thanks for the detailed report! We're already discussing/fixing this on # 3 🙌
