### ISSUE TITLE
Support Imgur upload

### ISSUE THREAD

**Issue by bhargavjoshi** [wulkano/kap#147]
It would be great to record the screen, and the gif could be automatically uploaded to any of these following services and give us a direct link to that gif 

- imgur
- Dropbox
- Google Drive

I am using this app [mac2imgur](https://github.com/mileswd/mac2imgur) this app takes the screen capture we do on Mac and uploads it to imgur and gives back a direct link to that image on imgur it's open-source maybe you can look at the source and use it to get an idea.

**Comment by skllcrn** [comment]
We're working on a feature that will open up for things like this, we're planning on shipping it as part of the [2.0 project](https://github.com/wulkano/kap/projects/2). Leaving this issue open to help avoid duplicates.

**Comment by skllcrn** [comment]
Support for plugins is on master! You can find the docs here https://github.com/wulkano/kap/blob/master/docs/plugins.md

**Comment by skllcrn** [comment]
An Imgur plugin will be available in Kap 2.0! You can check out the work @kevva has done on it at https://github.com/kevva/kap-imgur. Suggest narrowing the scope of this issue to Imgur only (but keep it open to avoid duplicates until launch), and create new plugin request issues for Dropbox and Google Drive.

**Comment by skllcrn** [comment]
The Imgur plugin is available in the Kap 2.0 Beta!

**Comment by orlandovallejos** [comment]
This feature is so cool, but it'd be nice to upload the gifs to the users account. I know it's possible because a tool called Share X do it. It lets you add your account and they images uploads directly to you account.

**Comment by kevva** [comment]
There's an issue for it here https://github.com/kevva/kap-imgur/issues/3.
