### ISSUE TITLE
No new folder button when choosing default folder

### ISSUE THREAD

**Issue by onordbo** [wulkano/kap#152]
Title says it all, pretty much. My guess is that it's a matter of defining what type of file browser dialogue is called when you open the setting.

<img width="728" alt="preferences" src="https://cloud.githubusercontent.com/assets/4263132/23478357/6abd09bc-fec1-11e6-93ce-e8e375b183c7.png">

Latest production build (1.0.0).

**Comment by sindresorhus** [comment]
Yup. I think we just need to add `createDirectory` in `properties` for the open dialog: https://electron.atom.io/docs/api/dialog/#dialogshowopendialogbrowserwindow-options-callback

**Comment by Khaledgarbaya** [comment]
Yep, if I am not mistaken the change should be made [here](https://github.com/wulkano/kap/blob/master/app/src/main/index.js#L451)

**Comment by Khaledgarbaya** [comment]
@sindresorhus I can't see that option available in the `showSaveDialog ` https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowsavedialogbrowserwindow-options-callback

**Comment by matheuss** [comment]
@Khaledgarbaya the correct place is here: https://github.com/wulkano/kap/blob/485d2afe52bd6e4aab4f51851b1f9358346828f5/app/src/renderer/js/preferences.js#L80 😄

**Comment by Khaledgarbaya** [comment]
Ok since I had some free time I made a [PR](https://github.com/wulkano/kap/pull/153) for this ;)

**Comment by skllcrn** [comment]
Thanks you again @Khaledgarbaya 🎉
