### ISSUE TITLE
Show keyboard input

### ISSUE THREAD

**Issue by superfunkminister** [wulkano/kap#158]
Very useful functionality that a lot of other screen capturing tools possess!

**Comment by skllcrn** [comment]
You can toggle mouse clicks from the main app window by clicking the mouse icon, if you also want to highlight clicks you can turn that on in the app preferences. You can't currently highlight clicks without showing the cursor. Showing keystrokes is a feature we've been talking about a lot, it would be really neat for screencasts like tutorials and so on.

**Comment by superfunkminister** [comment]
Awesome!

**Comment by albinekb** [comment]
https://github.com/miguelmota/global-keypress
Just need to add support for modifier keys then it's 💯 

we'll need to prompt the user for sudo access though, since it's basically a keylogger 😄

**Comment by koddsson** [comment]
FWIW I've been using [`keycastr`](https://github.com/keycastr/keycastr) in unison with `kap` and it's been pretty great.

**Comment by albinekb** [comment]
Cool @koddsson, the `global-keypress` plugin has support for modifiers now, however it's mac-only and I don't think we could ever handle linux+windows in addition to the mac version.

So we should choose one of these options:
- Have this functionality as a plugin (per platform, not maintained by Kap-crew)
- Refer to `keycastr` (or similar per platform) in the docs and/or in the app
- Only support macOS (via global-keypress & sudo password everytime you want to record keypresses)

and take this issue from there. IMHO.

**Comment by sindresorhus** [comment]
> Refer to keycastr (or similar per platform) in the docs and/or in the app

👍

**Comment by skllcrn** [comment]
Closing this as I believe using `keycastr` in unison with Kap is the best currently available solution. I'll still tag it as a plugin request and happy to re-open the issue if anyone wants to explore that possibility. The docs for plugins are available at https://github.com/wulkano/kap/blob/master/docs/plugins.md

**Comment by krainboltgreene** [comment]
Hilariously keycastr doesn't display the keys when kap is recording. I wish I was joking.
