### ISSUE TITLE
Kap does not disappear before starting to record

### ISSUE THREAD

**Issue by jaredreich** [wulkano/kap#160]
**Platform:** Mac 10.11.6
**Kap Version:** 1.0.1
### Steps to reproduce
- Record anything with Kap
- Open the saved video, look at the first couple frames
- Notice that Kap has not disappeared before starting the video
### Current behaviour
Kap does not disappear before starting to record
### Expected behaviour
Kap to disappear before starting to record

### Demo
<img width="1015" alt="screen shot 2017-03-23 at 12 53 37 pm" src="https://cloud.githubusercontent.com/assets/8563847/24265021/c710eeba-0fc7-11e7-8f8a-2aa1b5545ae0.png">

**Comment by matheuss** [comment]
#3 🙌
