### ISSUE TITLE
Extremely slow resizing and moving of selection window

### ISSUE THREAD

**Issue by kristojorg** [wulkano/kap#161]
**Platform:**
Darwin rMBP 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

aka Mac OS Sierra 10.12.3

**Kap Version:**
1.0.1

### Steps to reproduce

Open kap, click the selector button to open selection window. Try to move or resize selection window.

### Current behaviour
Very very laggy, takes multiple seconds for selection window to catch up to cursor.

### Expected behaviour
Smooth resizing

### Details:

Here is a screenshot of the timeline for the selection window. Looks like lots of heavy hits to the GPU. I'm wondering if this has to do with it being transparent?

<img width="939" alt="screen shot 2017-03-29 at 11 30 54 am" src="https://cloud.githubusercontent.com/assets/4398775/24463109/ddcd8d38-1473-11e7-987c-8aac0fa7d44d.png">

**Comment by skllcrn** [comment]
We still haven't been able to reproduce this issue, and haven't seen other reports of it. Could you test it again on [`master`](https://kap-artifacts.now.sh/master) @kristojorg?
