### ISSUE TITLE
Animated menu bar icon

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#162]
Indicate that Kap is preparing to record with an animated menu bar icon

**Comment by CodeTheory** [comment]
cc @onordbo

**Comment by skllcrn** [comment]
It looks like we'll need to create a PNG sequence and repeatedly call `-setImage`. Something like this would be neat: 

![kapture 2017-04-12 at 1 18 32](https://cloud.githubusercontent.com/assets/8440026/24934794/1cef1df6-1f1e-11e7-8d71-02c45024ae37.gif)

**Comment by vadimdemedes** [comment]
What do you think about showing a countdown inside the menubar icon, like in ScreenFlow?

1. Select area
2. Hit record
3. Immediately hide window
4. Show countdown in the menubar icon (3... 2... 1...)
5. Record

**Comment by skllcrn** [comment]
@onordbo has worked on a better way to indicate that Kap is loading when attached to the menubar. We can't know exactly when the recording starts, but there are ways to work around this. More on that in #3, also relates to #53. Combining all this with #150 and @albinekb's work in https://github.com/wulkano/kap/pull/198 will create a great flow for super quick recording and sharing.
