### ISSUE TITLE
Export to APNG

### ISSUE THREAD

**Issue by FezVrasta** [wulkano/kap#164]
The browser support for APNG seems pretty good nowadays, do you have plans to support it?

https://en.wikipedia.org/wiki/APNG#Support

**Comment by CodeTheory** [comment]
Yes, we'll definitely look into supporting it. All for progress of better formats!

**Comment by fokusferit** [comment]
I did a initial search through the code and ffmpeg and it seems straight forward -> adding a new convert function to convert.js + some addition to the editor + main.js . 

And since v3.3 ffmpeg supports apng. If no one is currently working on it, I'd like to do it.

**Comment by CodeTheory** [comment]
Added in #185 😄

**Comment by FezVrasta** [comment]
Cool!
