### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by pabitrapadhy** [wulkano/kap#165]
Hello,

`npm install` is failing for me, with the attached log file below.
please look over this issue or specify any details that need to be considered before building
like node version, some permission, etc etc.

Platform : Mac OSX Sierra 10.12.4
Branch : master

[https://drive.google.com/open?id=0B-IgfsAh9Mn4X0cxVjMwUlJKM1U](url)

[https://drive.google.com/open?id=0B-IgfsAh9Mn4dEZlNGFaaVpQTUk](url)

Please let me know, if any other details need to be added.
Thanks.

**Comment by CodeTheory** [comment]
I think this is a problem with your node version @pabitrapadhy. Please try upgrading and see if that fixes you issue.

**Comment by pabitrapadhy** [comment]
@CodeTheory : could you please let me know.
what node version is required for the setup

This is my current version - 
`Pabitra-MBP:kap pabitra$ node -v`
`v4.3.2`
`Pabitra-MBP:kap pabitra$ npm -v`
`2.14.12`

**Comment by Khaledgarbaya** [comment]
I think you will need node v6+

**Comment by pabitrapadhy** [comment]
I have installed the latest node through NVM and checked with node version:
`6.10.3` and `v7.10.0`
and npm version:
`3.10.10`

But the issue seems to persist as attached in the log file.
[https://drive.google.com/open?id=0B-IgfsAh9Mn4WnVYSDNlaEZoSEE](url)

If someone, could try to list down a fresh install with all steps, node version and other dependencies
that would be great :)

**Comment by Khaledgarbaya** [comment]
oh wow, the problem is here actually `http://evermeet.cx/ffmpeg/ffmpeg-83544-g965f35b.7z` the URL to download ffmpeg is returning 404. 
Looks like the the ffmpeg download link is broken/changed.

The link in the code is [here](https://github.com/wulkano/kap/blob/master/scripts/download-ffmpeg.js#L12)

**Comment by pabitrapadhy** [comment]
Thanks @Khaledgarbaya 
I managed to get it to work, by changing the link to the latest distribution.
[http://evermeet.cx/pub/ffmpeg/snapshots/ffmpeg-85767-gdec2fa8.7z](url)
in the file : `scripts/download-ffmpeg.js`

My app is generated successfully.
For others to lookup. I used the following :
`node version: v7.10.0`
`npm version: 4.5.0`

**Comment by pabitrapadhy** [comment]
Closing the issue.
However, I got this issue as in the screenshot below,
I believe this is because, I need to sign the app with my mac developer signing identity.
please correct me, if I am wrong.
Thanks for all your help.
<img width="422" alt="screen shot 2017-05-07 at 1 22 25 am" src="https://cloud.githubusercontent.com/assets/8029485/25775523/6723e014-32c4-11e7-9d27-04993e3cb6d2.png">
