### ISSUE TITLE
Current ffmpeg download script's url gets 404

### ISSUE THREAD

**Issue by hikerpig** [wulkano/kap#167]
While trying to pack the app, I fail to download ffmpeg binary using `npm run ffmpeg`

```javascript
//    scripts/download-ffmpeg.js
const FFMPEG_URL = 'http://evermeet.cx/ffmpeg/ffmpeg-83544-g965f35b.7z';
```

Platform : Mac OSX Sierra 10.12.4
Branch : master (bad50a5)

**Comment by Khaledgarbaya** [comment]
This [issue](https://github.com/wulkano/kap/issues/165) also is related

**Comment by matheuss** [comment]
Fixed, thanks for reporting 😄
