### ISSUE TITLE
Recording with Kap on one display and recording frame on another captures with undesired vertical offset

### ISSUE THREAD

**Issue by Glutnix** [wulkano/kap#169]
**Platform:** Darwin mybox.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
**Kap Version:** Version 1.0.1 (1.0.1.170)
### Steps to reproduce

Set up your displays with one display having its top edge higher than another. 

![screen shot 2017-05-09 at 3 06 48 pm](https://cloud.githubusercontent.com/assets/88983/25834063/93cb7d28-34c9-11e7-9d25-d9829a15a73a.png)

![screen shot 2017-05-09 at 3 12 37 pm](https://cloud.githubusercontent.com/assets/88983/25834202/72683c10-34ca-11e7-92e8-14be0baae99e.jpg)

Open Kap's main window, so it's attached to the menu bar, on the screen with the lower top edge.
Set the recording frame to record something on the other monitor.

![screen shot 2017-05-09 at 3 21 24 pm 2](https://cloud.githubusercontent.com/assets/88983/25834340/5eb97390-34cb-11e7-822b-a1d59874d994.jpg)
![screen shot 2017-05-09 at 3 21 24 pm](https://cloud.githubusercontent.com/assets/88983/25834339/5eb6cf82-34cb-11e7-8fd6-39b8fb02c276.jpg)

### Current behaviour
The screen recording's captured frame will be vertically offset from the intended frame in such a way that the vertical offset will be the vertical offset of the two monitors

Here is a gif that was supposed to be of the finder window shown in previous screenshots.

![offset capture](https://cloud.githubusercontent.com/assets/88983/25834349/6e017e7e-34cb-11e7-8288-8facce5f65b9.gif)

### Expected behaviour

Captured recording frame should match desired area as drawn by selection area. 

### Workaround

Detach Kap from menubar and bring to same display as recording frame. Not necessarily desirable if you wish to record a full screen.

**Comment by sindresorhus** [comment]
Most likely there's something wrong with the math in https://github.com/wulkano/kap/blob/8a4530b8dfe8ab6d48fe6c332ebb809c5dfd413f/app/src/renderer/js/main.js#L162-L175, but I don't have multiple monitors, so I can't really debug this.

One suspectful thing there is the use of `Math.abs()`. I don't think that accounts for the fact that the [bounds could be negative](https://github.com/electron/electron/issues/1036#issuecomment-71083831).

For example:

![image](https://cloud.githubusercontent.com/assets/170270/26033288/7cf5ebde-38d3-11e7-8e05-197a6f6b36a3.png)


@matheuss Any thoughts? Maybe we should request Electron add something like [`NSWindow.convertFromScreen`](https://developer.apple.com/reference/appkit/nswindow/1419603-convertfromscreen), so we can use the system API to convert it?

**Comment by skllcrn** [comment]
Could you see if you're able to reproduce this issues on the [latest beta release](https://github.com/wulkano/kap/releases) @Glutnix?

**Comment by Glutnix** [comment]
Seems to work fine now, though I don't have exactly the same set up as before. Good work people!
