### ISSUE TITLE
Ask user permission before tracking to GA

### ISSUE THREAD

**Issue by petetnt** [wulkano/kap#17]
Currently the app sends data to GA automatically, which while anonymous is still undesirable for some people.  The app s/could/should ask for user permission on `firstRun` and set the `insight.optOut` flag accordingly, with an additional toggle somewhere else for later use.

**Comment by matheuss** [comment]
We'll have it along with a full preferences screen in a future release, @petetnt! Thank you for your feedback 🙌

**Comment by petetnt** [comment]
Awesome 👍

**Comment by CodeTheory** [comment]
@petetnt We now support this in preferences 😄

**Comment by petetnt** [comment]
That's awesome! Keep up the good work!
