### ISSUE TITLE
Emulate built-in rectangle drawing

### ISSUE THREAD

**Issue by chibigoku04** [wulkano/kap#171]
**Platform:** Darwin c02rj0c7fvh8 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
**Kap Version:** 1.0.1

Not a bug, more of a want. I'd like the ability to draw my own rectangle, similar to how the native OSX screen capture utility does. Preferably, after a customized keyboard shortcut, but it could make sense after hitting the capture button from the popout.

**Comment by sindresorhus** [comment]
Why? I personally don't like how the macOS screenshot selector works. I can never get it perfect by dragging. I always miss it a little bit at either of the sides.

**Comment by chibigoku04** [comment]
It's not that I don't like the existing crop selector, but I feel like it slows me down compared to the built-in tool.

I have to hit the button, resize the rectangle, hit the record/capture button. Whereas with the built-in screenshot, or Jing, I can hit a shortcut, draw my rectangle and it's done, or prompts to start recording video in the case of Jing. As for missing the mark with the built-in screenshot, if it's as simple as hitting a keyboard shortcut, hit it again and correct. It doesn't slow you down anymore than the current process. Personal opinion/preference.

**Comment by sindresorhus** [comment]
> hit the record/capture button.

Just press enter ;)

We definitely need a global shortcut to record though. Then you could just: Hit keyboard shortcut, resize, enter.

**Comment by CodeTheory** [comment]
@sindresorhus we have CMD + SHIFT + 5, no?

**Comment by chibigoku04** [comment]
> Just press enter ;)

Wasn't aware of that. But I, personally, would still prefer the option to draw my own rectangle without resizing a pre-built box.

**Comment by chibigoku04** [comment]
> @sindresorhus we have CMD + SHIFT + 5, no?

That does work, is that documented anywhere?

**Comment by CodeTheory** [comment]
Not currently, no.

**Comment by onordbo** [comment]
Creeping in on this thread with a side-note feature request on this issue to implement a settings feature for **customizing the keyboard shortcut** to trigger Kap, so it doesn't _potentially clash with other applications_ that might be mapped to the same combination.

**Comment by sindresorhus** [comment]
@CodeTheory Ah, even I forgot about that. We should get that documented better.

**Comment by skllcrn** [comment]
#150

**Comment by skllcrn** [comment]
From what I understand @chibigoku04, what you would like is to activate the "cropper" and draw your selection on the screen from scratch, rather than to resize by dragging the corners of the selected area? 

If that is the case it's simply not possible due to various restrictions and limits on the tech. We are working on improving the selection tool, rethinking the entire implementation of it. There are a number of related issues such as #6 and #139, you can follow along there for updates. 

Thank you!
