### ISSUE TITLE
Add the option to only record the sound

### ISSUE THREAD

**Issue by sepehr** [wulkano/kap#184]
I wonder, is there any plans to add the feature to only record sound?

**Comment by sindresorhus** [comment]
Why? Kap is a screen recorder.

**Comment by sepehr** [comment]
Yea, I know that.

Because I always find myself opening QuickTime to record audio and it always fails me with stupid "try again" errors. And afaik there are no handy, free and opensource app to do that.

Kap is sitting right on my menu bar and I find myself wishing it could record sounds for me, too. Please feel free to close this, if it sounds like a stupid idea.

_P.S. BTW, thanks for developing Kap._

**Comment by CodeTheory** [comment]
I don't know, it could be cool in the long run @sindresorhus. Especially with the planned feature of exporting multiple formats. Could record audio and video at the same time and export a file for each. (also could be in the scope of plugins in the future)

**Comment by skllcrn** [comment]
What we could do as a core app feature is add a setting to record the audio and video to separate files

**Comment by fokusferit** [comment]
I would like to understand Why there is a need for only audio recording ? E.g. podcasting ? For me the purpose of a screen recorder is clear but having a audio-only option could blur the line too much.  

Maybe an idea could be to use Kap Branding, existing Electron Code and create a separate "Kap Audio" ? Then you could collect some data and see if people are really going crazy about it 😄

**Comment by skllcrn** [comment]
It's highly unlikely that we'll do audio only, see my reply earlier in this thread https://github.com/wulkano/kap/issues/184#issuecomment-303063280

**Comment by sepehr** [comment]
As a user, I think that recording audio and video in separate files is a great idea!

**Comment by skllcrn** [comment]
Closing this as we've decided it's out of scope after further discussion.
