### ISSUE TITLE
App should not stay on top when changing desktops

### ISSUE THREAD

**Issue by timothyis** [wulkano/kap#188]
**Platform:** Mac OS Sierra 10.12.5
**Kap Version:** Latest and latest master
### Steps to reproduce
- Open kap and drag away from the menubar so that it is a standalone window
- Switch switch to another desktop to see that Kap is still visible and on-top
### Current behaviour
This is a fullscreen window of Spotify with Kap still on top
![image](https://cloud.githubusercontent.com/assets/1695613/26500064/8d65c824-422c-11e7-8929-d81b2e2208a9.png)
Does _not_ happen when Kap is in the menubar but does flash briefly when switching from a desktop where Kap in menubar mode is visible.
### Expected behaviour
Kap should remain on the desktop it is opened on until the user clicks the Kap icon to open it on another desktop pane.
### Workaround
N/A

**Additional Information:**
To explain this a bit further, imagine you have a fullscreen window of Atom, a terminal, sketch, photoshop, etc. and you wanted to record something on chrome on your main desktop. If you switch back to a fullscreen app on another desktop, Kap still follows and gets in the way. You need to close it yourself. The most common behaviour should be that the user re-opens Kap on that desktop because they want it there.

**Comment by skllcrn** [comment]
This should be fixed on [`master`](https://kap-artifacts.now.sh/master)

**Comment by CodeTheory** [comment]
This still happens 😅
