### ISSUE TITLE
Window not horizontally aligned with menubar icon

### ISSUE THREAD

**Issue by tylerhowarth** [wulkano/kap#19]
![image](https://cloud.githubusercontent.com/assets/56019/19131224/7d298184-8b03-11e6-9487-69ae76f5483c.png)

Looks like the window needs to shift over to the right about ~10px to the right or so to horizontally align with the circle.

**Comment by CodeTheory** [comment]
We've also experienced this, but only once each. If you drag the window from the tray and then put it back, it should fix itself. We don't know what causes it exactly but since we don't deal with it, we believe the issue is up-stream. Will investigate more!

**Comment by tylerhowarth** [comment]
This has been fixed for me

**Comment by CodeTheory** [comment]
It still exists, @tylerhowarth. The problem can be reproduce by waiting for the time to change or the percentage of battery changes. Unfortunately, I think it's upstream. So we can't fix it 😞
