### ISSUE TITLE
The purpose of mouse icon isn't clear

### ISSUE THREAD

**Issue by vadimdemedes** [wulkano/kap#194]
<img width="170" alt="screen shot 2017-05-29 at 4 22 13 pm" src="https://cloud.githubusercontent.com/assets/697676/26551525/aa064f7e-448b-11e7-979d-20eb3386f254.png">

It's not clear what is mouse icon for in the main window. It has no tooltip, so I clicked it several times to see what it changes, but to no effect. Only later, @sindresorhus explained to me in person, that this toggles the visibility of the mouse cursor while recording.

The simplest thing we could do to improve this is to add tooltips to both mouse and microphone icons. I'd also add a disabled version of the mouse icon, similar to microphone.

<img width="56" alt="screen shot 2017-05-29 at 4 27 20 pm" src="https://cloud.githubusercontent.com/assets/697676/26551531/b6be9460-448b-11e7-9259-9596b7ffed96.png">
<img width="50" alt="screen shot 2017-05-29 at 4 27 24 pm" src="https://cloud.githubusercontent.com/assets/697676/26551536/bac6bdbc-448b-11e7-83b5-9e35d2dee916.png">

**Comment by CodeTheory** [comment]
In 2.0 the mouse icon has been removed, presumably to live within preferences instead. Preferences supports descriptions. cc @skllcrn

**Comment by skllcrn** [comment]
The option to show cursor isn't as commonly used as audio toggling in addition to having advanced options like highlighting clicks. Because of this we've moved it to live exclusively in preferences.

**Comment by skllcrn** [comment]
Also, did you just announce streaming @CodeTheory 🙈

**Comment by vadimdemedes** [comment]
Ok, sounds good!
