### ISSUE TITLE
Split the `ffmpeg` download script into a separate package

### ISSUE THREAD

**Issue by albinekb** [wulkano/kap#197]
Hi! Kap's convert functions is very useful for other things than kap, what do you think of making them their own lib?

Also, it would be 👌  to do the same with ffmpeg?

I'll help if you agree 🎉 

🙏

**Comment by sindresorhus** [comment]
I agree about splitting out the ffmpeg download thing or use something that exists, but not sure about `convert.js`. It's nice having it in the repo for now so we can iterate quickly on it. Can always be extracted later on. If we extract `convert.js`, other projects will start using it and come with demands that we don't need and it's going to be hard to keep it focused.

**Comment by sindresorhus** [comment]
Ugh, it's really annoying that the `ffmpeg` script runs every time I run `npm install`. We should prioritize getting it into a separate package.

**Comment by sindresorhus** [comment]
Existing modules:

- https://www.npmjs.com/package/ffmpeg-static (all OSes)
- https://www.npmjs.com/package/ffbinaries (all OSes)
- https://www.npmjs.com/package/ffmpeg-downloader (downloads only the current platform binary)
- https://www.npmjs.com/package/@ffmpeg-installer/ffmpeg (downloads only the current platform binary)

The last one looks like our best option.
