### ISSUE TITLE
Add "crop service" plugin support

### ISSUE THREAD

**Issue by albinekb** [wulkano/kap#199]
Awesome work with the plugin support 💯 

It would be awesome plugins could supply a crop-service

- Add setting in preferences to choose crop-service (default to the current one)
- When you click the crop button, that module is run and outputs the `cropArea` sent to aperture

for example: "select app window", and "drag rectangle", the latter i have a prototype of:

![crop](https://cloud.githubusercontent.com/assets/5027156/26578867/d14eb87c-4531-11e7-9c9a-0c8f9b0c44ea.gif)

(just like macOS still image capturing)

I'll make a PR if you think this is a good idea 🥇

**Comment by sindresorhus** [comment]
Can you elaborate on *why*? I'm curious why we can't just improve the default cropper. It seems like a lot of bloat for something that would result in not that many plugins. What potential is there really to innovate with cropper plugins?

**Comment by albinekb** [comment]
Yeah maybe, I'm working on a module that will emit events on window-focus, with the `width, height, x, y` for that window, which could be used in kap:

1. select "target window mode"
1. start checking windows
1. move the cropper window automatically to the focused window (do not receive click events)
1. have a button to say "ok" shown somewhere

But yeah, this should probably be in the core as there won't be many (if any) other needed ways to crop areas

**Comment by sindresorhus** [comment]
A "target window mode" would be super useful. I often have the need to only record a specific window. But I think that too is something that should just be in core.

**Comment by albinekb** [comment]
Agreed, there's only so much you can do with the crop rectangle 😄  Closing this.
