### ISSUE TITLE
Link in authors section of package.json has invalid cert in Chrome

### ISSUE THREAD

**Issue by NoNameProvided** [wulkano/kap#200]
### Steps to reproduce

1. Open https://wulka.no in Chrome.

### Current behaviour

Opening the url from the author section in `package.json` displays a SSL warning page in Chrome. Safari and Firefox works fine (Haven't tried in Edge.) 

The displayed error message: 

> This server could not prove that it is wulka.no; its security certificate is from wulkano.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

### Expected behaviour

The `package.json` author section contains the _https://wulkano.com_ url or _http://wulka.no_ has a valid certificate.

**Comment by skllcrn** [comment]
Uh-oh! I can't reproduce this, any ideas @CodeTheory?

**Comment by NoNameProvided** [comment]
Ok, so I just tried again and it works for me now too. Maybe Safe Browsing got crazy for a sec, or I have no idea.

**Comment by skllcrn** [comment]
That's good news!
