### ISSUE TITLE
Swap 'Yes' and 'No' on the discard recording popup

### ISSUE THREAD

**Issue by moskyb** [wulkano/kap#202]
**Platform:** `Darwin Bens-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64`
**Kap Version:** `1.0.0`
### Steps to reproduce
Discard any kapture
### Current behaviour
'Yes' is on the left, and 'No' is highlighted and on the right
### Expected behaviour
'No' is on the left, and 'Yes' is highlighted and on the right

<img width="790" alt="screen shot 2017-06-02 at 2 30 26 pm" src="https://cloud.githubusercontent.com/assets/15753101/26708951/3f1d54da-47a3-11e7-8796-a999b93cf6f2.png">

This confuses me every single time, and it's really annoying.

**Comment by sindresorhus** [comment]
Agreed. It should be:

```
[Cancel]  [Discard]
```

`Cancel` should be the highlighted button.
