### ISSUE TITLE
Option to open folder after save

### ISSUE THREAD

**Issue by xenio** [wulkano/kap#204]
I will love to see a setting for open the destination folder after save.

**Comment by CodeTheory** [comment]
Thanks for the issue @xenio.

@sindresorhus @skllcrn Perhaps we could send a desktop notification after save that, when clicked, opens the destination?

**Comment by sindresorhus** [comment]
Yeah, that could be useful. Could use the `click` event on the notification: https://github.com/electron/electron/blob/master/docs/api/notification.md#event-click

**Comment by BrandonKlotz** [comment]
I am looking for a first PR on a project that is not my own. Do you have any guidance on where to start and could I take this issue?

**Comment by albinekb** [comment]
@BrandonKlotz nice, yes. I'd start by cloning and running master, then read about the plugin arcitechture [here](https://github.com/wulkano/kap/blob/master/docs/plugins.md), and when you get that, we have the "default save to file" service code here: https://github.com/wulkano/kap/blob/master/app/src/main/save-file-service.js in which this one should be implemented. 

As the issue title says to add an option to do this, you will need need to read about how to enable config to a plugin here: https://github.com/wulkano/kap/blob/master/docs/plugins.md#config

Hope that points you in the right direction 👍 Feel free to ask more if I missed something.
