### ISSUE TITLE
What about hotkeys?

### ISSUE THREAD

**Issue by danillewin** [wulkano/kap#206]
Hi, could you add customizable hotkeys for start/stop capturing?

P.S. thank you for awesome app)

**Comment by CodeTheory** [comment]
Hey, thanks for the issue!
We have an issue going for custom keyboard shortcuts at #150 so this is a duplicate. You can current start Kap with a shortcut that is <kbd>CMD</kbd><kbd>shift</kbd><kbd>5</kbd>.
