### ISSUE TITLE
Downloading DMG from now.sh is painfully slow or fails

### ISSUE THREAD

**Issue by rturk** [wulkano/kap#207]
**Platform:**
NA
**Kap Version:**

### Steps to reproduce
Donwload the .dmg file
### Current behaviour
Slow, connection often resets
### Expected behaviour
Simple fast, easy to download

Downloading the .dmg file from now.sh is extremely slow and ofthen the connection reset causing download to fail.

Can we move this to, for example, S3 bucket?

**Comment by sindresorhus** [comment]
From clicking the link to the download starting takes a minute for me, but when it first starts it downloaded in seconds on my fast connection.

**Comment by rturk** [comment]
@sindresorhus any reason for not using S3 or github?

**Comment by skllcrn** [comment]
Dealing @rauchg and @matheuss in as it might be something they want to look into. For me now.sh is super snappy and reliable, but I'm open to adding in a direct link to download from GitHub as an additional alternative.

**Comment by sindresorhus** [comment]
I'm not entirely familiar with how it works, but I think the now.sh URL is just redirecting to the CircleCI-hosted artifacts: https://circleci.com/docs/1.0/build-artifacts/

**Comment by mattaningram** [comment]
I am incapable of downloading Kap via the download link. Every time I try it gets a few KB in and then fails. Definitely needs to be fixed.

**Comment by CodeTheory** [comment]
The issues is down to `nuts`. I'll redirect the download location directly to github tomorrow morning.

**Comment by whmountains** [comment]
This is why static hosting is so important.  Just saying...

**Comment by matheuss** [comment]
@whmountains and expensive 😄 Bandwidth is not free at all

**Comment by matheuss** [comment]
@whmountains just fixed it temporarily by using the direct GitHub Releases link 👌 

To be honest, we may keep this solution – we don't need to go through the updates server for `/download` 👌
