### ISSUE TITLE
Don't open on system startup

### ISSUE THREAD

**Issue by leo** [wulkano/kap#208]
The app should open, but not the main window 😊

**Comment by doot0** [comment]
Sounds good, but I'd want to have an option to turn the behaviour on or off.

**Comment by CodeTheory** [comment]
@doot0 So Kap shows the main window upon startup? Can't the user just click the icon in the start bar to show Kap when they want instead of it showing every time?

**Comment by doot0** [comment]
@codetheory We could, but it saves you a click otherwise. 🙊

**Comment by skllcrn** [comment]
Oops! Not the intended behaviour. I don't see how an option to enable showing the Kap window on startup would have enough value to build it out, personally I think it's annoying.

**Comment by albinekb** [comment]
Does anyone know how to check if Kap was started by "start on boot" or by the user? Is there some magic we can do with electron? 🤔

**Comment by leo** [comment]
@albinekb https://github.com/zeit/now-desktop/blob/325b8291a7100f7e674fc5e89512a57b80478b87/main/index.js#L247

**Comment by albinekb** [comment]
Awesome, exactly what I was looking for! Thanks a lot @leo ❤️
