### ISSUE TITLE
App won't work after opening + menubar window becomes draggable

### ISSUE THREAD

**Issue by conarro** [wulkano/kap#210]
**Platform:**
Mac OS Sierra 10.12.4 (Macbook Pro Retina 2015)
Darwin Kernel Version 16.5.0

**Kap Version:**
v1.0.1.1

### Steps to reproduce
* download DMG from Kap website (on platform described above)
* install app
* open app
* the menubar app window opens automatically
* try clicking the buttons, nothing works
* app window is draggable, which seems odd (not sure if intended but would assume not)

### Current behaviour
* no button clicks work within the app window. clicking menubar icon _does_ work, however (to show/hide the app window)

### Expected behaviour
* buttons should work when clicked

### Workaround
* not really a workaround since I can't get anything to click
* since no buttons work (including settings), I have to manually kill the Kap process to close the app

### GIF of this bug in action
![kap bug](https://user-images.githubusercontent.com/1232682/28344857-5fa73746-6bf4-11e7-983a-e757500fb1f5.gif)

**Comment by skllcrn** [comment]
Not fun! @sindresorhus resolved a similar issue (#159) a while back.

**Comment by conarro** [comment]
@skllcrn ah thanks for the reference (poked around the issues but didn't see it before) -- just installed from `master` and I'm up and running!
