### ISSUE TITLE
Option to record a window

### ISSUE THREAD

**Issue by kjvdven** [wulkano/kap#212]
When taking screenshots on a mac, you can take a screenshot of a singular window. It would be awesome to have this option in Kap, so you can make a screen recording of a window.

https://support.apple.com/en-us/HT201361

I know you can drag the area you want, but this is just a little bit nicer.

**Comment by sindresorhus** [comment]
That would be very useful indeed.

How would you like to see it work? Interactively pick a window like the system screenshot capture or just a list of window names in a dropdown?

Related issue: https://github.com/wulkano/aperture/issues/16

**Comment by styfle** [comment]
I've been working on a [project](https://github.com/styfle/magnemite) to record a single web browser that might solve your problem. However, the use case is more for capturing repro-steps so it might not meet your needs.

**Comment by ajunior** [comment]
It would be great, because is more practical just click on or choose a specific windows to record.
BTW the app is awesome!!

**Comment by chriscalo** [comment]
@sindresorhus, [Screenflick](https://www.araelium.com/screenflick) does this somewhat well: when you go into capture mode, it immediately shows a rectangle on the screen representing the area it will record. You have several options for interactions at this point:

1. Resize the rectangle using any of its drag handles
2. Click and drag inside the rectangle to reposition it
3. Click and drag anywhere outside the rectangle to define a new rectangle
4. Type specific numbers into a Screenflick window to update the rectangle dimensions
5. Hover over any visible window on screen and it shows a faint rectangle over that window, indicating that if you single-click that window, it will update the recording rectangle to the same dimensions and position as that window
6. Click the record button to start recording

Interaction 5 is by far the most common interaction I use when doing screen recordings. Most of the time people just want to record a window, so having to drag out a rectangle feels unnecessarily onerous in those situations. I recommend doing something like this where you need only click on the window you want to record.

**Comment by sindresorhus** [comment]
@chriscalo Agreed. I do think it can be improved further though. I have Screenflick and I never noticed the window picker as I almost always have a fullscreen window open, which makes the picker not very noticeable. I think it could help to have a list of windows too.

**Comment by dentarg** [comment]
Done?

**Comment by sallar** [comment]
@dentarg Yes! The latest beta has this feature :)
