### ISSUE TITLE
Make quality configurable (Output video compression)

### ISSUE THREAD

**Issue by luksak** [wulkano/kap#215]
**Platform:** Darwin Lukass-MacBook-Pro-3.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64
**Kap Version:** 1.0.1.170
### Current behaviour
The video and audio quality is not configurable.
### Expected behaviour
Provide options for bit rate for video an audio in the preferences
### Workaround

**Comment by CodeTheory** [comment]
Kap currently outputs an uncompressed video. We'll look into compressing video output optionally.

**Comment by luksak** [comment]
ok, great!

**Comment by skllcrn** [comment]
Closing in favour of #117
