### ISSUE TITLE
Persist settings across relaunch: Aspect ratio options and Export format

### ISSUE THREAD

**Issue by jsejcksn** [wulkano/kap#219]
**Platform:** macOS 10.12.6
**Kap Version:** 1.0.1.170
### Steps to reproduce
1. Open Kap.app
2. Expand Controls
3. Set Aspect ratio options and Export format
4. Quit Kap
5. Open Kap again

### Current behaviour
Settings are lost

### Expected behaviour
Settings persist

**Comment by jsejcksn** [comment]
@sindresorhus If you want, I can help with UX testing for Kap in general. I have some other suggestions if you'd like to hear them.

**Comment by sindresorhus** [comment]
@jsejcksn Definitely. Try out the latest master version: https://kap-artifacts.now.sh/master And let us know :)

**Comment by CodeTheory** [comment]
For what it's worth, the latest `master` build has somewhat broken aspect ratio selection. I'll be fixing this along with #226 😄

**Comment by jsejcksn** [comment]
@sindresorhus Wilco.

@CodeTheory Ah, great! Some of my suggestions are mirrored in your linked comment about aspect ratio behavior. Also, that's the version I've been using, but I downloaded it from the repo [release page](https://github.com/wulkano/kap/releases/tag/v1.0.1).
