### ISSUE TITLE
Include codec option in settings

### ISSUE THREAD

**Issue by jsejcksn** [wulkano/kap#220]
See wulkano/aperture#45

**Comment by sindresorhus** [comment]
Agreed. It should default to HEVC on High Sierra and up and H264 on the rest.

This is blocked by the linked Aperture issue.

**Comment by sindresorhus** [comment]
We've chosen not to add a codec option for simplicity. In the future, we'll move to HEVC when it becomes more mainstream and supported by Electron (and Chrome).

**Comment by skllcrn** [comment]
Revisiting this we've decided not to make it an *option*, but rather switch to HEVC once it's supported upstream. Our goal with Kap is not to make it an advanced recording and editing solution, but rather the quickest and easiest way to share what's happening on your screen.
