### ISSUE TITLE
Rewrite in React/Next.js

### ISSUE THREAD

**Issue by timothyis** [wulkano/kap#223]
It would be much easier to maintain. Much easier for other to contribute.

https://leo.im/2017/electron-next

cc @leo ❤️

**Comment by leo** [comment]
It's pretty easy. Check this out: https://github.com/leo/electron-next-skeleton

**Comment by CodeTheory** [comment]
Yes! Super excited to get it done 🎉

**Comment by skllcrn** [comment]
Moving #53 out of the current milestone/project, should be done in conjunction with the rewrite.

**Comment by steveharman** [comment]
Just a note relating to #338 while it was in my head.  I get this a lot, trying to draw / position my marquee right where the KAP window is.  In 1.x I could just drag the window aside but not with 2.x.  

Seems a shame to have removed such a handy feature.

Thanks,

![kap_marquee](https://user-images.githubusercontent.com/12557929/36668776-4387e5a6-1aea-11e8-98ef-5a86ee102b52.png)

**Comment by kevva** [comment]
Do we still want to keep the styles as separate CSS files or do we want to use [`styled-jsx`](https://github.com/zeit/styled-jsx)?

**Comment by timothyis** [comment]
Since next.js comes equipped with styled-jsx and that I'm personally a fan of it, I'd vote for using styled-jsx!

**Comment by skllcrn** [comment]
https://github.com/wulkano/kap/pull/450

**Comment by skllcrn** [comment]
#494
