### ISSUE TITLE
Open Kap's editor with an external video file

### ISSUE THREAD

**Issue by timothyis** [wulkano/kap#224]
Would be amazing if you could drag-and-drop a video file onto the Kap icon in the menubar and then proceed to use Kap's editor with that video file. This way you can convert pre-existing mp4 files to gif/webm/etc. without needing to record. You could also upload the file using Kap plugins making them much more useful.

Once the trimmer (#216) is in, this would be very helpful to pre-existing video files too.

**Comment by skllcrn** [comment]
I need this in my life.

**Comment by sindresorhus** [comment]
We should also register Kap in the "Open With" context menu.

This can be done with the [`extendInfo`](https://www.electron.build/configuration/mac) Electron Builder config. https://stackoverflow.com/a/19148579/64949

**Comment by skllcrn** [comment]
This feature is available in Kap 3.0!
