### ISSUE TITLE
Rework aspect ratio selection

### ISSUE THREAD

**Issue by CodeTheory** [wulkano/kap#226]
Aspect ratio selection shouldn't take priority of the width and height inputs. 
Currently if you select an aspect ratio, it will overwrite the width and height with a preset pixel value. 1600x900 for 16:9 for example. It will continue to help the width and height remain at a 16:9 ratio afterwards but it shouldn't have a preset value to begin with.

How I'd like to rework aspect ratios:
- Kap would open fresh with a 512x512 width and height (1:1 ratio but listed as custom)
- Changing the width or height wouldn't lock to the 1:1 ratio
- Selecting an aspect ratio would change the opposite value to the users active input to match the selected aspect ratio. For example, I've written `1280` as my width, I select `16:9` in the ratio selector and the height would change to `720`. Not overwriting the users width/height values to start with.
- As long as a ratio is selected in the ratio selector, the inputs will lock to that and the height/width values won't deviate from each other based on the ratio. 
- Selecting `Custom` ratio again will allow the user to type any value into both inputs without them locking to each other (however we should display what the ratio is for the user anyway, e.g. `Custom 512:200`)

Image example:
I've typed a custom width and height whilst selecting `Custom ratio` in the ratio selector. This shows me the ratio that the width/height pertain to. I can then lock this ratio for my width and height to change with.
![image](https://user-images.githubusercontent.com/1695613/30031282-a953b7fc-9188-11e7-9c5c-237cc693c934.png)
_note: ignore stream stuff. Just an experiment in design that I can't be bothered to remove_

Would love to hear thoughts to expand on this.

**Comment by skllcrn** [comment]
Could it be an idea to tackle #137 while working on this issue?
