### ISSUE TITLE
Double tapping record button throws error

### ISSUE THREAD

**Issue by OmgImAlexis** [wulkano/kap#229]
**Platform:** Darwin Bella.tardis 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
**Kap Version:** Version 1.0.1 (1.0.1.170)
### Steps to reproduce
Double tap record button
### Current behaviour
Throws error
### Expected behaviour
Recording to be cancelled before it starts
### Workaround
N/A

![screen shot 2017-09-12 at 9 35 23 pm](https://user-images.githubusercontent.com/6525926/30325132-b229d462-9802-11e7-9a16-6aa302fa849c.png)

**Comment by CodeTheory** [comment]
Thanks, I forgot to fix this!

**Comment by albinekb** [comment]
Fixed in #239 🎉
