### ISSUE TITLE
Support for AWS S3 / Cloud share link with short link!

### ISSUE THREAD

**Issue by irazasyed** [wulkano/kap#23]
Hey there!

Coming from Product Hunt. Upvoted too 👍 

Looks like a great app and the roadmap looks good too, looking forward to seeing those features implemented in this app.

I just tried the app on macOS Sierra and it didn't work as it froze and I ended up quitting. I'll give it a try again when a newer version is released.

So my feature request as already mentioned on PH is that, to add support for platforms like AWS S3 / Backblaze / Google Cloud Storage and other file storage providers with ofc custom server support apart from the already mentioned platforms like Dropbox/Google Drive. This would completely replace my current screenshot app that I use which stores the files on their servers.

Another thing is shortlink support like connected with Bit.ly API (With custom domain) maybe or just our domain that we can point it to AWS S3 or other storage providers.

Hopefully, you can consider these feature requests for your future builds.

Thanks!

**Comment by matheuss** [comment]
Thank you for the feedback, @irazasyed! 
We just released [`v0.2.0`](https://github.com/wulkano/kap/releases/tag/v0.2.0) 😄 

We'll definitely consider – it's planned! We'll let you know when have some progress 😄

**Comment by irazasyed** [comment]
No problem and sounds good about the progress updates. I'd be happy to do Beta testing when it's implemented :)

Thanks!

P.S. Checking the new ver.

**Comment by leahprin** [comment]
Simple S/FTP support would be great too.

**Comment by skllcrn** [comment]
@SamVerschueren has created a plugin for this, see https://github.com/SamVerschueren/kap-s3. Support for plugins is on master if you'd like to test it, keeping the issue open for now to avoid duplicates!

**Comment by skllcrn** [comment]
This is now available in the 2.0 Beta!
