### ISSUE TITLE
UX enhancement: ability to go back/exit preferences without exiting the window

### ISSUE THREAD

**Issue by aalokt89** [wulkano/kap#232]
- As a user, I want to be able to save my preferences and be taken back to the original recording screen.
- Right now, once I am done with my prefs, there is no way to 'save' or go back to the main recording interface. I have to close the window, which essentially closes the app. Then I have to go back and open the application again.
- This is very annoying because it makes me believe that my prefs didn't save and I have to open the application again.
- Solution: have a 'done' button in the prefs screen that takes you back to the recording interface

**Comment by CodeTheory** [comment]
Hi there @aalokt89. Thanks for another report.

We don't want to add an extra step to saving your preferences, but could your issue be summed up to the fact that there's no feedback to tell you when your preferences have been acknowledged/saved?

**Comment by sindresorhus** [comment]
He doesn't want the Kap popover window to be closed when the preferences window is open. I don't totally agree with that though as popovers are usually transient.

> This is very annoying because it makes me believe that my prefs didn't save and I have to open the application again.
> have a 'done' button in the prefs screen that takes you back to the recording interface

This is how all macOS itself and macOS apps does preferences. There's never a message. Your preferences are just saved right away. We're not going to change this as it would be against the macOS Human Interface Guidelines and would be surprising behavior for Mac users.

Instead, I think we should reopen the main Kap window when the preferences window is closed.

**Comment by aalokt89** [comment]
No, I get the auto saving aspect. @sindresorhus yes, that's more of what I meant. Because the recording interface goes away and essentially turns into the prefs interface, it feels like one entity. When you quit prefs, it feels like you're quitting the whole app. Keeping the recording interface open behind the prefs modal would be the ideal solution, like what most apps do.

**Comment by sindresorhus** [comment]
> like what most apps do.

What apps are those? Because I've never seen that behavior in popover menubar apps. For example, the Dropbox app also closes its popover when the preferences window is opened.

**Comment by aalokt89** [comment]
@sindresorhus 
Sketch: https://screencast.com/t/b7QnArmdM9
Illustrator: https://screencast.com/t/IAKt7niSQ6w

I don't know if it being a menu bar app is the cause of this. It's really not a huge deal; just an inconvenience because you generally want to take an action immediately after changing a pref for this app in particular.

**Comment by sindresorhus** [comment]
@aalokt89 Those are not menu bar apps. Menu bar apps and especially popovers have different behavior.

**Comment by skllcrn** [comment]
As @sindresorhus has outlined this is because Kap is a menubar app. However you can detach Kap from the menubar by dragging it off to keep the main Kap window open, including keeping it open while editing your preferences.
