### ISSUE TITLE
Default share service

### ISSUE THREAD

**Issue by albinekb** [wulkano/kap#238]
Many people would like to set a default export service for each format. That way you could "streamline" the pipeline from a recorded kapture to shared *insert format* file. 

For example: I use https://github.com/albinekb/kap-draggable to drag-n-drop my gifs onto github PRs, if I had a way to select this drag-n-drop as the default share service for GIFs, I could save having to do the tedious task to select the same share setting every time.

Here's my initial version of this, however, we'd like to improve on this idea and make it even better when we implement it: https://github.com/wulkano/kap/pull/198

**Comment by steveharman** [comment]
Setting defaults and "just getting on with it (tm)" when saving / exporting a recording would get a vote from me.  I do understand the concept of the preview but, well, in reality I just sat there and did my recording so I'm pretty sure I remember what it looks like even without a preview playback.  ;-)

No big thing - I'd just rather set my default exporting options in Preferences or somewhere, which 99% of the time will never change anyway, then just save my recording once I'm done without seeing lots of options and a video preview.

**Comment by albinekb** [comment]
@steveharman (or anyone else that wants to) a PR that adds this functionality is welcome 🙂 It won't make the 2.0 release but we will be able to get it out in a minor patch during 2.x 🙌 #198 could be used as a base, if you want to discuss things/need more help just HMU! 🏆

**Comment by skllcrn** [comment]
I suggest we do a simple implementation of this in 3.0 by remembering the last used export method. Note that if you use `Save to disk...` it should still default to the directory set in Preferences, not the last used directory.
