### ISSUE TITLE
Gif support 

### ISSUE THREAD

**Issue by sirgalleto** [wulkano/kap#24]
Can you export gif like recordit app?

**Comment by doot0** [comment]
Hey, closing this as it's a dupe of https://github.com/wulkano/kap/issues/14.

It's in the works and should be landing soon! Thanks for your patience. 👌

**Comment by sirgalleto** [comment]
@doot0 thanks and congrats, this app looks very nice

**Comment by doot0** [comment]
@sirgalleto Thanks boss! 🖖

**Comment by matheuss** [comment]
Ops, closed by accident 😩
