### ISSUE TITLE
Discard Kapture improvements

### ISSUE THREAD

**Issue by albinekb** [wulkano/kap#246]
When closing the editor window, you get this prompt:
![image](https://user-images.githubusercontent.com/5027156/32013680-24562d08-b9bc-11e7-967f-291a7ca1ad8a.png)

Which is good, but when using Kap a lot, it feels like an unnecessary step.

I can think of some ways to improve this:
- Only ask the user if nothing was exported (will not help in all cases)
- Have a button visible somewhere in the UI that says `discard` and when pressed, discards the recording & closes the editor without further questions
- Have a secret key (like cmd) that if you hold it and press the X it will not ask (bad UX)

This would make it easy to quickly discard a kapture, for example if you messed up and want to do a re-take, or when you're done exporting

Personally I like the idea to have a button to discard directly.

Thoughts?

**Comment by CodeTheory** [comment]
@skllcrn, @onordbo, and I spoke about this recently. We want an easier way to do it too. 

@onordbo had some ideas, if I remember correctly.

**Comment by sindresorhus** [comment]
> Have a button visible somewhere in the UI that says discard and when pressed, discards the recording & closes the editor without further questions

👍

**Comment by sindresorhus** [comment]
Maybe something like this (ignore the design):

<img width="880" alt="screen shot 2017-10-27 at 14 49 26" src="https://user-images.githubusercontent.com/170270/32093337-1636a1d8-bb26-11e7-9d99-67f6a66f8481.png">

**Comment by onordbo** [comment]
@sindresorhus Yes, this looks great — just pinned to the far-right corner with some extra (16px?) left padding.

**Comment by albinekb** [comment]
Looks awesome @sindresorhus 👌  This will save some time and not as annoying! 😄
