### ISSUE TITLE
Mouse & highlight ring can't be turned off in recording

### ISSUE THREAD

**Issue by ianpaschal** [wulkano/kap#247]
**Platform:** ians-mbp.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Kap Version:** 1.0.1 (1.0.1.170)

### Steps to reproduce
Now sure how to reproduce. Bug is an issue of not being able to reset in the first place.

### Current behaviour
Clicking the mouse icon in the main recording window, as well as turning off "Show mouse cursor" in preferences have no effect. Mouse cursor still appears in capture with black ring around it.

### Expected behaviour
I shouldn't see the mouse cursor or the black highlight ring after turning this feature off.

**Comment by skllcrn** [comment]
Thanks for the issue! It's a known bug and there's already an open issue for it, you can follow the progress on #231
