### ISSUE TITLE
Exported video file dimensions don’t match Kap settings

### ISSUE THREAD

**Issue by stursby** [wulkano/kap#25]
It looks like the actual video file that Kap saves has slightly smaller dimensions from the settings.

For example, I set mine to 1280x720, and here's the `Get Info` panel for that file.

![screen shot 2016-10-06 at 1 23 13 pm](https://cloud.githubusercontent.com/assets/527849/19165151/5b0abdc8-8bc8-11e6-89ea-f43ffa3780a4.png)

The dimensions are *1276x716* (4px smaller in each direction).

**Comment by matheuss** [comment]
Thanks fo the report, @stursby! I had that I mind but completely forgot about it. We'll make sure to include it in the next patch! 😄

**Comment by CodeTheory** [comment]
@stursby On a side note, could I ask how the size of the window got that small? If it's a bug, I need to fix it.

**Comment by stursby** [comment]
@CodeTheory which window are you referring to?

**Comment by CodeTheory** [comment]
@stursby The Kap window in your screenshot looks off. 

Here's yours:
![image](https://cloud.githubusercontent.com/assets/1695613/19165848/b3114874-8c05-11e6-93f7-f62956b9bb4a.png)

Versus mine: 
![image](https://cloud.githubusercontent.com/assets/1695613/19165874/d113a272-8c05-11e6-8b16-95fb8b9d92b2.png)

**Comment by stursby** [comment]
It looks like the window is changing widths after toggling the Controls panel. Here's three states:

1. Open Kap (320px)
2. Toggle Controls (~290px)
3. Detach window & Toggle Controls (~260px)

![kap-window-size](https://cloud.githubusercontent.com/assets/527849/19166219/58006fde-8bcc-11e6-9835-6b14802444fb.gif)

Hope this helps!

**Comment by matheuss** [comment]
Whoa @stursby, that's really strange. Could you open an issue for it so we can discuss? 😄

**Comment by stursby** [comment]
Done. https://github.com/wulkano/kap/issues/26
