### ISSUE TITLE
Error when Preferences window is closed/blurred during a plugin install

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#257]
Install a plugin, then close the Preferences window, and when the plugin finishes installing, an error is thrown.

<img width="532" alt="screen shot 2017-10-30 at 20 49 31" src="https://user-images.githubusercontent.com/170270/32174275-013cb71e-bdb4-11e7-8a3d-106dea23ba09.png">

**Comment by kevva** [comment]
So it's failing here https://github.com/electron/electron/blob/master/lib/browser/rpc-server.js#L150-L151. Too bad there's nothing point us to where.

**Comment by sindresorhus** [comment]
It's either this https://github.com/wulkano/kap/blob/49bc64cb3bba1c6089b240d9c227b5234a8b168c/app/src/main/index.js#L419 or this https://github.com/wulkano/kap/blob/49bc64cb3bba1c6089b240d9c227b5234a8b168c/app/src/main/index.js#L424, as they're the only ones with a `.sender` property.

**Comment by kevva** [comment]
I tried removing them but got the error anyway. It could be https://github.com/electron/electron/blob/master/lib/browser/rpc-server.js#L153 too which is why we don't get the correct error.

**Comment by kevva** [comment]
Works if we install/uninstall the plugins from the main process instead of directly calling the plugin API via `remote.require`. I'm working on an implementation.
