### ISSUE TITLE
Use `electron-updater`

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#258]
Right now we're using the built-in updater in Electron with a custom server. The built-in updater in Electron requires a server and a lot of boilerplate code in Kap.

I suggest we switch to [`electron-updater`](https://www.npmjs.com/package/electron-updater). It's part of `electron-builder` and will let us just build on Travis or CircleCI and publish to GitHub. No need for us to maintain a server. It just works. It also now supports delta updates for smaller updates, [staged rollouts](https://www.electron.build/auto-update#staged-rollouts), prerelease support, etc.

I've been using it with great success on Caprine for a long time.

This is not high priority. Just opening this since I got the idea now.

Thoughts?

**Comment by skllcrn** [comment]
Note that we would lose the static URL for the latest release (https://kap-beta-updates.now.sh/), so we would need to work around that if we decide to go ahead with this. Would appreciate your thoughts @matheuss.

**Comment by skllcrn** [comment]
[Easier AutoUpdating for Open-Source Apps](https://electronjs.org/blog/autoupdating-electron-apps)

**Comment by sindresorhus** [comment]
@skllcrn I looked at it. Was not impressed. Seemed very immature and not that thought through. Could be good in the future, but for now, I would go with `electron-updater`.
