### ISSUE TITLE
Window changing widths

### ISSUE THREAD

**Issue by stursby** [wulkano/kap#26]
It looks like the window is changing widths after toggling the Controls panel. You'll notice the scrollbar show up, then quickly disappear. Here's three states:

1. Open Kap (320px)
2. Toggle Controls (~290px)
3. Detach window & Toggle Controls (~260px)

![kap-window-size](https://cloud.githubusercontent.com/assets/527849/19166219/58006fde-8bcc-11e6-9835-6b14802444fb.gif)

Hope this helps!

**Comment by matheuss** [comment]
Thanks for the report 💪 

When the `Controls` is clicked, [a message is sent](https://github.com/wulkano/kap/blob/master/app/src/renderer/js/index.js#L14) from Electron's renderer process to the main one with the current width and height of the window, so Electron can [tell macOS to resize it](https://github.com/wulkano/kap/blob/master/app/src/main/main.js#L45).

To be honest, I have no clue on how the width is changing 😮 I'll push a branch with a possible fix and would be grateful if you could test it 😄 

Also: could you share some details about your env? macOS version, window resolution/scaling... 🕵️

**Comment by stursby** [comment]
I would be happy to test for you. I'm running macOS Sierra 10.12 on a Mid 2015 15.4" MackBook Pro (Retina) and a 27-inch Apple Thunderbolt Display.

The GIF from above was recorded on the Thunderbolt, however, I just tried from the Retina MBP screen and had the same results.

LMK if you need more details.

**Comment by matheuss** [comment]
There we go @stursby https://github.com/wulkano/kap/tree/fix/window-resize-glitch 😄 Could you see if it's a fix?

**Comment by stursby** [comment]
LGTM! Window confirmed staying 320px wide. On another note, is there a way to not display the scrollbar? See my GIF below, you'll notice a small hiccup when expanding `Controls`. Or is there no way to remove that since it's basically just a browser window with overflow as it's animating down?

![kap-scrollbar](https://cloud.githubusercontent.com/assets/527849/19169713/3c5706ee-8bdb-11e6-9920-687f73c3089b.gif)

**Comment by matheuss** [comment]
YAY! Since I can't reproduce, could you try adding `overflow: hidden` to the `<body>` element? 😄

**Comment by stursby** [comment]
Yep, that worked too! 💯 

![kap-scrollbar-fix](https://cloud.githubusercontent.com/assets/527849/19170041/74ba4392-8bdc-11e6-8372-6ecb4ca42f3e.gif)

**Comment by matheuss** [comment]
Yay @stursby ✨ Could you just test it one more time? Also, you're getting a strange behavior with the `Controls` `background-color` 😕 We (@skllcrn) tried to reproduce but no luck.

**Comment by stursby** [comment]
I think that was just a glitch between DevTools selection and LICEcap. In reality, the background color of `Controls` doesn't actually change.

Closed
![image](https://cloud.githubusercontent.com/assets/527849/19171615/530c955e-8be3-11e6-98a2-ca8c4e53e8ee.png)

Open
![image](https://cloud.githubusercontent.com/assets/527849/19171621/5bde42f4-8be3-11e6-9fcc-21f3d31755a7.png)

**Comment by matheuss** [comment]
Amazing :sparkles: I'll merge it into master when I'm back at my computer — it'll be on tomorrow's release :smile:
