### ISSUE TITLE
Missing rounded corners in the Editor

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#264]
The Editor is being square and doesn't really get with my circle. 

On a serious note though, the top left and right corners of the Editor are missing some sweet rounded corners on the latest master.

**Comment by kevva** [comment]
Looks like this for me. Isn't this correct?

![screen shot 2017-10-30 at 20 41 45](https://user-images.githubusercontent.com/709159/32191879-d2012f94-bdb2-11e7-9215-e18fc47873d9.png)

**Comment by sindresorhus** [comment]
@kevva The top corners are not round for me. Are you on 10.12 or 10.13?

**Comment by kevva** [comment]
10.12 still.

**Comment by albinekb** [comment]
Interesting 🤔
