### ISSUE TITLE
Why there is no Windows version of KAP ?

### ISSUE THREAD

**Issue by pushqrdx** [wulkano/kap#270]
As far as i know electron allows for easy cross platforming, so why there is no version of this app for windows ? are there any native calls or something like that ?

**Comment by albinekb** [comment]
See https://github.com/wulkano/kap/issues/20
We use wulkano/aperture for the actual recording (native), and it is macOS only atm. The problem is that we have not found anyone that's up to the work that having windows support will bring. All of the current maintainers are macOS only, hence why we can't handle supporting windows. 

We would need to find a windows maintainer for both Kap and Aperture to be able to support windows.

See https://github.com/wulkano/aperture/issues/46 for more info about the aperture issue.

**Comment by thedonquixotic** [comment]
I wish I was a good enough dev to help with this.

**Comment by skllcrn** [comment]
Maybe you are @thedonquixotic, for the time being we're focusing exclusively on the macOS version, but why not create a fork and experiment with it?

**Comment by thedonquixotic** [comment]
I'm literally a UX Designer who knows enough code to annoy real devs on github
and thats about it :/ But I'm getting there someday!

If nothing else, know that I think this project is very dope and it looks
beautiful.  








On Thu, Mar 22, 2018 5:25 PM, Christopher notifications@github.com  wrote:
Maybe you are @thedonquixotic, for the time being we're focusing exclusively on
the macOS version, but why not create a fork and experiment with it?

**Comment by Mancerrss** [comment]
I'm not a dev or technical person, I'm just a designer but I've red about this recently. This might help to you guys. 

https://mspoweruser.com/windows-10-scu-includes-new-screen-capture-api/

This will ship on upcoming Windows 10 April 2018 Update. I don't know if there's a way to utilize this even if you're not a UWP app, I've heard and discuss it too on Twitter and says it's possible, Win32 screen recorder apps could utilize it. Check out the article and their documentation

**Comment by lacymorrow** [comment]
The answer may be: https://github.com/NodeRT/NodeRT

I'm looking into using it now.

**Comment by TheGrimSilence** [comment]
Hey guys, I just found Kap but I'm a steadfast Windows only developer. For anyone that reads this post-close-issue I'll take a look and see what I can do about a Windows solution since Kap seems to be a really nice tool.

**Comment by nathanloisel** [comment]
Electron gives function to create a stream from the desktop: [desktopCapturer](https://github.com/electron/electron/blob/v8.2.4/docs/api/desktop-capturer.md)
There is a limitation with macOS, capturing system audio doesn't work but there are alternatives to overcome this problem.
