### ISSUE TITLE
Document how to do new releases

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#274]
We should document this in a `maintaining.md` file in the repo root.

Example: https://github.com/avajs/ava/blob/master/maintaining.md

**Comment by matheuss** [comment]
As far as I remember (the last time I did this was 9 months ago 😅), here's how I'd do it:

1. Bump `version` [here](https://github.com/wulkano/kap/blob/master/app/package.json#L4)
2. `git commit -am '<the new version you just bumped>'`
3. `git tag <same version here>`
4. `git push && git push --tags`
5. Wait for CI to build it the commit and the tag
6. When building the tag, `electron-builder` should take care of uploading the relevant artifacts (`.app` and `.zip`) to a release titled `<version here>`. I'm not sure if you need to create the release beforehand or if it'll create it for you

The _trick_ there is that `electron-builder` will only (as far as I know) upload the artifacts if you push a new tag (it's configurable, but unless it was changed, we have it configured for `tagOnly` (or sth like that)).

**Comment by sindresorhus** [comment]
`electron-builder` didn't upload to the GitHub Release. I think I know why now. Seems CircleCI has deprecated the `deployment` key and we need to upgrade the CircleCI config file to v2: https://circleci.com/docs/2.0/configuration-reference/#tags

**Comment by matheuss** [comment]
@sindresorhus I'm afraid it only uploads it if you do `1.` 😥 It's CI agnostic as far as I can recall – it handles the upload logic itself 🤔

**Comment by sindresorhus** [comment]
@matheuss Yes, I'm saying that builds are not triggered on new tags, so it has no chance to upload.

**Comment by sindresorhus** [comment]
This was done in https://github.com/wulkano/kap/commit/2971d6dcae5679b7ce6825dc87bec47490e65620
