### ISSUE TITLE
Preferences for recording audio displaying "None" device

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#276]
If you have not overwritten the system settings for audio recording in Kap, the selector should display "Default".

**Comment by sallar** [comment]
@skllcrn This is tricky. Because we are setting the "first" device as the "selected" device, and the the device list doesn't include a "default" key so we can show that. So we either show the selected option or "None" which is the current behavior. How do we do the "Default" logic?

**Comment by skllcrn** [comment]
The default option is Kap *not* having a custom setting, in other words default is none, falling back to the system setting.

**Comment by sallar** [comment]
@skllcrn but does that work? So I need to remove the "force setting the device to the first available device" right?

**Comment by sindresorhus** [comment]
> in other words default is none, falling back to the system setting.

Saying the "default is none" is kinda confusing. I would say the default is "Auto", which is what happens if we don't have a preference for the audio.

**Comment by skllcrn** [comment]
Thanks @sindresorhus, that's a much better way of putting it. Chrome also displays "Default" when inheriting the system setting.

**Comment by sallar** [comment]
@sindresorhus @skllcrn so the options would say: "Default, Device 1, Device 2" etc right? And we remove the None option?

**Comment by skllcrn** [comment]
Correct, thank you!
