### ISSUE TITLE
Missing plugins pane

### ISSUE THREAD

**Issue by joshhopkins** [wulkano/kap#278]
Perhaps I'm just overlooking it?

**Platform:**

MacOS 10.13

**Kap Version:**

1.0.1.1

### Steps to reproduce

Look for where I'd expect the plugins pane to appear in preferences.

**Comment by skllcrn** [comment]
You can go to our [Product Hunt Upcoming](https://www.producthunt.com/upcoming/kap) listing and subscribe to receive a beta build with the new 3rd party plugin support later today!
