### ISSUE TITLE
Fix remaining issues with the aspect ratio widget

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#279]
~See comments in https://github.com/wulkano/kap/pull/251~
See https://github.com/wulkano/kap/pull/312#issuecomment-355913302

**Comment by sallar** [comment]
@sindresorhus @skllcrn I think these are the actual remaining issues:
https://github.com/wulkano/kap/pull/312#issuecomment-355913302
The description in this issue is old so i'll update it

**Comment by sindresorhus** [comment]
I've hid the custom ratio until we can manage to fix the ratio stuff: https://github.com/wulkano/kap/commit/e7a8d7c9db6ce6eb1f06f98ee0539f73f0925d95

**Comment by sallar** [comment]
Removing this from the milestone.
