### ISSUE TITLE
Settings button for plugins that provide it

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#286]
When doing the plugins pane, we forgot about adding a `Settings` button to plugins in the list that provide settings. This button should simply open the config file.

@skllcrn Any opinions on how it should look?

**Comment by skllcrn** [comment]
Work in progress! 

![configure-plugin](https://user-images.githubusercontent.com/8440026/39950785-3cfb3470-5584-11e8-90f8-deacd2a9ad4b.png)

**Comment by skllcrn** [comment]
Configuring plugins is part of #223
