### ISSUE TITLE
Exporting multiple files shows single progress bar

### ISSUE THREAD

**Issue by ericclemmons** [wulkano/kap#299]
**Platform:** macOs
**Kap Version:** Version 2.0.0-beta.3 (2.0.0-beta.3.449)

### Steps to reproduce

1. Make a recording.
2. Export to GIF.
3. While exporting. export to MP4.

### Current behaviour

1. Progress bar stays the same.

### Expected behaviour

1. Show two progress bars with the filename that's being output.

**Comment by skllcrn** [comment]
Related to #263

**Comment by ericclemmons** [comment]
Closed for #263.

**Comment by ericclemmons** [comment]
Shoot, just saw the labels.  Re-opened since it's triaged :)

**Comment by skllcrn** [comment]
For now we've discussed doing a simple fix where we show how many exports are in the queue: 

![image](https://user-images.githubusercontent.com/8440026/32989684-60e26616-cd1b-11e7-9eb4-494462ca5491.png)

The option to hide the window could alternatively be changed to starting a new recording, as mentioned in #263.

**Comment by skllcrn** [comment]
For now we're disabling multiple exports #340
