### ISSUE TITLE
Similar native app for Mac

### ISSUE THREAD

**Issue by vishaltelangre** [wulkano/kap#30]
This is great!

I had spent last weekend on https://github.com/vishaltelangre/Kyapchar. In upcoming weekends I am also thinking to build pause/resume, crop, system tray menu, etc. features in Kyapchar.

**Comment by doot0** [comment]
While Kyapchar looks cool, the Issues board isn't really meant for advertisements so I'm going to close this. Thanks! 🖖

**Comment by skllcrn** [comment]
Great work, thank you for sharing! We’ll allow this one, even if it’s not an issue. Among the reasons we built Kap was to explore using Electron, and to have a free and open source alternative to the current offerings.

**Comment by vishaltelangre** [comment]
Yes, my intention wasn't to advertise that work. 

On Mac, there are paid tools like ScreenFlow and ScreenFlick which costs a lot. QuickTime doesn't record computer audio. That made me to think about writing that one. Kap has already tried to solve most of such problems and I am glad to see it as trending.

**Comment by doot0** [comment]
@vishaltelangre My bad! 😅
