### ISSUE TITLE
Beta does not work on yosemite

### ISSUE THREAD

**Issue by aranajhonny** [wulkano/kap#301]
**Platform:** Mac OS X 10.10.5
**Kap Version:** v2.0.0-beta.3

### Current behaviour
![captura de pantalla 2017-12-01 a las 3 33 47](https://user-images.githubusercontent.com/9091881/33482197-3f7c26ea-d66e-11e7-996f-3002ad18b45f.png)

after this, it opens but just does not work.

![captura de pantalla 2017-12-01 a las 3 34 20](https://user-images.githubusercontent.com/9091881/33482244-7c68f90c-d66e-11e7-84c2-702d6aa1d096.png)

we can't all have 10.12.

**Comment by skllcrn** [comment]
Due to our limited time and resources we've decided to focus our efforts on macOS 10.12 and up. You are however free to either fork or contribute to optimise for older OS versions!

**Comment by albinekb** [comment]
@skllcrn Should we Improve the error message? It's now an "Unhandled error", we could handle that error and display a nicer message about not supporting older macOS versions

**Comment by skllcrn** [comment]
That'd be great @albinekb, could you create a separate issue for it?
