### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by timothyis** [wulkano/kap#31]
Separate issue from #20.

**Comment by PaulBGD** [comment]
Just opened this, should be ready soon https://github.com/wulkano/aperture.js/pull/3

**Comment by okdewit** [comment]
Active issue on aperture.js about Linux support is now wulkano/aperture.js#7

**Comment by roccomuso** [comment]
+1

**Comment by CodeTheory** [comment]
For the record, Linux currently has some issues with transparency, which is required for the cropper window.

**Comment by matheuss** [comment]
@roccomuso plese don't `+1` issues

**Comment by PaulBGD** [comment]
@CodeTheory Actually, there's an NPM package right here that works for the cropper window: https://github.com/PaulBGD/LinuxAreaSelector

**Comment by skllcrn** [comment]
As mentioned in https://github.com/wulkano/aperture/issues/46 we encourage anyone motivated to port Kap to other platforms to create their own fork. 

If that person is you, these could help you get started:

- [Port to Linux](https://github.com/wulkano/kap/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+linux)
- [Linux Support](https://github.com/wulkano/aperture/pull/32)

**Comment by Serkan-devel** [comment]
Could ffmpeg be used if installed?
