### ISSUE TITLE
Resolve feedback in #306

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#310]
It was merged to unblock @sallar, but there were some unresolved things that need to be fixed: https://github.com/wulkano/kap/pull/306#issuecomment-355160210

**Comment by sindresorhus** [comment]
Only the below is relevant anymore:

- When choosing "Fullscreen", the recording misses a few pixels on the edges of the screen.
<img width="409" alt="screen shot 2018-01-04 at 00 46 46" src="https://user-images.githubusercontent.com/170270/34544801-cbe34ce6-f0e8-11e7-9958-827ea9a41b88.png">

The left is my screen, the right is the recording. I intentionally moved the window some pixel from the edge to show that the white stripe is not in the recording.

**Comment by sindresorhus** [comment]
@sallar Interested in looking into this when you have some time?

**Comment by sallar** [comment]
@sindresorhus we are sending x: 1, y: 1 as coordinates, thats why. but when I change that to 0 and 0, the cropper doesnt show lol. but yeah I can look into it!

**Comment by sindresorhus** [comment]
@sallar You have to place the cropper at 2xy because of the border (cropper buffer variable), but subtract the border correctly when we send the coordinates to Aperture, which does the actual recording.
