### ISSUE TITLE
It's not possible to move the Preferences window

### ISSUE THREAD

**Issue by scorchio** [wulkano/kap#323]
**Platform:** Darwin scor-mac.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
**Kap Version:** 2.0.0-beta.4.556
### Steps to reproduce
1. Open the Preferences (either with the gear button or with Cmd + , )
2. Try dragging the Preferences window on the top.

### Current behaviour
The window doesn't move.

### Expected behaviour
It should, just like any other window on macOS :)

**Comment by CodeTheory** [comment]
Ah, good catch @scorchio! This was my bad, I removed the drag area for the window header in order to disable the drag cursor on the Kap main window, I didn't think about the consequences on other windows.
