### ISSUE TITLE
Kap 1.0.1 says I'm up to date, yet there's a 2.x beta?

### ISSUE THREAD

**Issue by steveharman** [wulkano/kap#325]
**Platform:** macOS 10.12.6
**Kap Version:** 1.0.1 
### Steps to reproduce
Launch KAP
Check for update s
### Current behaviour
Tells me I'm up to date
### Expected behaviour
Maybe a mention of the 2.x beta?
### Workaround
Manual download of the beta 

I understand that a beta isn't a release, but anyone not on the email list might miss the fact that there's a new beta & it might be handy for the 1.x update mechanism to offer the beta download option?

**Comment by onordbo** [comment]
Yes, there's a beta branch available where you can download the latest bleeding edge of Kap and help us test it — prior to an official, stable release.

You can download it here 👉  https://kap-artifacts.now.sh/beta

**Comment by steveharman** [comment]
Yes, I have the beta.   My point was that, for anyone not on the mailing list - how do they find out about the new beta ?  

Wouldn't it be handy to offer the beta download to 1.x users as an option when they use "Check for updates" ?

**Comment by skllcrn** [comment]
We're keeping them completely separate, the beta is not an equal to the latest stable and we want to maintain some control of how many are using it.

**Comment by steveharman** [comment]
Oh ok.  I thought today's email and post on Product Hunt about the beta was intended to get as _many_ people using it and submitting feedback as possible.  The beta doesn't overwrite the version 1.x release after all.

No worries.  The beta doesn't work for me atm anyway.  (please see  #326)
