### ISSUE TITLE
Multiple screens currently not supported

### ISSUE THREAD

**Issue by mmoutenot** [wulkano/kap#33]
Right now, if you launch Kap and move the selection window to a second screen it ignores and records the entirety of the first screen instead.
1. click the selection button
2. drag the selection onto a second screen
3. hit record
4. hit done.
5. view the "kapture" -- it will be of the first screen, and of a different size than the selection (full height / width)

**Comment by doot0** [comment]
Yo @mmoutenot, thanks for the report. Will attempt to reproduce ASAP. 

I believe this problem stems from not using [Electron's Screen API](https://github.com/electron/electron/blob/master/docs/api/screen.md) to figure out the currently active display before recording.

**Comment by mmoutenot** [comment]
Yeah that sounds about right. After testing again it seems like it might just be whatever screen you have Kap active. So the Screen API must default to that.

**Comment by mmoutenot** [comment]
`screen.getDisplayMatching(rect)` seems like it could be useful, if not used already ;)

**Comment by matheuss** [comment]
@mmoutenot Thanks for creating the issue! 😄 

ATM, we're using Quartz's [`CGMainDisplayID()`](https://github.com/wulkano/aperture/blob/master/swift/aperture/Recorder.swift#L13). TBH, I don't remember how it works, but seems that [it returns the id of the display that contains the menubar](https://developer.apple.com/reference/coregraphics/1455620-cgmaindisplayid).

Anyways, we definitely need to support multiple displays! I'm able to test it – I have a (_shitty_) external display lying down somewhere – so I can guarantee that we'll ship it in `v1.0.0` 😄

**Comment by doot0** [comment]
We've had a lot of issues with this recently. Priority bump? @matheuss @skllcrn @CodeTheory

**Comment by CodeTheory** [comment]
@doot0 bumped to high

**Comment by kud** [comment]
Related:

- https://github.com/wulkano/kap/issues/728
- https://github.com/wulkano/kap/issues/729
