### ISSUE TITLE
Be able to record speaker audio too (besides mic audio)

### ISSUE THREAD

**Issue by sapeish** [wulkano/kap#331]
**Platform:Mac
**Kap Version:1.0.1

Would be nice to be able to enable/disable recording of speaker audio, for instance a song playing in my local computer or the incoming audio in a conference.

Currently Kap records my mic audio only.

**Comment by albinekb** [comment]
Hi, thanks for opening this issue 🙂 You can follow the discussion over at #145, tl;dr it's complicated, there are however workarounds if you need this  👍
