### ISSUE TITLE
Couple of UX questions

### ISSUE THREAD

**Issue by steveharman** [wulkano/kap#338]
Hi,

a) Did I miss something, or is it now no longer possible to un-pin Kap's menu-bar dropdown window and drag it out of the way?  I appreciate the window disappears once recording begins, but if I want to define a custom window that uses the area of the screen occupied by Kap's dropdown window it's a bit of a pain.  I used to have the window floating on monitor 2 while recording on monitor 1 but now it seems impossible to detach from the menu bar?

b) Is it now mandatory to have the "preview playback" process after a recording ends?  Is there an option to not have this and just open a save-as dialog after a recording ends,  as currently happens in 1.x.  

Thanks,

Steve

**Comment by skllcrn** [comment]
Thanks for creating an issue regarding the detached state in the latest beta, that's exactly what we wanted to know; how important is the detached state to the people that use it, and how often is it used. Personally I use it all the time! If we get more feedback like this we'll bring it back as part of #223. 

Regarding the preview, yes, it's mandatory. The preview holds all the export functionality including selecting the file format and exporting using plugins. We've tried to make this as quick as possible, opening a "Save as..." dialog immediately after completing the recording would result in the exact same amount of steps as the current solution.

**Comment by albinekb** [comment]
https://github.com/wulkano/kap/pull/198 this was an attempt at fixing/speeding up the process of exporting a Kapture, maybe we could take this idea up again, see https://github.com/wulkano/kap/issues/238 for the issue 👍

**Comment by skllcrn** [comment]
Making good progress on a new version of Kap that builds on this and all the other feedback we've received, I'll close this now but do chime in on #113 and #223 if you've got additional thoughts to share with us!
