### ISSUE TITLE
Can't launch Kap on OSX after installing

### ISSUE THREAD

**Issue by andriy-m** [wulkano/kap#351]
Platform: Mac OSX 10.11.6
Kap Version: 1.0.1

I downloaded the dmg from https://getkap.co/, copied to Applications and launched by double clicking. It fails with an error message (see attached). Seems like it doesn't have the right permissions:

![screen shot 2018-01-25 at 11 15 32 am](https://user-images.githubusercontent.com/2603195/35407712-b7471efe-01c1-11e8-820a-cce96a6f2f6c.png)

**Comment by skllcrn** [comment]
Could you try again using [`master`](https://kap-artifacts.now.sh/master) and let us know if you're able to recreate the issue?

**Comment by ackzell** [comment]
I think you can't use it anymore @andriy-m , this happened to me after updating Kap on my machine:
![image](https://user-images.githubusercontent.com/601266/35688745-7bc12778-0737-11e8-8b0e-099666327930.png)

**Comment by skllcrn** [comment]
This version of Kap is no longer supported, and the newer version of Kap requires macOS 10.12 or later. I understand it sucks, but we have to focus our resources on making Kap the best it can be for as many people as possible. There are two workarounds; either forking Kap to fit your needs or updating your OS.

**Comment by lzrski** [comment]
If I downgrade Kap, can I still use it on OS X 10.11? What version of Kap runs on 10.11?

**Comment by skllcrn** [comment]
You can download [previous releases](https://github.com/wulkano/kap/releases) @lzrski, but they are not supported.

**Comment by lzrski** [comment]
Ok. So versions before 2.0 are compatible with OS X 10.11.

Perhaps you could make it so it doesn't auto-upgrade on non-compatible hosts? I understand your position and that it's a free software (as in beer and speech), so I don't blame you for not supporting older platforms. But from my perspective it used to work, and then stopped apparently for no reason. It's not very user-friendly, is it?

Anyway, thanks for your work. I really appreciate it.

**Comment by albinekb** [comment]
@lzrski see https://github.com/wulkano/kap/issues/367#issuecomment-365176584 for instructions on how to disable updates for old versions.
