### ISSUE TITLE
Sort app recording list by last and most used

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#352]
A note from working on #298: In the future we might want to sort apps you can record by last and most used.

**Comment by sindresorhus** [comment]
My suggestion is to increase a count each time an app is chosen in the app list along with the timestamp. Then we sort the last used app first, and the rest of the apps are sorted by usage count, when presenting the list.

**Comment by sallar** [comment]
@sindresorhus should this be persisted to disk? if so, what method do you suggest I do that with?

**Comment by sindresorhus** [comment]
@sallar Yes, should be persisted. You can use [`electron-store`](https://github.com/sindresorhus/electron-store) for that (Already included as a dependency).
