### ISSUE TITLE
Indeterminate export progress

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#354]
Plugins might want to show what's happening during export, but might not be able to provide percentage progress information, like [`kap-giphy`](). Would be nice to have an indeterminate progress bar for those cases. Could be triggered by using `.setProgress(text, percentage)` without the `percentage` parameter.

https://www.google.co.th/search?q=indeterminate+progress+bar&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjYs4vjzf3YAhVMMo8KHYU1DRwQ_AUICigB&biw=1440&bih=804#imgrc=_

@skllcrn If you agree, could you make a design of how it should look? I guess something like this, but in the Kap style:

![puc7j](https://user-images.githubusercontent.com/170270/35521930-a016913a-054d-11e8-86bf-7ffe85eea9a0.gif)

**Comment by skllcrn** [comment]
We can include both a determinate and indeterminate spinner in the export window (#263) for the rewrite (#223): 

![Export window](https://user-images.githubusercontent.com/8440026/40575952-f2f3b0d4-60ee-11e8-939b-7362c557e02d.png)
