### ISSUE TITLE
Option to hide mouse cursor does not work.

### ISSUE THREAD

**Issue by michaelpumo** [wulkano/kap#356]
**Platform:**
MacOS High Sierra

**Kap Version:**
1.0.1 (1.0.1.170)

### Steps to reproduce
Set mouse cursor to hidden in preferences.

### Current behaviour
Mouse cursor is not hidden, even after restart of the app.

### Expected behaviour
Mouse cursor should be hidden in recordings.

### Workaround
None I know of.

### Extra Request
If this is going to be fixed, it would be great to have the mouse cursor hidden, but also show clicks. At the moment you can only set clicks to show if the mouse cursor is set to visible. It would great to have the ability for both combinations.

**Comment by albinekb** [comment]
Can't reproduce on latest master: 
![kapture 2018-01-30 at 14 22 17](https://user-images.githubusercontent.com/5027156/35568358-faef3f50-05c8-11e8-9e5f-7fddd21adde0.gif)

Could you try using the latest? https://kap-artifacts.now.sh/master

**Comment by michaelpumo** [comment]
Seems to be fixed on latest update. Thanks.
