### ISSUE TITLE
Speed up time to recording

### ISSUE THREAD

**Issue by albinekb** [wulkano/kap#358]
An idea I had that could make Kap even nicer to use for quick Kaptures. Currently to record a simple gif you need to:

1. Click the kap icon in your menubar
1. Click the record button once to bring up the cropper
1. Position the cropper and press record
1. ... export or do what you want

I propose we remove step 2 completely, and always have the cropper show as soon as the kap record window is shown, that way we save a click and make it so you can just:

1. Click the kap icon in your menubar (brings up the cropper too)
1. Position the cropper and hit record
1. ... export or do what you want

**Comment by albinekb** [comment]
I think https://github.com/wulkano/kap/pull/409 will solve this 🕵️

**Comment by mrcolo** [comment]
I would like to work on this!

**Comment by skllcrn** [comment]
Closing this now, if you're still interested in contributing to this @mrcolo you can see our progress so far on #223 at https://github.com/wulkano/kap/pull/450
