### ISSUE TITLE
Stuck mouse cursor label on recording

### ISSUE THREAD

**Issue by patrols** [wulkano/kap#362]
**Platform:** Darwin Patricks-MBP 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
**Kap Version:** Version 2.0.0 (2.0.0.681)
### Steps to reproduce
Start recording -> immediately drag mouse pointer to recording area, and stop moving the mouse pointer

![kapture 2018-02-01 at 10 38 21](https://user-images.githubusercontent.com/4093546/35671562-1d366d80-073c-11e8-9179-88d1acc4c68e.gif)

**Comment by lexcorp16** [comment]
Hey @patrols I would like to take a crack at this. This is my first attempt at contributing to opensource and I would be glad if you could point me in the right direction. Thanks

**Comment by patrols** [comment]
Sure! @lexcorp16  Are you not able to reproduce this?

**Comment by albinekb** [comment]
Here's the line that adds that title https://github.com/wulkano/kap/blob/master/app/src/renderer/views/main.pug#L34

I don't know what the best way to fix this is, feels like a bug with electron/chrome? We could do some hack to remove the `title` attrubute when the window goes away, or just remove it completely and save us the hassle? @skllcrn toughts?

**Comment by skllcrn** [comment]
It's really strange that a `title` attribute for an element in a window carries over to a new window like this... I don't think we should remove it completely though, we should rather make sure we have proper `title` attributes everywhere—though that's another issue.

**Comment by timothyis** [comment]
We could try and remove the `title` attribute on click of the button? This removes the label on the web at least. Might be a good workaround.

**Comment by sindresorhus** [comment]
Seems like a [common issue](https://www.google.co.th/search?q=mac+stuck+tooltip&oq=mac+stuck+tooltip&aqs=chrome..69i57j0j69i64.2649j1j1&sourceid=chrome&ie=UTF-8). I've had it many times before too with Chrome.
