### ISSUE TITLE
Main window displayed in a wrong place with window controls after changing display arrangement

### ISSUE THREAD

**Issue by jsynowiec** [wulkano/kap#364]
**Platform:** macOS 10.12.6 (16G1114)
**Kap Version:** 2.0.0.681

This is probably related to #53 

### Steps to reproduce

This requires an external display to reproduce.

1. Start Kap.
2. Click on the Kap tray icon/use Kap in any way.
3. Leave Kap tray window visible.
4. Change arrangement of displays.
5. Click on the Kap tray 

### Current behaviour

![screen shot 2018-02-01 at 14 32 05](https://user-images.githubusercontent.com/1029142/35681414-9cb5e088-075d-11e8-9813-36ba375790c5.png)

### Expected behaviour

Kap window stays as a _tray_ window, attached to the tray icon.

**Comment by skllcrn** [comment]
Fixed in #494
