### ISSUE TITLE
Support selecting the viewport by drawing like RecordIt

### ISSUE THREAD

**Issue by vinhlh** [wulkano/kap#370]
This behavior of RecordIt is quite cool :D
I just have to press Cmd + 1, drawing an area, and Cmd + 1 again to Record 💃 And finally press Cmd + 1 again to finish.
![kapture 2018-02-02 at 13 42 07](https://user-images.githubusercontent.com/261283/35720101-e7a44078-081e-11e8-8d67-5d069491df36.gif)

**Comment by skllcrn** [comment]
You can CMD + 5 to trigger the marquee tool and hit enter to start the recording once you've cropped the area you want to record. Alternatively hit the record button in the main app window one time to trigger the tool, and once you resized and placed it where you want it, hit the record button again to start the capture. Remember that you can also select fullscreen, specific windows or an aspect ratio for your recording. 

![kapture 2018-02-02 at 7 56 16](https://user-images.githubusercontent.com/8440026/35721732-b9634fe0-07f3-11e8-8674-de3ad5ece747.gif)
