### ISSUE TITLE
Replace the framerate slider in the Preferences with a dropdown

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#371]
It doesn't make a lot of sense to record, for example, 27 fps.

The dropdown should contain:

- 10 FPS
- 15 FPS
- 25 FPS
- 30 FPS
- 60 FPS

With the default being 30 FPS, like it currently is.

**Comment by AluminiumTech** [comment]
Yeah but there should be an option for a custom fps number to be added. E.g. 45 fps or 90fps or whatever.

Also the 25fps should probably be replaced with 24 fps as 24 fps is the industry standard for movies and videos. 25fps is not an industry standard at all.

10-15 fps could be removed as neither are popular these days.

**Comment by sindresorhus** [comment]
I disagree with having a custom input. There's no good reason I can think of to record 45 FPS. 90 FPS is not possible. Also, none of the screen recorders I've tried has that.

> Also the 25fps should probably be replaced with 24 fps as 24 fps is the industry standard for movies and videos. 25fps is not an industry standard at all.

This is not correct. 24 FPS is the standard for movies, but 25 FPS is the European (PAL standard) for video. It makes no sense to use 24 for recording the screen. I don't think it makes sense to use 25 FPS over 30 FPS for screen recording either, so maybe we could drop 25 FPS too.

> 10-15 fps could be removed as neither are popular these days.

It can be useful for people that only record GIFs as it would mean faster transcode time, but I guess we could drop the 10 FPS.
