### ISSUE TITLE
Bring back the show/hide Cursor Option Icon

### ISSUE THREAD

**Issue by wottpal** [wulkano/kap#373]
**Platform:**
**Kap Version:2.0.0**

**Feature-Request:**
First: I appreciate your hard work on making Kap 2 possible. This is a great update! I've used Kap 1 from the first day and recommended it to everyone who asked :)

I often have different purposes for recording and it would be so useful to have that little cursor-icon in the Kap-window from version 1 back which shows/hides the cursor in recordings. I know this is possible in the settings-menu but very inconvenient because my needs differ from time to time.

Thanks and Regards from Germany!
Dennis

**Comment by skllcrn** [comment]
Hi from Norway, Dennis! We removed this after doing some research that indicated that people don't change this setting as often as we initially assumed. For the app to be easy to use for as many as possible we maintain a carefully considered set of options and features, which means we're not able to cater to everyone. What I suggest is that we include a keyboard shortcut to toggle the cursor in #150, and hopefully that will be a decent workaround for you!

**Comment by wottpal** [comment]
That's totally fine!
I would like to see any sort of notification/temporary indicator after the shortcut-change happened. So I know it worked and I don't have to repeat my recordings if it didn't :)

**Comment by albinekb** [comment]
That's a great idea with the notification @wottpal I'll keep that in mind when this gets reviewed!

**Comment by wottpal** [comment]
Another quick note: The 'Highlight Click' option should be memorized IMO. At least for me it's the case that if I record with the cursor I always want to highlight clicks as well.

Here a little _inception_-recording of the current behavior (if you know what I mean 😅)
![kap](https://user-images.githubusercontent.com/3930150/35737861-42ccbfa8-082d-11e8-94de-a871d4d2c8a7.gif)
