### ISSUE TITLE
Feature Request: Speed-Option in Export Window

### ISSUE THREAD

**Issue by wottpal** [wulkano/kap#374]
**Kap Version:**
2.0.0

**Feature Request:**
Still being thrilled about the new release I thought about how Kap could be even better for me. And it turns out I would really like to see some speed-options in the export window. Right next to the FPS-setting there could be a combo-box which several options for speeding-up / slowing-down the recording like 0.5x, 0.75x, 1x (default), 1.25x, 1.5x, 2x, 3x.

What do you think?

Dennis

**Comment by skllcrn** [comment]
Thank you for the issue @wottpal, please keep sharing your ideas and thoughts. This feature request would definitively fall into the category of editing, which is not within the scope for Kap. See my comment on https://github.com/wulkano/kap/issues/115#issuecomment-266576958
