### ISSUE TITLE
Linked plugin folder doesn't show up

### ISSUE THREAD

**Issue by urre** [wulkano/kap#375]
I'm creating a Kap plugin.

Followed [the guidelines](https://github.com/wulkano/kap/blob/master/docs/plugins.md) but can't seem to get my plugin listed in the app.

Thanks for a great app, thankful for some input

Platform: Darwin MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64
Step to reproduce :  Npm linked my local plugin in the plugins folder like described. Added "plugin-name": "latest" to the to the "dependencies" in the package.json there.
Current behaviour: In the plugin tab, no plugins show up. Only link to "Show the plugins folder"

**Platform:**
**Kap Version: Version 2.0.0 (2.0.0.681)**

**Comment by sindresorhus** [comment]
The issue was introduced in https://github.com/wulkano/kap/pull/347/commits/c6ba9380310ac460e348cacd6a0edd0fb482ebf1#diff-d5dad5083988c4f93c867122253af8cdR80 @sallar Why was this added?

**Comment by sallar** [comment]
@sindresorhus no not a mistake actually. Structure of installed plugins and available plugins is different. One has homepage key directly the other has it under “links”. Previously there was two templates for only this reason, I turned them into one and for this issue I added this `||` thing.

**Comment by sallar** [comment]
The way you fixed it (by removing the second part) actually dies on my local.

**Comment by sindresorhus** [comment]
I missed that. Should be fixed for real now.
