### ISSUE TITLE
Plugins authentication with oauth

### ISSUE THREAD

**Issue by mderazon** [wulkano/kap#380]
New plugins are really nice. I would like to try and create a plugin for Dropbox but the only authentication mechanism they have is oauth. Have you thought about how plugins will authenticate the user with oauth ?

**Comment by albinekb** [comment]
That's a great question! Maybe we could do it a bit how zeit does the oauth login in their CLI? We need somehow to proxy the oauth request since dropbox wants to talk to an http endpoint correct? 🤔

**Comment by mderazon** [comment]
> dropbox wants to talk to an http endpoint correct? 

Looks like it can be localhost:
<img width="811" alt="screen shot 2018-02-06 at 8 21 24" src="https://user-images.githubusercontent.com/717076/35844549-ce0f7aba-0b16-11e8-8463-e11ebfb59ffb.png">

Still probably need Kap to run a server to intercept the authorization code from DB and then exchange it for access / refresh tokens

Dropbox also supports [implicit flow](https://labs.hybris.com/2012/06/05/oauth2-the-implicit-flow-aka-as-the-client-side-flow/) but the access tokens are short lived.

**Comment by matheuss** [comment]
I recommend the approach I took on `now gcp login`: [just create an HTTP server](https://github.com/zeit/now-cli/blob/canary/src/providers/gcp/login.js#L91) that listens on a ["random" port](https://github.com/zeit/now-cli/blob/8c16f4282644bc0561105731301cf6c49fe7de14/src/providers/gcp/login.js#L28-L29) to receive the data via the callback 👌

**Comment by albinekb** [comment]
That's awesome, thanks @matheuss 

We should probably provide an API for this so we can use one server in Kap and not let all plugins run their own? Thoughts @sindresorhus @sallar

**Comment by skllcrn** [comment]
Related issue: https://github.com/wulkano/kap/issues/286

**Comment by sallar** [comment]
We open a Window for authenticating with DropBox and it's not so complicated... It can be done from the plugin itself too.
https://github.com/buttercup/buttercup-desktop/blob/master/src/renderer/system/auth.js#L25

**Comment by skllcrn** [comment]
Plugin developers can support this in their configuration

![plugin-configuration](https://user-images.githubusercontent.com/8440026/46047264-af5ea900-c124-11e8-80c0-9c74bff4b021.png)
