### ISSUE TITLE
Can't cancel plugins that are not using the provided request method

### ISSUE THREAD

**Issue by sallar** [wulkano/kap#382]
**Platform:** macOS 10.13
**Kap Version:** 2

### Steps to reproduce

Install [Kap Cloudinary Plugin](https://github.com/urre/kap-cloudinary) and when exporting using that, try to cancel the export.

### Current behaviour

Cancel button does not do anything or throws an error.

### Expected behaviour

The export should be canceled.

---
Currently only the plugins that are using the provided `context.request()` method can be canceled. Otherwise the plugin itself should be using a cancelable promise instance.

**Comment by skllcrn** [comment]
Fixed via #494
