### ISSUE TITLE
Updating Kap breaks compatibility with the OS

### ISSUE THREAD

**Issue by shime** [wulkano/kap#386]
**Platform:**
MacOS 10.11.2 ElCapitan
```
Darwin Hrvojes-MacBook-Air.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64
```  
**Kap Version:**
1.0.1
### Steps to reproduce
Download version 1.0.1 and click the update button.
### Current behaviour
The app stops working and reports that it's not compatible with the older version of MacOS. The message is: "You have OS X 10.11.2. The application requires OS X 10.12 or later.".

### Expected behaviour

App should not report available updates if they are incompatible with the OS version.
 
### Workaround

Reinstall Kap 1.0.1 and don't press the update button.

**Comment by sindresorhus** [comment]
Our update server doesn't support checking the required macOS version, unfortunately, so not much we can do about this.
