### ISSUE TITLE
Installing on OSX: The operation can’t be completed because one or more required items can’t be found. (Error code -43)

### ISSUE THREAD

**Issue by annapowellsmith** [wulkano/kap#391]
**Platform:** Darwin MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
**Kap Version:** 2.0.0
### Steps to reproduce Drag
Download .dmg, double-click and drag Kap to Applications folder
### Current behaviour
Popup appears saying: `The operation can’t be completed because one or more required items can’t be found. (Error code -43)`
### Expected behaviour 
Installing
### Workaround
None

**Comment by sindresorhus** [comment]
https://apple.stackexchange.com/questions/139105/error-the-operation-can-t-be-completed-because-one-or-more-required-items-can

**Comment by skllcrn** [comment]
We suspect this issue is upstream @annapowellsmith. Will close this issue shortly if we don't hear back from you.

**Comment by annapowellsmith** [comment]
Yes, it was upstream. (I did Google!) Thanks, closing this.
