### ISSUE TITLE
Incorrect permissions for .config

### ISSUE THREAD

**Issue by kasperkamperman** [wulkano/kap#392]
**MacOS 10.12.6:**
**Kap Version:2.0.0**
### Workaround: no idea

<img width="423" alt="screen shot 2018-02-08 at 21 43 52" src="https://user-images.githubusercontent.com/1760616/35997246-38209c64-0d19-11e8-82c7-8a311f5a3d69.png">

**Comment by skllcrn** [comment]
Try running `sudo chown -R $USER:$GROUP ~/.config` @kasperkamperman

**Comment by kasperkamperman** [comment]
That did the trick, however you can't expect from an average user to mess around in Terminal I think.

**Comment by timothyis** [comment]
Absolutely agree @kasperkamperman. We'll keep this issue open and look into providing a better experience for the next user with this problem 🙏
