### ISSUE TITLE
Could not call remote function

### ISSUE THREAD

**Issue by andomain** [wulkano/kap#394]
Hi,

On opening for the first time I tried to expand the `1:1` dropdown and got an error.

**Platform:**
macOS 10.13.2
**Kap Version:**
Version 2.0.0 (2.0.0.681)
### Steps to reproduce
Open Kap, click '1:1' dropdown
### Current behaviour
Gives the following error: 
`Unhandled Error
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 2, conversion failure from 62.890625
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 2, conversion failure from 62.890625
    at HTMLDivElement.el.onclick (/Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/size-selector.js:258:12)
`
### Expected behaviour
Dropdown opens correctly

**Comment by skllcrn** [comment]
I doubt this is related to installing Kap using `brew`, so I'll remove references to that in the issue title and description @andomain. 

It's an elusive bug, but we've made changes to the underlying functions that seem to have solved it. Can you check if you're still able to reproduce on the latest version (2.1.2)?

**Comment by andomain** [comment]
Hi

Yes, reinstalled 2.1.2 today and it works fine, thanks
