### ISSUE TITLE
Kap kepps updating from 1.0.1 to 2.x

### ISSUE THREAD

**Issue by steveharman** [wulkano/kap#395]
Fairly sure I'm not imagining this.  

Case:  I do **not want Kap 2.0**.  I want to keep using 1.0.1 which does everything I want it to (saves as MP4 without crashing) and has the tear-off control panel that's been removed from 2.x/

But this is the third time I've launched Kap only to find that 2.x has been installed, which I then have to bin and reinstall my 1.0.1 that I keep to close by.

Is there a way of stopping this happening?  I couldn't find any "automatically update me" option inside Kap 1.0.1. I know there's the notification telling me an update is available but I never click it.

Thanks,

Steve

**Comment by skllcrn** [comment]
First of all, you're mentioning several separate issues here, some of which are already open (even ones that you've opened yourself and voiced extensively). Remember that you are free to contribute, or fork Kap to create a version that suits you better. This is one of the great advantages of open-source software. 

We do not support older versions of Kap and do not advice using them, as they don't have the latest security patches and performance improvements. However, this comment from @albinekb offers a workaround which will stop automatic updates: https://github.com/wulkano/kap/issues/367#issuecomment-365176584

**Comment by steveharman** [comment]
Sure, mentioning other issues as explanation to why I stick with 1.x in case anyone needed to know - I'm not attempting to raise them again.

You assume quite a bit in suggesting I fork Kap or create a different version aren't you?  Who said I was a developer?

I'll look into #367 - thanks.
