### ISSUE TITLE
Record internal audio

### ISSUE THREAD

**Issue by thiesschneider** [wulkano/kap#397]
Hi,

I am using the latest version (2.0.0.681) of Kap on the latest macOS. I want to record user tests which are streamed on my computer. 
For this I need to record the internal audio source. If I go to preferences I can only choose "Built-in Microphone".

Is there a way to record the internal audio only? 
Can you add an option for this?

thx in advance

**Comment by sindresorhus** [comment]
There’s an open issue about this already.
