### ISSUE TITLE
Kap is crashing when recording is over without error message

### ISSUE THREAD

**Issue by diego3g** [wulkano/kap#398]
I use Kap since the firsts versions but this recent update is causing me a lot of headaches.

Sometimes when i click on stop recording, Kap doesn't show the Preview Window with export options, it only stop recording but nothing happens and i loose everything i recorded. Kap used to crash on old versions too but now i don't have any error message or something like this.

Darwin MacBook-Air-de-Diego.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

Kap Version: Version 2.0.0 (2.0.0.681)

**Comment by skllcrn** [comment]
We released an update earlier today (https://github.com/wulkano/kap/releases/tag/v2.1.0), are you able to reproduce after updating @diego3g?
