### ISSUE TITLE
Finder bar overlaps window in some cases

### ISSUE THREAD

**Issue by CodeTheory** [wulkano/kap#4]
When the finder bar is set to 'Auto Hide' and the kap window is open, when hovering at the top of the screen, the finder bar will slide down and cover the top of the kap window.

**Comment by CodeTheory** [comment]
@matheuss I think we should possibly look into detecting the state of the menu bar or forcing the menu bar as visible whilst Kap is open. https://github.com/electron/electron/pull/817

**Comment by skllcrn** [comment]
The menu bar should no longer cover the top of the Kap window, but remains in it's position. That's the same behaviour as for example Dropbox, but differ from the inconsistency seen in the system entries (macOS 10.13.1). Can you confirm using [`master`](https://kap-artifacts.now.sh/master)? 

![kapture 2017-11-01 at 17 01 38](https://user-images.githubusercontent.com/8440026/32284074-5f7aaa8e-bf26-11e7-892a-46a48871666d.gif)

**Comment by CodeTheory** [comment]
Can't reproduce anymore on v2. Closing.
Please comment if you can reproduce.
