### ISSUE TITLE
Cannot save to mp4 (Error in plugin kap)

### ISSUE THREAD

**Issue by LasseHaslev** [wulkano/kap#406]
![image](https://user-images.githubusercontent.com/3670799/36844012-267397a8-1d51-11e8-94f7-7d1daf884a8e.png)

**Platform:**
 Darwin Lasses-iMac.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Kap Version:**
Versjon 2.0.0 (2.0.0.681)

### Steps to reproduce
1. Take a screenrecording.
1. Click on MP4
1. Save file
1. **Error**

### Current behaviour
- Throws error when trying to save to MP4.
- `WebM` works fine.

### Expected behaviour
Should not throw error when saving to MP4.

### Workaround
Could not find a workaround.

**Comment by timothyis** [comment]
Hi! Thanks for the issue. We are aware of this an have a fix coming soon (probably today or tomorrow). You can see the original issue here: https://github.com/wulkano/kap/issues/377#issuecomment-368922541
