### ISSUE TITLE
Audio Recording

### ISSUE THREAD

**Issue by mohammedzamakhan** [wulkano/kap#41]
I tried it, but didn't see the audio in my recorded video.

**Comment by tdreitz** [comment]
Not hearing audio in the recordings

**Comment by skllcrn** [comment]
This is a planned feature, we're actively working on it. Watch this space!

**Comment by joenash** [comment]
@skllcrn Hey! Just wondering if status of this is being tracked anywhere?

**Comment by matheuss** [comment]
@joenash just in time: check wulkano/aperture.js#6 ☺️

**Comment by joenash** [comment]
@matheuss great, thanks Matheuss! Great work from y'all, love both Kap and aperture.

**Comment by Khaledgarbaya** [comment]
Hi guys so this is the first video ever with audio done completely in Kap https://youtu.be/uOBTGvXjaVs . It is coming along. Make sure to check the PR https://github.com/wulkano/aperture.js/pull/6

**Comment by matheuss** [comment]
@mohammedzamakhan @tylerreitz @joenash if you were talking about recording the audio from the system (e.g. what's coming out from youtube), it's almost impossible 😔 

But if you were talking about microphones: it's out! 😄 Make sure to have the app open – you'll receive the update automagically ✨

**Comment by abreckler** [comment]
@matheuss i updated to the latest but don't see where to select a microphone input for the sound. Am i missing something? I tried using a few different sound inputs from my system preferences, but none worked when recording for the final output.

**Comment by CodeTheory** [comment]
If you click the cog icon, and then select preferences; on the second tab of preferences, you should be able to select a mic input.

![image](https://cloud.githubusercontent.com/assets/1695613/21123862/37e33e3e-c0d3-11e6-825d-5091a679f40d.png)

![image](https://cloud.githubusercontent.com/assets/1695613/21123864/3e8944d6-c0d3-11e6-8581-44d3e5731353.png)
_(At the bottom)_

**Comment by abreckler** [comment]
@CodeTheory got it! That did the trick. Keep up the great work guys! Loving these recent updates.
