### ISSUE TITLE
macOS - Kap 2.0.0 - Can't start due to permission error

### ISSUE THREAD

**Issue by fofoy** [wulkano/kap#411]
**Platform: Darwin florians-macbook-pro.home 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64**
**MacOS version: 10.13.3**
**Kap Version: 2.0.0**

### Steps to reproduce
Open Kap

### Current behaviour
Displays Unhandled Error on start-up

![image](https://user-images.githubusercontent.com/1737124/37035202-07f18a02-214c-11e8-8c08-39b334085ab1.png)

**Comment by sindresorhus** [comment]
This is fixed in master: https://github.com/wulkano/kap/commit/649d9838c12133337cf43c7435e66dba7df5771f I plan to do a beta release today.
