### ISSUE TITLE
Can't re-install older version of Kap on OS X 10.11.6

### ISSUE THREAD

**Issue by diz740** [wulkano/kap#412]
Kap must've updated itself manually. I'm running OS X 10.11.6 and the latest version doesn't run on this version of OS X. I tried re-installing both v1 and v1.01 and neither will run. Can someone please explain why this happens and also how to fully uninstall Kap?

Thanks.

**Comment by DrummerHead** [comment]
You can uninstall with `brew cask uninstall kap`, currently seraching for a way to install previous version.

**Comment by DrummerHead** [comment]
Following instructions [here](https://www.jverdeyen.be/mac/downgrade-brew-cask-application/) this command will re-install Kap:

```
brew cask uninstall kap
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/725602d6ea115415dd304c4a7cc6fd8fc4ec6e6d/Casks/kap.rb
```

This version (1.0.1.1) is working for me on OS X 10.11.6

Cheers!

**Comment by diz740** [comment]
Thank you!

**Comment by albinekb** [comment]
See https://github.com/wulkano/kap/issues/386#issuecomment-363732919, our update server does not support this. If you want to stay on an old version, see: https://github.com/wulkano/kap/issues/367#issuecomment-365176584 for a workaround to disable updates 😊
