### ISSUE TITLE
Can Kap be used to get screen recording of test run on Circle CI

### ISSUE THREAD

**Issue by aleenadavy90** [wulkano/kap#415]
Hi, I'm trying to get the screen recording of the test run in the $CIRCLE_ARTIFACTS folder in Circle CI.
Below is the test section of the build where I would like to start capturing 
```
test:
  override:
    - >
      if [ -n "${RUN_APPIUM_TESTS}" ]; then
        # Install java jdk8
        brew update
        brew cask install java
        brew update && brew cask install kap
        # Install maven
        brew install maven
        npm install -g appium@1.7.1
        appium &
        pod install
        xcodebuild CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= PROVISIONING_PROFILE= -scheme "Mumbo Jumbo" -workspace 'MumboJumbo.xcworkspace' -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,name=iPhone 6 Plus,OS=11.2' | xcpretty
        #cd to Code directory & run tests!
        pushd "appium-selenium/MumboiOSTests"
        mvn clean test;
        popd
      fi

```

How do I start kap from the command line, start recording and store the recoding in $CIRCLE_ARTIFACTS folder. Thanks in advance for the help!

**Comment by sindresorhus** [comment]
Kap can unfortunately not be controlled from the command-line.

**Comment by albinekb** [comment]
You can however use our recording library (macOS only) https://github.com/wulkano/aperture to archive this @aleenadavy90 💨
