### ISSUE TITLE
Kap update notifications are pushed during recordings

### ISSUE THREAD

**Issue by Qix-** [wulkano/kap#422]
**Platform:** MacOS Sierra (10.12.6)
**Kap Version:** 1.0.1 (1.0.1.170)
### Steps to reproduce
1. Wait for a Kap update to be available or maybe downgrade
2. Start recording something; wait a bit
3. A notification will appear reminding you to update kap - which, depending, will get recorded 😅 

### Expected behaviour
Kap shouldn't push update notifications if it's currently recording the screen.

### Workaround
Disable all notifications while recording.

However, the frustrating part is that I probably haven't booted Kap up in a while when I do a screen recording (I don't like to leave apps running idly by when I don't use them), so the situation arose where I had _just_ booted Kap up to do a quick recording, started recording, and then got the notification since it had been a while.

**Comment by rauchg** [comment]
Not sure if it's possible, but it'd be nice to temporarily halt _all_ notifications, and then have an option to override that, in case one is interested in particular in recording a notification.

I mention this because I've had some Slack notifications pop in during recordings that were unintended :D

**Comment by albinekb** [comment]
You can alt-click ![image](https://user-images.githubusercontent.com/5027156/37244711-6cb2133c-248d-11e8-87dd-6592b32faa64.png) in your menu bar to toggle do not disturb mode, that might be a half decent workaround to disable them without having it in Kap 👍

**Comment by timothyis** [comment]
Would be great for Kap to halt notifications during a recording, at least. Even better if we had an option to halt all notifications during a recording!
