### ISSUE TITLE
Touch Bar bugs

### ISSUE THREAD

**Issue by Qix-** [wulkano/kap#425]
**Platform:** MacOS
**Kap Version:** c11e02eb567b4c1552fa6beec0d7245134aa342d
### Steps to reproduce
( Requires Macbook Touchbar or [emulator](https://github.com/sindresorhus/touch-bar-simulator))

1. Open Kap
2. Tap `Crop`
3. Tap `Record`
4. Tap `Record` (again)
5. Try to click Kap icon in menu bar
6. Click `Record`
7. Try to do anything else with Kap

### Current behaviour
A number of things:

1. `Record` touchbar button doesn't switch to `Stop` or `Finish` or anything
2. `Record` touchbar button seems to start new recordings even though there's one ongoing
3. The Kap menubar widget freezes/lags and appears to remain in the "cropping" stage even though (after the above repro steps) the icon shows that it's recording

### Expected behaviour
Normal record flow, just with the touchbar.

### Workaround
Don't use touchbar :trollface: 

// cc @vadimdemedes since I believe he added the original touchbar functionality.

**Comment by sindresorhus** [comment]
> ( Requires Macbook Touchbar)

If someone without a Touch Bar wants to help out, they can use https://github.com/sindresorhus/touch-bar-simulator

**Comment by catalinmiron** [comment]
@Qix- @sindresorhus just opened a PR for fixing this bug. Please take a look at #460. Thanks!
