### ISSUE TITLE
Can't disable "Start automatically" option

### ISSUE THREAD

**Issue by danielbachhuber** [wulkano/kap#428]
As a Kap user, I'd like to disable the "Start automatically" option:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/36432/37437504-d7ca358a-27aa-11e8-843d-dc9325bf2686.png">

However, when I quit Kap and re-open, "Start automatically" is checked again:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/36432/37437530-f1c3c24e-27aa-11e8-9b39-40a3eea80f2e.png">

My expectation is that the option would remain unchecked.

```
$ uname -a
Darwin local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

**Comment by danielbachhuber** [comment]
If I remove Kap from my user's Login Items, then "Start automatically" is properly unchecked:

<img width="671" alt="image" src="https://user-images.githubusercontent.com/36432/37437609-5d8fa66e-27ab-11e8-80ae-fddb363ef751.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/36432/37437622-7109b978-27ab-11e8-88c1-426ec315942d.png">

**Comment by sindresorhus** [comment]
This is an issue with Electron: https://github.com/electron/electron/issues/10880

**Comment by sindresorhus** [comment]
This is fixed in master with the upgrade to Electron 4.
