### ISSUE TITLE
Provide option to save source file (to avoid export for long videos being extremely slow)

### ISSUE THREAD

**Issue by Jamedjo** [wulkano/kap#429]
### Steps to reproduce

Record long 30min video and attempt WebM export

### Problem

I was exporting a 30min recording and had to eventually abort the `WebM` export after a couple of hours. Using the inspector I checked the progress bar percentage which appeared to be stuck at 15%.

Attempting `mp4` export was slightly better: I could see progress being made but still slowly.

### Workaround

While looking around to find an exiting issue I noticed that `aperture.js` stores temporary files in `/var/folders/` and was able to find the video and copy it to my `Kaptures` folder instantly. Perhaps because this was on APFS?

### Feature request

1. Could you provide an instant export option which just copies the recorded video to the target directory?
2. ~~Could you provide more of a hint of expected export duration, or potentially a warning to avoid WebM export on long captures.~~ See: https://github.com/wulkano/kap/issues/437

### Platform

**Mac OS:** `10.13.3 (17D47)`
**Kernel:** `Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
**Kap Version:** `2.0.0 (2.0.0.681)`

**Comment by albinekb** [comment]
>While looking around to find an exiting issue I noticed that aperture.js stores temporary files in /var/folders/

This is the source file, it's not possible to export this file directly from Kap, when you choose "MP4" export, we still convert the file trough ffmpeg - even if there are no settings changed.

**Comment by skllcrn** [comment]
What FPS are you capturing at @Jamedjo? You can check your capture frame rate in preferences.

**Comment by matheuss** [comment]
`1.` is easy and it'd be very nice, indeed, to have it. `2.` is very tricky and I'm not sure it's possible to implement it 😕

**Comment by Jamedjo** [comment]
> What FPS are you capturing at @Jamedjo? 

I'm not entirely sure, but the preference toggle is set to off. Presumable that means it is using the default of `30 FPS` rather than the bolded `60 FPS`?

<img width="490" alt="screen shot 2018-03-25 at 13 33 18" src="https://user-images.githubusercontent.com/1028741/37875004-254a01a8-3031-11e8-9453-cd40b02d33ae.png">

**Comment by Jamedjo** [comment]
> 2. is very tricky and I'm not sure it's possible to implement it 😕

@matheuss Would it be possible to parse ffmpeg's output or pass in a progress option to determine how many frames or seconds of video have been processed?

Alternatively could we have a cut off where we show a warning if sending more than X mins of video to ffmpeg?

Should I open a second issue for this so this one can focus on instant export?

**Comment by Jamedjo** [comment]
> 1. is easy and it'd be very nice, indeed, to have it.

How should this look in the UI?

We could add an extra button labelled `Original`:
<img width="377" alt="screen shot 2018-03-25 at 13 46 24" src="https://user-images.githubusercontent.com/1028741/37875141-109182fc-3033-11e8-84fd-aed6e34cb491.png">

**Comment by skllcrn** [comment]
To clarify this seems to be 2 different issues: 

- One issue regarding processing time for WebM in particular.
- A feature request to access the original recording.

In the original issue you were attempting to export to WebM, which has a very different set of qualities compared to MP4 or MOV and will take longer to process. Exporting to another format isn't really a workaround for the processing time, as you'd lose out to the unique benefits of WebM. 

We're big fans of open formats such as GIF, WebM and APNG. MOV is not an open format, neither is MP4, but it has far wider support. I don't think the difference between MOV, MP4 and their support is common knowledge, which is why we spent time picking a good defaults. The last thing we want is analysis paralysis when picking the format for your Kapture and where to export it. We feel the formats we've chosen cover most needs, while also embracing and pushing future advancements. 

Sure, some exports might take longer, there's always trade-offs. In the case of MP4 you get a widely supported format that will work more or less whatever you chose to do with it, without having to put much thought into it. That, in part, helps make Kap a quick and easy solution for more people.

**Comment by Jamedjo** [comment]
@skllcrn Yes, two issues:
1. Wanting instant access to the original mp4 to avoid unbearable processing times
2. Wanting some kind of warning or time estimate when export will take hours

I'll open a second issue for the the warning/estimate feature request now.

For long videos I think the best default is to keep the recorded encoding. Container format isn't too relevant to this, as I think ffmpeg can change container format quite quickly if it doesn't have to re-encode. Since the original is an H264 encoded mp4 I think using the actual file is perfect. Especially on APFS where copying the file is a free operation.

> Exporting to another format isn't really a workaround for the processing time, as you'd lose out to the unique benefits of WebM.

I initially chose WebM out of habit since it is perfect for embedding online, but in this case container wasn't too important. Speed was, but neither format was taking a sane amount of time to export.

**Comment by Jamedjo** [comment]
Perhaps the new option should be labeled `instant` to emphasise that it is a quicker option: 

<img width="362" alt="screen shot 2018-03-25 at 16 27 13" src="https://user-images.githubusercontent.com/1028741/37876806-dca58558-3049-11e8-8cb0-a58b1b0cb569.png">

I do like that "Original" could help with https://github.com/wulkano/kap/issues/399 though. Saving with instant/original might prevent the "Are you sure that you want to discard this recording?" dialog, or could be provided as an option in that dialog.

**Comment by Jamedjo** [comment]
> If possible a better solution would be to check if there are any settings changes to the original file when exporting to MP4, and skipping the processing if there are none.

I missed this before...
Makes sense, and avoids the extra button 👍

> Exporting a 27 minute long recording to WebM took ~5 minutes, while exporting to MP4 takes less than half of that. Exporting to both formats the progress bar stops at ~20% before jumping at completion.

Hmmm... something must have gone wrong for mine. Early 2015 13" but WebM export at 15% after two hours would mean around 13 hours to export. Even with a stuck progress bar, 2h is a long way from 5mins. It looks like the FPS defaults to 15 on export, maybe that had an impact? Also, it was a near full screen recording.

> Adding "Original" as an export option is confusing as it appears in a list of formats

I think that confusion can be reduced by grouping it separately. While it does still add an extra button it avoids having to check FPS in two places to get a quick export, so a difficult trade off:

<img width="777" alt="screen shot 2018-03-25 at 20 19 08" src="https://user-images.githubusercontent.com/1028741/37879160-cfede662-306b-11e8-9ae3-e793469c5f61.png">

**Comment by skllcrn** [comment]
We're aiming to add this option to the "File" menu when viewing a recording in the Editor in our next release. The option is technically the same as exporting an MP4 without changes, skipping `ffmpeg`.
