### ISSUE TITLE
Unhandled Error - cannot open Kap

### ISSUE THREAD

**Issue by arjanski** [wulkano/kap#432]
Hello there,

I have a strange problem since I cannot use Kap on my main macOS user account. Downloading it, it won't open and gives the following popup with this error:

<img width="435" alt="capturfiles-19-53-2018_09 53 39" src="https://user-images.githubusercontent.com/13831998/37621699-085f25de-2bc0-11e8-9e66-c37f9c10b449.png">

Strangely, I can use Kap without problems on another user account on this machine, one which has no extra applications or node/NPM installed... 

Anyone knows how to fix this? Would really like to use Kap.

**Platform: macOS 10.13.3**
**Kap Version: 2.00**

**Comment by Davi-T** [comment]
I get a similar error when trying to export an MP4 (works fine exporting APNG/GIF though). See system specs and error screenshot below.

![system](https://user-images.githubusercontent.com/20928342/37624502-c1d552c6-2b9e-11e8-8b27-8e4e78fbd880.gif)


![kap_error](https://user-images.githubusercontent.com/20928342/37624461-9f526c02-2b9e-11e8-850b-5f2d78dbbe52.gif)

**Comment by skllcrn** [comment]
A fix for both these issues is being released today, see #411 and #326.

**Comment by arjanski** [comment]
Thanks, that was fast! Will try it out
