### ISSUE TITLE
Confusing prompt copy when cancelling an export

### ISSUE THREAD

**Issue by jonsadka** [wulkano/kap#436]
**Platform:**
`17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`
**Kap Version:**
`Version 2.1.1 (2.1.1.747)`
### Steps to reproduce
- Make a recording, 
- Export as .gif
- Click on `Cancel Export` button
- Read copy on the confirm cancellation modal 
### Current behaviour
Confirm modal says `Are you sure you want to cancel the export?` and the two options of `Continue` and `Cancel Export`. It is unclear if `Continue` means I want to continue with cancelling the export or continue with the export.
<img width="443" alt="screen shot 2018-03-23 at 9 00 51 am" src="https://user-images.githubusercontent.com/6504944/37840007-33fb5d6e-2e79-11e8-8caa-5a50b8d01508.png">
### Expected behaviour
Confirm modal says `Are you sure you want to cancel the export?` and the two options should say something like `Yes` and `No` or `Do not Cancel` and `Cancel`.

**Comment by skllcrn** [comment]
Ah, yes. We should change this to:

`Are you sure you want to cancel the export? `
`Cancel cancelling` or `Cancel`

On a more serious note; `Yes` or `No` is simple and obvious, but I'm not sure we need this prompt at all? You don't lose the original recording if you cancel the export.

**Comment by Jamedjo** [comment]
> but I'm not sure we need this prompt at all? 

@skllcrn Maybe it helps if the user clicks `[x]` to close the dialog during a long export instead of minimizing it? If explicitly clicking `Cancel Export` I don't think it is needed.

**Comment by skllcrn** [comment]
I think it's useful to have an explicit option to cancel, this is in part to future proof for queued exports. The button would allow you to cancel the currently active one and skip to the next in the queue, while closing the window would cancel all of them.

**Comment by Jamedjo** [comment]
> I think it's useful to have an explicit option to cancel

@skllcrn Agreed. Perhaps I should have worded my suggestion better:

> @skllcrn Maybe *the confirm modal* helps when the user *accidentally* clicks [x] to close the *export dialog* during a long export instead of minimizing it? If explicitly clicking Cancel Export I don't think *the confirm modal* is needed.

I like your suggestion to get rid of the confirm modal for the cancel button, but am think it might be worth keeping the confirm modal when cancelling the export through the title bar.

**Comment by sindresorhus** [comment]
I think the buttons should be `[Continue Export]` and `[Cancel Export]`. Yes/No buttons are not recommended by the macOS Human Interface Guidelines: https://developer.apple.com/macos/human-interface-guidelines/windows-and-views/alerts/

**Comment by skllcrn** [comment]
> I like your suggestion to get rid of the confirm modal for the cancel button, but I think it might be worth keeping the confirm modal when cancelling the export through the title bar.

This sounds like a good solution to me, with the changes @sindresorhus suggested.

**Comment by Jamedjo** [comment]
@skllcrn It looks like the prompt already only appears when clicking `[x]`, I've updated the text in https://github.com/wulkano/kap/pull/438
