### ISSUE TITLE
Options to hide menubar item and add dock icon?

### ISSUE THREAD

**Issue by danielbayley** [wulkano/kap#44]
There should be a choice between:
- Menu bar only (existing behaviour)
- Dock only (remove menu bar item)
- Neither (hotkey only trigger)

**Comment by matheuss** [comment]
Thanks for the issue @danielbayley 😌  While a preferences window is not released, you can drag the window off the menubar by clicking and holding the white area 😄

**Comment by sindresorhus** [comment]
Closing as we support hotkeys now and I don't see the point of having Kap in the Dock.

You can try out the latest beta here: https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.1
