### ISSUE TITLE
Website download button is still linking to 2.0.0 version

### ISSUE THREAD

**Issue by samgranger** [wulkano/kap#440]
Might be a good idea to link the download button to the latest 2.1.1 release on getkap.co - it's currently linking to the 2.0.0 release.

**Comment by samgranger** [comment]
Just noticed you have a repo for the website, closing this issue since it's better off there.

**Comment by davidjb** [comment]
The website repo is at https://github.com/wulkano/getkap.co for people wanting to report similar (or the exact same) issue.
