### ISSUE TITLE
New logo for Kap

### ISSUE THREAD

**Issue by mutluhn** [wulkano/kap#448]
I wanted to contribute to Kap. I designed a logo for it. If you like it, I'll send you files.

![kap](https://user-images.githubusercontent.com/35154172/38519553-e2ee7aa4-3c48-11e8-9f63-13c970ba3a3e.png)

**Comment by skllcrn** [comment]
Awesome that you wanted to contribute and started something on your own initiative! I dig that you used elements that are in our current brand and from our product. All that being said, we're not looking to do a rebrand and the complete redesign that would be needed for a direction like this now. 

One of the unique challenges for Kap is that the brand for the most part lives in a tiny space in the strip of the top menubar in macOS. There it's always displayed stencilled in black or white, but still needs to be instantly recognisable. 

It's always a good idea to look at the logo your designing in the environments it will be used in, including the ones that might be challenging. At the same time it needs to work without colour or opacity and at tiny sizes, which could be solved by having alternate versions of your logo optimised for different uses.  

![site](https://user-images.githubusercontent.com/8440026/38525461-b29cc1c6-3c52-11e8-93d1-71c521b3e897.png)

![dock](https://user-images.githubusercontent.com/8440026/38525467-b87022b4-3c52-11e8-9667-e5b149cb6a09.jpg)

![menubar](https://user-images.githubusercontent.com/8440026/38525468-ba95422c-3c52-11e8-81f7-322f18fa8ff4.png)

**Comment by mutluhn** [comment]
If you want to use I will provide different color variations and sizes.

**Comment by timothyis** [comment]
Hi @mutluhn! Thank you so much for looking into this! I think design is a very important part of open-source that doesn't get as much attention as it deserves. Unfortunately, as @skllcrn said, we're not really looking for a rebrand for Kap.

However, I don't to discourage you from contributing to open-source design. I encourage you to keep looking for other repositories that need designs! ❤️
