### ISSUE TITLE
Show activity indicator or progress bar when updating.

### ISSUE THREAD

**Issue by sorodrigo** [wulkano/kap#452]
**Platform:**
Mac OS 10.12.6 Darwin Kernel Version 16.7.0: RELEASE_X86_64 x86_64
**Kap Version:**
Version 2.1.2 (2.1.2.777)
### Steps to reproduce
Check for update, or close and open the app.
### Current behaviour
Shows a notification prompting the user to click to update. Performs update in the background.
### Expected behaviour
After being prompted to update display some sort of indicator showing that the update is in progress.
### Workaround
none

This is not a bug, more of a feature request. I understand if this is not a priority right now. Thanks anyway for this amazing app!

**Comment by sindresorhus** [comment]
The fix is to notify when the update is done downloading instead of just when it’s available. That way we can just notify and restart right away without the need for a progress indicator.

**Comment by mackness** [comment]
@sindresorhus I would like to work on this but it seems like this notification already exists? Is there more work that needs to be done?

https://github.com/wulkano/kap/blob/master/app/src/main/auto-updater.js#L40

**Comment by skllcrn** [comment]
We've implemented automatic updates in the background, applying updates when Kap is restarted.
