### ISSUE TITLE
Windows support: New Windows 10 Screen Recording APIs

### ISSUE THREAD

**Issue by Mancerrss** [wulkano/kap#456]
I'm not a dev or technical person, I'm just a designer but I've red about this recently. This might help to you guys.

https://mspoweruser.com/windows-10-scu-includes-new-screen-capture-api/

This will ship on upcoming Windows 10 April 2018 Update. I don't know if there's a way to utilize this even if you're not a UWP app, I've heard and discuss it too on Twitter and says it's possible, Win32 screen recorder apps could utilize it. 

Check out the article and their documentation

**And again, we would really love you guys to support Windows 10. Please try to be inclusive and ubiquitous to all. And if you can, ship it too in Microsoft Store**

**Comment by albinekb** [comment]
We're not shipping Windows because we have 0 people that work/use windows and also contribute, all of us are using macOS.

**Comment by sanlyx** [comment]
It seems like a managed wrapper around Desktop Duplication API, which my Windows port of Aperture is using on supported platforms. A lot of work is required, specially on older versions of Windows and multiple graphics cards scenarios, PRs welcome, I guess.

**Comment by skllcrn** [comment]
As mentioned in https://github.com/wulkano/aperture/issues/46 we encourage anyone motivated to port Kap to other platforms to create their own fork. 

If that person is you, these could help you get started:

[Initial support for Windows capture with Aperture.CLI](https://github.com/wulkano/aperture/pull/56) (#56)
[Initial Windows support](https://github.com/wulkano/aperture/pull/38#issuecomment-362252400) (#38)

**Comment by robcresswell** [comment]
@skllcrn Hey, so I read through the other issues but I couldn't see a solid answer on this; why is the official stance to open a fork for every other distribution? That seems like it would create a lot of extra overhead / duplicated code. Is Aperture supposed to be superseding Kap? Is it the same thing?

**Comment by robcresswell** [comment]
Ah awesome, that explains it, if its backed on to a MacOS engine then I can see why the complexity is so much higher. Thanks for taking the time to respond, I appreciate it.

**Comment by mengning** [comment]
let us ship kap to  windows https://github.com/mengning/kap

**Comment by masudhossain** [comment]
@mengning  is that repo working for windows ? 

I too would love it for windows and am willing to pay a developer to work with me on this.

**Comment by mengning** [comment]
@masudhossain yes, that repo is working for windows.

just works, it use ffmpeg to record desktop, I don't know whether the performance of ffmpeg is enough for recording video games, but we can try it out.

**Comment by levrik** [comment]
@masudhossain If you want to record video games on Windows just use OBS. It's really mature and widely used by Let's Players and streamers on Twitch and YouTube.

**Comment by masudhossain** [comment]
@levrik obs is really common for recording games, but we need some control over what to do with the recordings. Our idea was to allow recordings and then automatically upload it to our server via api post requests. 

@mengning i'll try it out now!

**Comment by styfle** [comment]
@masudhossain If you need to record the contents of the Electron window and send it to the server, checkout https://github.com/styfle/magnemite

**Comment by masudhossain** [comment]
@styfle unfortunately that doesn't work for us. We need to record the actual desktop.

**Comment by Mancerrss** [comment]
@masudhossain Are you guys looking for any UX designer tho?
