### ISSUE TITLE
Rewrite code to make XO happy without disabling any rule

### ISSUE THREAD

**Issue by matheuss** [wulkano/kap#46]
XO's [`v0.17.0`](https://github.com/sindresorhus/xo/releases/tag/v0.17.0) introduced some new rules and our code is not prepared for them.

[These exceptions](https://github.com/wulkano/kap/blob/c67a3177bcea10e143dfe5045efc830ba5803f6c/package.json#L40-L43) should be removed: 
- [ ] `import/no-extraneous-dependencies`
- [x] `import/no-unresolved`
- [ ] `import/named`
- [ ] `import/default`

cc @sindresorhus

**Comment by stursby** [comment]
@matheuss was starting to work through this... one of the errors is the following:

![image](https://cloud.githubusercontent.com/assets/527849/19291881/a083c2e6-8fdd-11e6-81e2-23493f767429.png)

Where is this [reporter.js](https://github.com/wulkano/kap/blob/master/app/src/main/auto-updater.js#L7) file??

**Comment by matheuss** [comment]
Here @stursby: https://github.com/wulkano/kap/blob/master/app/src/renderer/js/reporter.js 😄 

The problem is: When we run `npm run build`, gulp writes (almost) everything to `app/dist`.

@sindresorhus what do you suggest?

**Comment by matheuss** [comment]
To make it clearer: I implemented this `gulp.dest('app/dist')` to remove any `../../` and things like that from the `import`s 😄

**Comment by stursby** [comment]
Hmmmm, XO was complaining about a bunch of the imports after switching to default rules.

**Comment by sindresorhus** [comment]
Sounds like a weird setup. The common way to do this is to use webpack which has support for exactly what you're doing. `eslint-plugin-import` should then just handle it as long as you specify the `webpack` resolver setting: https://github.com/benmosher/eslint-plugin-import#importresolver

Alternatively, you could [ignore a set folder](https://github.com/benmosher/eslint-plugin-import#importignore) or just disable the rule.

**Comment by matheuss** [comment]
It's weird but I don't want to use webpack 😔 I think I'll just refactor everything to have `app/dist` organized in the same way that `app/src` is.

The "system" I implemented is 💯 for me but it requires some weird knowledge before hand to work with it – you need to understand what the `gulpfile` is doing – and nobody wants that 😛 Thank you both for the feedback @stursby @sindresorhus 🙌

**Comment by matheuss** [comment]
https://github.com/wulkano/kap/commit/ce2b5f3365bfe70656a2d64da3f00291a90ba23c ✅

**Comment by satriashop** [comment]
what a nice plugin for wordpress?

**Comment by CodeTheory** [comment]
@satriashop Sorry? There's nothing to do with wordpress here. 😛

**Comment by FezVrasta** [comment]
About Webpack, you may consider Rollup if the overhead of webpack is a major concern.

**Comment by CodeTheory** [comment]
I think he changed his mind on webpack 😛  https://github.com/wulkano/kap/blob/feature/a-whole-new-world/webpack.config.js

**Comment by FezVrasta** [comment]
Oh nice.

**Comment by sindresorhus** [comment]
Closing as this is no longer relevant.
