### ISSUE TITLE
README (and thus, front page) links to old version of Kap

### ISSUE THREAD

**Issue by robcresswell** [wulkano/kap#465]
The README seems to link to Kap-2.0.0 when I hit the download link; I'd update this to a more recent version, but its hidden behind some kind of shortcut (no idea what serves it).

It could probably be just a link to `https://github.com/wulkano/kap/releases/latest`

**Comment by albinekb** [comment]
This is fixed 👍 Thanks for reporting.

**Comment by albinekb** [comment]
Sorry, the readme isn't updated yet, the website link is.
