### ISSUE TITLE
Add option to enable lossy compression for gifs with gifsicle

### ISSUE THREAD

**Issue by albinekb** [wulkano/kap#468]
Add an option to use https://github.com/imagemin/imagemin-gifsicle for lossless compression for GIFs, toggle in preferences: 

**Enable GIF compression**
Lossless :radio_button:
Lossy :radio_button:

Defaults to lossless.

**Comment by skllcrn** [comment]
Updated the original issue description to specify the lossless option.

**Comment by skllcrn** [comment]
Just realised this is a duplicate of #117
