### ISSUE TITLE
Why did you have to disable automatic updates

### ISSUE THREAD

**Issue by zeke** [wulkano/kap#47]
From the [newsletter](http://getkap.us14.list-manage.com/subscribe?u=318c21d4f80a3b46f22ad6ddd&id=f219da06bd):

> We had to disable automatic updates for the beta

Why? Just curious.

**Comment by matheuss** [comment]
@zeke to be really honest, I don't now why I disabled it 😛 It was 4 am and we're excited to ship it and I thought that it was better to disable it. For some reason, I didn't want people to replace their current `Kap.app` with the beta one, so I thought it was better to disable it and say `you'll have to download the final version again when it's out` ¯\_(ツ)_/¯

We'll release the `0.3.0` tomorrow and we'll make sure to let you know! 😄 🙌

**Comment by zeke** [comment]
Cool. Just wanted to make sure it wasn't something upstream.

**Comment by matheuss** [comment]
Thanks for your concern ❤️
