### ISSUE TITLE
Error in plugin kap-now

### ISSUE THREAD

**Issue by williamli** [wulkano/kap#470]
**Platform:** MacOS 10.13.4
**Kap Version:** Version 2.1.2 (2.1.2.777)

### Steps to reproduce
Share files using kap-now, API keys already included.

### Current behaviour
Error in plugin kap-now

> Error: Response code 400 (Bad Request)
>     at stream.catch.then.data (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/got/index.js:341:13)
>     at <anonymous>
>     at process._tickDomainCallback (internal/process/next_tick.js:135:7)

![screen shot 2018-05-24 at 16 42 16](https://user-images.githubusercontent.com/179761/40474559-f13a8174-5f71-11e8-907c-96acc73bad9c.png)

### Expected behaviour
upload to be successful

### Workaround
nil

**Comment by sindresorhus** [comment]
// @lucaperret

**Comment by lucaperret** [comment]
Hi @williamli, is your token set in the kap-now.json file ?

**Comment by skllcrn** [comment]
I'm going to let you finish... 

![screen_shot_2009-09-15_at_8 57 03_am](https://user-images.githubusercontent.com/8440026/40480677-822b9132-5f4f-11e8-8930-846c240b3329.png)

...but we're working on making it much easier to use configurable plugins. Also, it's best if you post issues specific to a plugin in its repo https://github.com/lucaperret/kap-now
