### ISSUE TITLE
application opens in dock (not in menu bar) unexpectedly when connect/disconnect to the external Monitor

### ISSUE THREAD

**Issue by star114** [wulkano/kap#472]
**Platform:** Darwin 000-MBP.dhcp.icnl.sap.corp 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
**Kap Version:** 2.1.2.777
### Steps to reproduce
1. start kap.
2. connect/disconnect mac to the external monitors
### Current behaviour
kap runs in the dock, not the menu bar and opens the new window separated to the menu bar.
### Expected behaviour
anything happens
### Workaround
?

**Comment by star114** [comment]
Thanks, @albinekb 
BTW, do you have any plan to fix it?

**Comment by albinekb** [comment]
I dont have access to external screen so can’t reproduce, there is however an open PR that I think addresses this, were also rewriting Kap completely for 3.0 with a different approach to cropping, so this will eventually get resolved

**Comment by star114** [comment]
Thank you!

**Comment by star114** [comment]
The problem is gone after mac os system upgrade to 10.13.5.
Can I close this bug or keep it?

**Comment by skllcrn** [comment]
Thanks for the update @star114, it's an intermittent issue so it's likely still there even though you're not able to consistently recreate it after updating macOS. I'll close this in favour of the other related issues for now.
