### ISSUE TITLE
Error: Cannot call function 'set' on missing remote object 46

### ISSUE THREAD

**Issue by stephenmathieson** [wulkano/kap#473]
**Platform:** Darwin Stephens-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Kap Version:** 2.1.2 (2.1.2.777)

### Steps to reproduce

1. Open Kap (fresh install)
2. Start setting up recording
3. Click+drag to expand the recording area

### Current behaviour

An uncaught error is raised:

<img width="459" alt="screen shot 2018-05-31 at 9 37 41 am" src="https://user-images.githubusercontent.com/571265/40785905-ba9261be-64b7-11e8-8651-305ea59c7633.png">

Copied/plaintext:

```
Unhandled Error
Error: Cannot call function 'set' on missing remote object 46
Error: Cannot call function 'set' on missing remote object 46
    at setSelectedRatio (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:269:22)
    at EventEmitter._electron.ipcRenderer.on (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:481:7)
```

### Expected behaviour

No error is raised.

### Workaround

I tried it again and everything worked as expected. This seems to be pretty edge-casey and intermittent.

**Comment by skllcrn** [comment]
Sentry issue: [KAP-2D](https://sentry.io/wulkano-l0/kap/issues/446912938/)

**Comment by stephenmathieson** [comment]
I was trying to record on a single display 15-inch, 2017 MacBook Pro. I had all windows (other than what I was trying to record) minimized, and was cropping to fit that window.

Sorry I can't really provide any more information, as I don't think there really is anymore 🤷‍♀️ 

FWIW I'm unable to reproduce this having tried again a few times. My guess is there's some sort of race condition somewhere and I "too quickly" tried to crop, but I honestly have no idea.

**Comment by sindresorhus** [comment]
We have now rewritten Kap to be more stable. You can try out [the beta](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.2).

I'm going to close this as it was never reproducible and is probably not an issue in the new beta.
