### ISSUE TITLE
Error: ffmpeg exited with code: 1

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#474]
**macOS 10.13.5**
**Kap Version 2.2.0**

Throws an error when attempting to export to WebM, no way to consistently reproduce the issue. My best guess is that it has to do with width and height conversion, that was the only change I made before exporting. 

<details>
  <summary>Error: ffmpeg exited with code: 1</summary>
<code>ffmpeg version N-87313-g73bf0f4-tessus Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --disable-ffplay
  libavutil      55. 75.100 / 55. 75.100
  libavcodec     57.106.101 / 57.106.101
  libavformat    57. 82.100 / 57. 82.100
  libavdevice    57.  8.101 / 57.  8.101
  libavfilter     6.105.100 /  6.105.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///private/var/folders/wm/hvpr1m2n7rs93lfq0pr5zcw00000gn/T/f7c629dc5088370cf783914af0195a79.mp4':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2018-06-06T19:50:25.000000Z
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: MacBookPro11,4
    com.apple.quicktime.software: Mac OS X 10.13.5 (17F77)
    com.apple.quicktime.creationdate: 2018-06-06T21:50:23+0200
  Duration: 00:00:18.17, start: 0.000000, bitrate: 2896 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1024x768 [SAR 1:1 DAR 4:3], 2569 kb/s, 30 fps, 30 tbr, 6k tbn, 12k tbc (default)
    Metadata:
      creation_time   : 2018-06-06T19:50:25.000000Z
      handler_name    : Core Media Data Handler
      encoder         : H.264
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2018-06-06T19:50:25.000000Z
      handler_name    : Core Media Data Handler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> vp9 (libvpx-vp9))
  Stream #0:1 -> #0:1 (aac (native) -> vorbis (native))
Press [q] to stop, [?] for help
[vorbis @ 0x7fd191006000] Current FFmpeg Vorbis encoder only supports 2 channels.
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
    at ChildProcess.converter.on.code (/Applications/Kap Beta.app/Contents/Resources/app.asar/dist/scripts/convert.js:83:16)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)</code>
</details>

**Comment by sindresorhus** [comment]
@skllcrn Can you reproduce this with the latest beta?

**Comment by skllcrn** [comment]
I haven't seen this at all in the last couple of builds! I'll close for now, hopefully it's a goner.

**Comment by pivic** [comment]
I've just seen this on Kap v2.2.0.880, and I'm running macOS Mojave (v10.14.5):

> Error: ffmpeg exited with code: 1
> 
> ffmpeg version N-87313-g73bf0f4-tessus Copyright (c) 2000-2017 the FFmpeg developers
>   built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
>   configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --disable-ffplay
>   libavutil      55. 75.100 / 55. 75.100
>   libavcodec     57.106.101 / 57.106.101
>   libavformat    57. 82.100 / 57. 82.100
>   libavdevice    57.  8.101 / 57.  8.101
>   libavfilter     6.105.100 /  6.105.100
>   libswscale      4.  7.103 /  4.  7.103
>   libswresample   2.  8.100 /  2.  8.100
>   libpostproc    54.  6.100 / 54.  6.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:///private/var/folders/4r/34s_3l791gbbxnqd6v8qkx6w0000gn/T/8490d242c07b8c764f8f4bc1766ed0d6.mp4':
>   Metadata:
>     major_brand     : qt  
>     minor_version   : 0
>     compatible_brands: qt  
>     creation_time   : 2019-06-04T08:37:23.000000Z
>     com.apple.quicktime.make: Apple
>     com.apple.quicktime.model: MacBookPro15,2
>     com.apple.quicktime.software: Mac OS X 10.14.5 (18F132)
>     com.apple.quicktime.creationdate: 2019-06-04T10:37:20+0200
>   Duration: 00:27:39.13, start: 0.000000, bitrate: 3068 kb/s
>     Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 2880x1642 [SAR 1:1 DAR 1440:821], 2865 kb/s, 59.99 fps, 60 tbr, 6k tbn, 12k tbc (default)
>     Metadata:
>       creation_time   : 2019-06-04T08:37:23.000000Z
>       handler_name    : Core Media Data Handler
>       encoder         : H.264
>     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, mono, fltp, 129 kb/s (default)
>     Metadata:
>       creation_time   : 2019-06-04T08:37:23.000000Z
>       handler_name    : Core Media Data Handler
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (native) -> vp9 (libvpx-vp9))
>   Stream #0:1 -> #0:1 (aac (native) -> vorbis (native))
> Press [q] to stop, [?] for help
> [vorbis @ 0x7fd93b802a00] Current FFmpeg Vorbis encoder only supports 2 channels.
> Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
> Conversion failed!
> 
>     at ChildProcess.converter.on.code (/Applications/Kap.app/Contents/Resources/app.asar/dist/scripts/convert.js:83:16)
>     at emitTwo (events.js:111:20)
>     at ChildProcess.emit (events.js:194:7)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
