### ISSUE TITLE
Allow Kap to be running without being moved to the Applications folder

### ISSUE THREAD

**Issue by Mosrod** [wulkano/kap#475]
Platform: MacOS V10.12.6 Sierra 2015 Macbook Air
Step to reproduce :  Download zip file and run the .app file.
Current behaviour: Alerts that program needs to be in applications folder and closes the program
Expected behaviour : Should alert you once, and not close the program
Workaround: Use an older version of Kap.

I run a school issued computer, so I cannot install .dmg applications, and I am not administrator, so I cannot move it to the Applications folder. It is a very useful application, and I hope you can make this available as a portable version or fix this issue.

**Comment by skllcrn** [comment]
We did this to work around an issue we were having, but hoping we can make it possible to run Kap without moving it to your Applications folder for our next major release (cc: @sindresorhus). Best of luck with your studies!

**Comment by Mosrod** [comment]
Thanks so much :)

**Comment by oliveratgithub** [comment]
It works for me having it in ~/Applications

**Comment by hedin-hiervard** [comment]
I can't make it work neither in /Applications nor in ~/Applications
All I get is: "Please move Kap to your Applications folder to ensure it runs correctly."

**Comment by sindresorhus** [comment]
Closing for lack of response. This is most likely fixed in v3.
