### ISSUE TITLE
Kap i18n

### ISSUE THREAD

**Issue by ForeverOpp** [wulkano/kap#476]
I want to translate Kap into Chinese because it is welcomed in China but there is no official Chinese version provided. And I'm not familiar with JavaScript, CSS or HTML, so could you provide a text list which people can use to translate? Thx.

**macOS Version: 10.13.5**
**Kap Version: 2.2.0.880**

**Comment by skllcrn** [comment]
Changed the title to make this an issue for i18n in general. In addition to Chinese we know Kap is popular in countries that speak Japanese, Portuguese, Spanish, German, Dutch and French. With proper localisation we should also separate between regional variants of English.

**Comment by ForeverOpp** [comment]
So do you have some good ideas for this?

**Comment by skllcrn** [comment]
No good ideas yet, @ForeverOpp! It creates a lot of overhead and the translations will need additional work for every new feature or tweak. It adds another layer on top of our ongoing maintenance work that we quite frankly don't have the resources for. Luckily we have very little text, and where we do have text we can get even better at pairing it with icons so people can navigate more visually.

**Comment by ForeverOpp** [comment]
OK. I'm waiting for it delightfully.

**Comment by skllcrn** [comment]
Unfortunately, I don't advise holding your breath. We want to be honest and say that we simply do not have the resources to pursue this improvement.

**Comment by KovalevArtem** [comment]
For example, you can use the service for translations Weblate, or any other service. It is completely free for open source projects.
I know 2 people who are willing to help with the setup...

**Comment by ForeverOpp** [comment]
Wow, Kap has 15k stars now! Congratulations! But seems like the i18n feature will not be support forever. : (
