### ISSUE TITLE
„Check for updates…“ option has no feedback

### ISSUE THREAD

**Issue by oliveratgithub** [wulkano/kap#481]
Clicking on „Check for updates...“ contextual menu of the Kap menu icon, checks if a new version is available or not.

I think, if it doesn’t find a new version, the menu item is only grayed out/disabled.

It should send a user feedback in any case - whether a new version is available or also if not. It‘s confusing triggering that contextual menu manually and not receiving any user feedback on the action‘s result.

**Comment by sindresorhus** [comment]
I think we should remove the button altogether and just report when an update is available automatically. (Except for when recording, of course)

**Comment by skllcrn** [comment]
Personally I really like having the option to check for updates, it could be especially useful if we can tie it to force checking plugin updates too?

**Comment by sindresorhus** [comment]
What’s the point if it happens automatically? Plugin updates are already 100% automatic.

**Comment by oliveratgithub** [comment]
I have never noticed that the app updated itself - even the last version I downloaded manually because it clearly wasn’t up to date anymore (which could have been an issue with the version I was using so long, of course).

However, even for auto-updates, as a user, I would love some information that an update has happened. Otherwise I will start thinking at one point, that I‘d better check online if I‘m really using the most recent version and not missing out... that’s why I actually like having the „Checking for update...“ option there.

But it is not really necessary after all, as long as there would be some kind of notice easily showing/ensuring me, that Kap is up to date.

**Comment by timicode** [comment]
I believe this may be a separate issue as I am able to receive user feedback on "Check for Updates..."

<img width="642" alt="issue481" src="https://user-images.githubusercontent.com/39888639/41501157-b8932b8e-716c-11e8-9607-b0dedd8e3352.png">
