### ISSUE TITLE
Opaque black overlay over the entire screen

### ISSUE THREAD

**Issue by Scglia** [wulkano/kap#482]
**macOS Version:** 10.13.4
**Kap Version:** Next

#### Steps to reproduce
Open Kap on a 2011 Macbook Pro and click on the Kap icon in the menu bar.

#### Current behaviour
There's an opaque black overlay over the entire screen.
See: https://drive.google.com/file/d/1splW5MxbyAMPJrxMposxrCIvSWONhqMK/view?usp=sharing

#### Workaround
I think it might be happening because WebGL is disabled in Chromium/Electron for Intel HD3000 chips.
(https://bugs.chromium.org/p/chromium/issues/detail?id=644091)
I'll try to investigate it more.

Possible workaround: https://developer.mozilla.org/en-US/docs/Learn/WebGL/By_example/Detect_WebGL

**Comment by skllcrn** [comment]
Hey mate, does this happen when running Kap 2.0 or later on the same hardware? Not necessarily for the crop tool, but for example in the Editor where there's a transparent titlebar, or near the bottom of the same window where the background has `vibrancy`? 

We could see if we're able to recreate by running the app with [`app.disableHardwareAcceleration()`](https://github.com/electron/electron/blob/master/docs/api/app.md#appdisablehardwareacceleration)

**Comment by Scglia** [comment]
![image](https://user-images.githubusercontent.com/6373724/41588328-b3df878a-73b1-11e8-9e2c-25458245845f.png)

Vibrancy looks like it's working fine 👍

**Comment by brennomaeji** [comment]
**macOS version:**    Big Sur (11)
Kap version: Version 3.5.4 (3.5.4.1810)

I have a different kind of overlay on a part of the screen, with some transparency. I could not find how to remove it:

https://user-images.githubusercontent.com/80332150/156736735-d9b9fe9b-87a7-48ac-a28c-377002eb50c3.mp4

Is this issue related to this problem?
