### ISSUE TITLE
Dropbox integration has reached limit

### ISSUE THREAD

**Issue by m2mathew** [wulkano/kap#486]
**macOS Version:** 10.13.5 build 17F77
**Kap Version:** lateset

#### Steps to reproduce

1. Make a screencap
2. Attempt to upload to Dropbox for first time
3. Enter Dropbox credentials as requested
4. The screen below appears and says that Kap has reached its limit

#### Current behaviour

Unable to connect to Dropbox to store .gif files there.

#### Expected behaviour

Should be able to connect to Dropbox. 🤓 

#### Workaround

File issue and 🙏 for help.

![image](https://user-images.githubusercontent.com/11624407/42611239-c3fd4bd8-855a-11e8-90ef-6c8abbab6432.png)

**Comment by skllcrn** [comment]
Moving this issue to the `kap-dropbox` repository https://github.com/karaggeorge/kap-dropbox/issues/1
