### ISSUE TITLE
Why this app opens 0.0.0.0:8080?

### ISSUE THREAD

**Issue by komarnicki** [wulkano/kap#487]
https://stackoverflow.com/questions/51391841/what-is-running-on-my-0-0-0-08080-if-vagrant-and-docker-are-completely-down

This is very odd. I had to remove Kap from automatically starting with macOS.

**Comment by skllcrn** [comment]
Not able to reproduce @komarnicki, could you please provide more details about your environment and the following: 

**macOS Version:**
**Kap Version:**

**Comment by komarnicki** [comment]
Hi @skllcrn,

**macOS High Sierra** 10.13.5 (17F77
**Kap** Version 2.2.0 (2.2.0.880)

**Comment by skllcrn** [comment]
Could you see if you're able to recreate the issue using [`master`](https://kap-artifacts.now.sh/master) @komarnicki?

**Comment by sindresorhus** [comment]
Closing this for lack of response and we never managed to reproduce this.

Try out [the beta](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.2) and see if you still can reproduce this issue, and let us know if you do.
