### ISSUE TITLE
'Allow analytics' always re-enables itself

### ISSUE THREAD

**Issue by davidjb** [wulkano/kap#488]
**macOS Version:**
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
**Kap Version:** Version 2.2.0 (2.2.0.880) 

#### Steps to reproduce
1. Open Kap
1. Open Preferences
1. Disable 'Allow analytics'
1. Close Preferences
1. Open Preference
1. Note that 'Allow analytics' is now _re-enabled_
#### Current behaviour
'Allow analytics' preference either never saves or re-enables itself without warning.
#### Expected behaviour
'Allow analytics' preference should respect my choices.
#### Workaround
Firewall Kap off from hitting Google Analytics.

**Comment by skllcrn** [comment]
Do you have more than one instance of Kap @davidjb? The only thing I can think of that would cause this is a corrupt settings file or a conflict between multiple of them. I suggest uninstalling Kap and making sure the contents of `~/Library/Application Support/Kap` is deleted before reinstalling.

**Comment by davidjb** [comment]
I just installed Kap for the very first time on this machine today.  Fresh new install from `brew cask` which comes from the 2.2.0 dmg here on GH.  I've uninstalled and `rm -rf`'d the application support directory, and reinstalled and same experience. 

Are there debug logs or a debug mode I can invoke to get more info?

**Comment by skllcrn** [comment]
Can you go to `~/Library/Application Support/Kap` and grab the config.json file from that folder and share it? 

`cat ~/Library/Application Support/Kap/config.json | pbcopy`

**Comment by skllcrn** [comment]
That explains it, for some reason Kap isn't generating a `config.json` file for you. I have a feeling it might be due to an issue with permissions.

**Comment by davidjb** [comment]
The `Kap` directory has 755 permissions and is owned by my user and my user has been writing to those other files from within Kap so I'm not sure.  Let me know if there's something you want me to check or test specifically.

**Comment by skllcrn** [comment]
https://github.com/wulkano/kap/issues/489#issuecomment-405942430

> Could you remove it again and try this build https://kap-artifacts.now.sh/next

**Comment by davidjb** [comment]
Yep, that's now got a `config.json` rather than a `Settings` file in the `Kap/` directory.  The `allowAnalytics` key changes correctly on modifying the setting in the GUI. (Version 3.0.0 / 3.0.0.900)

**Comment by skllcrn** [comment]
Awesome, that should solve #489 for you too. You can [download and install Kap 2.2.0](https://github.com/wulkano/kap/releases/download/v2.2.0/kap-2.2.0-mac.zip) now, it will share the plugins and `config.json` with your current installation.

**Comment by davidjb** [comment]
Doesn't work unfortunately; running 2.2.0 leads to `Settings` being recreated, with its original settings.  In that file is a bundle of JSON with the same object as what's in `config.json`.  So the two versions seem to use different config filenames.

Anyway, I'm fine with using v3 if it's stable enough.  Otherwise, modifying the `Settings` file seemed to workaround the problem for now...

**Comment by skllcrn** [comment]
Bummer. Since we haven't heard about this issue in the past and things seem to work with 3.0 (which should be stable enough, just [keep an eye out for the beta](http://eepurl.com/ch90_1) so you remember to update) I'm going to close this issue for now. Again, thank you for the issue and quick replies, glad we could find a workaround.
