### ISSUE TITLE
Audio input: undefined

### ISSUE THREAD

**Issue by harryfear** [wulkano/kap#490]
macOS Version:        10.13.5 
Kap Version:          2.2.0 (2.2.0.880)

#### Steps to reproduce

Open Preferences, intend to select audio input. Doesn't reflect system audio inputs. Instead tens of 'undefined' inputs.

![Screenshot](https://my.mixtape.moe/rxeopa.png)

**Comment by skllcrn** [comment]
Closing in favour of #384
