### ISSUE TITLE
Mouse cursor and click settings not persisting after first recording

### ISSUE THREAD

**Issue by cosmin-marginean** [wulkano/kap#495]
**macOS Version**: Mac OS X, 10.13.6, 17G65
**Kap Version**: 2.2.0 (2.2.0.880)

#### Steps to reproduce
* Start Kap
* Enable (or disable and then re-enable) "Show mouse cursor" and "Highlight clicks" in preferences.
* Record screen (1)
* Export (mp4/gif/etc) and then close the window
* Record screen (2)

#### Current behaviour
* Record screen (1) contains the mouse clicks, Record screen (2) doesn't contain mouse clicks anymore
#### Expected behaviour
* Once these preferences have been enabled, all videos should record the mouse clicks.
#### Workaround
* Toggle "Show mouse cursor" / "Highlight clicks" off and then on again

**Comment by skllcrn** [comment]
I can't recreate this exact behaviour, but we are having some issues with settings not persisting. Have you used other version of Kap in the past, or is this a fresh install on a new system @cosmin-marginean? 

Can you go to `~/Library/Application Support/Kap` and grab the `config.json` file from that folder and share it here?

`cat ~/Library/Application Support/Kap/config.json | pbcopy`

Once you've done that you can attempt quit Kap, delete the file mentioned above and then try running the app again.

**Comment by cosmin-marginean** [comment]
This is a version I've been running for a while now but only noticed this behaviour today.
Also, I don't seem to have this file at all:
```
cosmin@imac ~ $ ll ~/Library/Application\ Support/Kap/
total 24
drwxr-xr-x    7 cosmin  staff   224 16 Aug 11:01 .
drwx------+ 108 cosmin  staff  3456 16 Aug 09:37 ..
drwx------    7 cosmin  staff   224  8 Feb  2018 GPUCache
-rw-------    1 cosmin  staff    69  8 Feb  2018 Preferences
-rw-r--r--    1 cosmin  staff   364 16 Aug 11:01 Settings
drwxr-xr-x    5 cosmin  staff   160 16 Aug 09:22 plugins
-rw-r--r--    1 cosmin  staff     2 16 Aug 09:37 usage-history.json
```

**Comment by skllcrn** [comment]
Ah, I forget. I mean't the Preferences and Settings file, you can attempt to delete those and run Kap again! If that doesn't work, can you please try using the [`master`](https://kap-artifacts.now.sh/master) build?

**Comment by cosmin-marginean** [comment]
Deleted, restarted, doesn't solve the problem.
However, I did manage to get more detail on this: After a restart, the Highlight clicks is turned off, even if it was turned on before.

Master seems to persist the setting ok, but has a different problem - doesn't _always_ capture clicks:
![kapture 2018-08-16 at 12 40 30](https://user-images.githubusercontent.com/2995576/44206440-af48b200-a151-11e8-8be0-d467e1957192.gif)

**Comment by skllcrn** [comment]
Good to know, I'm glad it's partially solved on `master` though. The highlight clicks not always showing is a separate issue that I can't recreate. You might want to create a new one for that referencing this issue, and I'll close this one. 

Related issues for future reference: #231, #491, #488

**Comment by cosmin-marginean** [comment]
Great, thanks!

**Comment by multidynamic** [comment]
FYI I noticed the same behavior:  _Show cursor_ toggle would not be persisted and even if in `on` state I could not flip highlight toggle (I saw 🚫)  This appears to be fixed in `master`
