### ISSUE TITLE
Cannot launch Kap

### ISSUE THREAD

**Issue by maximskripnik** [wulkano/kap#498]
**macOS Version:**
ProductVersion: 10.13.6
BuildVersion: 17G65

**Kap Version:**
2.2.0.880

#### Steps to reproduce

1. `brew cask install kap`
2. Open Kap from Applications folder

#### Current behaviour
Only this shows up:
![screen shot 2018-09-05 at 10 57 38](https://user-images.githubusercontent.com/11578334/45070269-addc2b00-b0fa-11e8-81ff-ca98595bb410.png)
After i click **OK**, application just quits
#### Expected behaviour
The error does not show up and application can be used
#### Workaround
Could not find any

It is really in the Applications folder:
![screen shot 2018-09-05 at 11 10 21](https://user-images.githubusercontent.com/11578334/45070617-550d9200-b0fc-11e8-8ec7-c07047c3af9d.png)

**Comment by sindresorhus** [comment]
This is probably a bug in our Application directory detection. In Kap v3 (in master) we will use an Electron API for this, so it's likely fixed already there.

Is Kap in `/Applications` or `~/Applications`?

**Comment by maximskripnik** [comment]
In `/Applications`:
```bash
~/Applications$ ls /Applications | grep Kap
Kap.app
~/Applications$ ls ~/Applications | grep Kap
~/Applications$
```

**Comment by skllcrn** [comment]
Were you able to launch Kap after installing it via GitHub or the website @maximskripnik?

**Comment by maximskripnik** [comment]
@skllcrn If I download it from the website and manually move to Applications folder from .zip archive, it is launched fine
