### ISSUE TITLE
Lag when resizing the cropping area

### ISSUE THREAD

**Issue by CodeTheory** [wulkano/kap#5]
"There is also a little bit o' lag when resizing the clip area"

**Comment by doot0** [comment]
Not sure if I was imagining it, but after https://github.com/wulkano/kap/pull/16 resize performance seems slightly better. I did very briefly profile before/after with what was probably a negligible improvement.

**Comment by CodeTheory** [comment]
@doot0 I'm testing the PR now. I'll see if I can see the same.

**Comment by CodeTheory** [comment]
@doot0 @matheuss @skllcrn this no longer happens to me. Can you test?

**Comment by skllcrn** [comment]
I haven't had this issue myself!

**Comment by doot0** [comment]
Seems acceptable to me, though if you _really_ go mad with resizing it you get a bit of jank.

**Comment by matheuss** [comment]
For now there's nothing we can do about it since we're resizing a macOS window; If and when we change the *cropper* window implementation, we might be able to optimize it 😄

**Comment by CodeTheory** [comment]
Okay, closing for now!
