### ISSUE TITLE
Plugin notifications and alerts

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#501]
Via #500 (https://github.com/wulkano/kap/pull/500#issuecomment-421945971) 

> When attempting to export using a Plugin with a missing or incorrect configuration, show a dialog with options to cancel or open the configuration in question: 
> 
> ![Alert](https://user-images.githubusercontent.com/8440026/45614047-78bfc900-ba68-11e8-940c-115ab775dcdf.png)
> 
> Once a Plugin has been installed, send a notification (banner) to indicate that it's ready for use. In the case of a Plugin that requires configuration there's an action associated with the notification (alert) and it does not dismiss automatically: 
> 
> ![Notifications](https://user-images.githubusercontent.com/8440026/45614283-4ebad680-ba69-11e8-83d0-20e0b8061bb3.png)

**Comment by karaggeorge** [comment]
Additional notification when there's an issue installing a plugin:

<img width="367" alt="screenshot 2018-09-19 16 36 43" src="https://user-images.githubusercontent.com/8822835/45779895-4e1d6e00-bc2a-11e8-86ee-4c75297fe12e.png">
