### ISSUE TITLE
The plugin discover tab needs an empty state

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#505]
When you have installed all the plugins, this is what you see:

<img width="592" alt="screen shot 2018-09-20 at 12 08 19" src="https://user-images.githubusercontent.com/170270/45797074-e3257300-bccd-11e8-96a2-21c225a9b30e.png">

We could have something fun, like:

> Wow. You sure like plugins.

**Comment by skllcrn** [comment]
I heard you like plugins 

![image](https://user-images.githubusercontent.com/8440026/45797847-d2fa9d00-bca7-11e8-97a3-5ebc7e9801fb.png)

**Comment by sindresorhus** [comment]
![image](https://user-images.githubusercontent.com/170270/45798113-bde73380-bcd2-11e8-872b-7c3763f30116.png)
