### ISSUE TITLE
Let plugins specify general config page description

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#506]
A description that gives context to the config, like links to API docs, etc.

See: https://github.com/wulkano/kap/pull/504#issuecomment-423228417

**Comment by skllcrn** [comment]
Can this be included in the bottom menu within the Plugin config modal?

**Comment by sindresorhus** [comment]
@skllcrn I think it should be at the top. The point is to use the space to have general instructions that you need to fill out the fields.
