### ISSUE TITLE
Touch Bar support

### ISSUE THREAD

**Issue by skllcrn** [wulkano/Kap#514]
Touch Bar controls (Make sure we take https://github.com/wulkano/kap/commit/621f1cabc6ce859923a6c07536241d781454726d into account)

Do people want this, and if so; are there other improvements needed on our initial implementation #255? 

If you don't have a device with Touch Bar you can use https://github.com/sindresorhus/touch-bar-simulator

**Comment by albinekb** [comment]
YEEES I WANT. I Liked how it works in 2.0

**Comment by LitoMore** [comment]
![image](https://user-images.githubusercontent.com/8186898/51657722-b917f080-1fe0-11e9-9c6a-10d83777386d.png)

I think we could add these options to the Touch Bar.

**Comment by skllcrn** [comment]
How do you see the inputs working @LitoMore? I'm not sure the size input would make sense, but the FPS could be a slider?

**Comment by onordbo** [comment]
*Reviving this issue with an interactive idea:* Draggable trimming sliders for in and out points on a recorded video.

cc @skllcrn

**Comment by LitoMore** [comment]
@skllcrn Sorry for the late response, let me draw some prototype for my idea. Will post out later.

**Comment by skllcrn** [comment]
No worries, and thank you @LitoMore!

**Comment by skllcrn** [comment]
We'd love to do some incremental improvements for our next update, but it would still be really useful to see your concepts or prototypes @LitoMore

**Comment by sindresorhus** [comment]
Closing as the Touch Bar is being phased out.
