### ISSUE TITLE
Rewrite the integration with the menubar

### ISSUE THREAD

**Issue by matheuss** [wulkano/kap#53]
The current code to deal with the tray icon/menubar is very confusing and complex: we're relying on (a fork of) the `menubar` module and we're doing a lot of things on our on. There's a lot of confusing and duplicated code.

**Comment by skllcrn** [comment]
Upcoming as part of the 2.0.0 milestone! Hopefully this can close or progress #1, #3, #4, #7, #44 and #112.

**Comment by skllcrn** [comment]
Suggest dealing with #162 in conjunction with this issue.

**Comment by skllcrn** [comment]
#472

**Comment by skllcrn** [comment]
Kap no longer attaches to the menubar (#494 and #223)
