### ISSUE TITLE
Shortcut should stop recording

### ISSUE THREAD

**Issue by pacocoursey** [wulkano/kap#533]
**macOS Version:** 10.13.6
**Kap Version:** 3.0.0-beta.1.1006

#### Steps to reproduce
- With Kap open, press the keyboard shortcut to "Trigger Kap"
- Click record and record a short video
- Press the keyboard shortcut again while still recording

#### Current behaviour
- Pressing the shortcut while recording seemingly starts a new recording, but this new recording is never viewable or exportable. (seems like a bug)

#### Expected behaviour
- Pressing the shortcut while recording should stop the recording.

The major advantage of a keybind in my mind is the ability to start and stop a recording without needing to click the menu bar. In addition, https://github.com/wulkano/kap/issues/83#issuecomment-266144128 lists <kbd>Space</kbd> and <kbd>Enter</kbd> as ways to start the recording from the editing screen, but this behavior is not present in the beta.

If #263 aims to allow Kap to record multiple areas at once, then you can probably disregard this issue and re-evaluate the behavior of the shortcut.

**Comment by skllcrn** [comment]
Thank you for the issue @pacocoursey, closing in favour of #625
