### ISSUE TITLE
Cannot paste text to the config input field

### ISSUE THREAD

**Issue by LitoMore** [wulkano/kap#534]
**macOS Version:** macOS 10.14
**Kap Version:** 3.0.0-beta.1

#### Steps to reproduce

1. Open Preference
2. Install `fanfou` plugin from Discover
3. Enter the config view
4. Trying copy something to the clipboard
5. Paste to the config input field

#### Current behavior

Cannot paste text to the input field

#### Expected behavior

Could paste text to the input field

#### Workaround

Null

**Comment by LitoMore** [comment]
Also, I can't use the <kbd>Command</kbd> + <kbd>a</kbd> for select all.

**Comment by bringking** [comment]
This does indeed seem fixed in the master branch
