### ISSUE TITLE
Cannot get the latest plugin version

### ISSUE THREAD

**Issue by LitoMore** [wulkano/kap#535]
**macOS Version:** macOS 10.14
**Kap Version:** 3.0.0-beta.1

#### Steps to reproduce

1. Open Preferences, then go to Discover view
2. Find `fanfou` plugin
3. Look at the version number

#### Current behavior

The version is `fanfou 0.2.0`

#### Expected behavior

This version should be the latest version `fanfou 0.3.0`

#### Workaround

Null

**Comment by LitoMore** [comment]
After a while, the version number updated.

BTW, I'm curious that when will Kap update the list, and how can I update the list manually?

**Comment by skllcrn** [comment]
Kap checks for updates and installs them automatically, It'll check on launch and around every hour after that!
