### ISSUE TITLE
Clicking an item in the Exports window should reveal the file in Finder

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#537]
That's what I expected to happen. It's weird that it currently has a hover effect, but nothing happens when I click it.

**Comment by skllcrn** [comment]
The challenge here is that if a file was exported using a plugin we don't necessarily have the destination/directory for it, we could however reveal the original cached recording.

**Comment by sindresorhus** [comment]
We do have the directory for it. Plugins just get a file path to the converted file. We can open the directory for that path.
