### ISSUE TITLE
Add a way to open export window

### ISSUE THREAD

**Issue by albinekb** [wulkano/kap#543]
**Kap version:** 3 Beta 1

#### Current behaviour
Can't open export window after closing it

#### Expected behaviour
I can open up the export window in the menu bar or cropper controls:
![image](https://user-images.githubusercontent.com/5027156/46146318-be4b7580-c262-11e8-96b7-08db5d205b4a.png)

#### Workaround
Record & export another recording to get the export window to show

**Comment by sindresorhus** [comment]
If there's no history, the menu item should still show, but be disabled.
