### ISSUE TITLE
Open cropper view at app launch

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#544]
I think it would be nice if Kap would show the cropper view at launch. I only have Kap open when I actually want to use it and this would make it quicker for me to start recording.

It should not however be opened if Kap was launched at system startup. We can detect this with `app.getLoginItemSettings`, which returns an object with `wasOpenedAtLogin`. 

https://electronjs.org/docs/api/app#appgetloginitemsettingsoptions-macos-windows

**Comment by skllcrn** [comment]
It's either showing the cropper at launch or some sort of hint that you need to draw the cropper, with the latter we make no assumptions about where and what size the cropper needs to be. 

If we do show a default cropper on launch we need to define an aspect ratio and size for it.

**Comment by karaggeorge** [comment]
@skllcrn 
I think this was about opening the cropper window (not drawing a cropper necessarily) when the app first launches

At least that's how I understand it

**Comment by albinekb** [comment]
I think having an option for this would be good. I launch Kap before I need to record, so it's ready when I need it. I would get mad if it just popped up when it loaded.

**Comment by sindresorhus** [comment]
Yes, this is only about opening the cropper view, not drawing a cropper rectangle.

**Comment by sindresorhus** [comment]
> I think having an option for this would be good. I launch Kap before I need to record, so it's ready when I need it. I would get mad if it just popped up when it loaded.

Sure, but I think it should default to showing the cropper view.
