### ISSUE TITLE
Open preferences hotkey does not work

### ISSUE THREAD

**Issue by thephw** [wulkano/kap#549]
**macOS version:**    darwin x64 17.7.0
**Kap version:**      3.0.0-beta.1

#### Steps to reproduce
1. Click Kap in the menubar and give it focus
2. Use the hotkey `CMD + ,` to Open Preferences

#### Current behavior

Nothing happens

#### Expected behavior

Preferences page opens

#### Workaround

Click `...` in the overlay and then select "Preferences..."

**Comment by sindresorhus** [comment]
The shortcut currently only works when the menu is open, but yes, it should work when the cropper view is open too. Also the editor view.
