### ISSUE TITLE
Can't save Kaptures

### ISSUE THREAD

**Issue by doot0** [wulkano/kap#55]
via Twitter: https://twitter.com/RauschenImWalde/status/788488883637985292

> [...] I like your KAP app very much, but I cannot save anything (v2.0/3.0) on macOS Sierra

**Comment by matheuss** [comment]
I believe this happens if you try to save a Kapture to a Volume that's not the `Macintosh HD` 😕

**Comment by doot0** [comment]
Reproducible?

**Comment by matheuss** [comment]
I can't reproduce since i don't have any external devices here 😛 But should be reproducible, you just need to record something and then try to save it to an external HD/SSD/pen drive

**Comment by doot0** [comment]
@matheuss Can reproduce on Sierra with an external disk. Save dialog allows you to click Save, but no file is written.

**Comment by doot0** [comment]
Update: can now save Kaptures to the external disk just fine. 😕

**Comment by radum** [comment]
Same problem here. Nothing gets saved anywhere I try.

![image](https://user-images.githubusercontent.com/46779/28912485-5bf519e4-782c-11e7-8564-678bb9068820.png)

**Comment by skllcrn** [comment]
I wonder if by any chance this could be related to denying Kap to access local servers? #130

**Comment by gugahoi** [comment]
Can reproduce here. I am trying to save to another HDD and nothing happens, just disappears into thin air. Kap version `1.0.1.170` and macOS Sierra `10.12.6`.
