### ISSUE TITLE
Bringing this to Windows or Linux?

### ISSUE THREAD

**Issue by ThatTonybo** [wulkano/kap#553]
Hi there! I've had some of my friends tell me about Kap, and it's pretty cool-

..but doesn't have neither Windows or Linux support, and for a person that at their best owns an old iMac G3 from a garage sale, it's sad.

My question, can we get Kap ported to Windows and possibly Linux?

Thanks!

**Comment by skllcrn** [comment]
Hey @ThatTonybo! You're free to fork and port Kap, here's a couple of issues to get you started: #456, #31
