### ISSUE TITLE
Config Settings

### ISSUE THREAD

**Issue by tylerreitz** [wulkano/kap#56]
It appears the configuration settings reset after each quit. Not sure if this is on the _to-do_ list but it's somewhat of a pain to set them each time (let alone remember to). Also, the recording frame is not remembering placement either. 

I'm on an older mac btw – Late 2011, Yosemite 10.10.3

**Comment by stursby** [comment]
Hey @tdreitz, #75 should fix this (not in master yet), however, we're trying to decide if the window position & size should reset on Quit. For now, we've decided on _yes_, but could revisit. I will take a look a persisting these:

![image](https://cloud.githubusercontent.com/assets/527849/20183473/0bf42728-a72b-11e6-8b69-88b7e9feedb1.png)

**Comment by skllcrn** [comment]
In my opinion the configuration should be remembered (aspect ratio, size, etc.) while the actual selection area could reset on every quit. Thoughts @tdreitz, @stursby?

**Comment by stursby** [comment]
@skllcrn that's exactly what I was thinking... working on a new branch now 💪

**Comment by matheuss** [comment]
Fixed on [v1.0.0](https://github.com/wulkano/kap/releases/tag/v1.0.0) 😄
