### ISSUE TITLE
The audio icon should be more obvious when it's not clickable

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#561]
When I have audio recording disabled in the preferences, record something, and in the editor the audio (mute) icon shows muted like normal, but nothing happens when I click it. I had forgotten that I had audio recording disabled and thought it was a bug. We should make it look like a disabled control when it's not possible to change it.

Right now it looks exactly like the play/pause icon which is clickable:

<img width="134" alt="screen shot 2018-10-04 at 12 50 31" src="https://user-images.githubusercontent.com/170270/46455252-5fdb4580-c7d4-11e8-9fd2-5c2f827689e9.png">

**Comment by dnguneratne** [comment]
Can I work on this?

**Comment by hooskers** [comment]
I can take this one. Would it be better to:

a) just gray it out (bump up transparency)
or
b)just not show it all if it cannot be unmuted?

**Comment by stephanmax** [comment]
Just stumbled upon Kap and would like to contribute—great piece of software 😃

Do you mind if I take this one?

**Comment by albinekb** [comment]
Glad you found Kap @stephanmax! There's already a PR opened for this, see #571. There are other issues tagged with "Good First Issue" [here](https://github.com/wulkano/kap/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Good+First+Issue%22)
