### ISSUE TITLE
The number inputs in the editor should be changeable with arrow keys

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#562]
In the cropper view, you can change the number inputs with arrow up/down keys, and you can also press <kbd>Shift</kbd> to increase/decrease by 10. Would be nice if this worked in the editor window too, for the width, height, and FPS inputs. Should probably make it a reusable component.

**Comment by bringking** [comment]
@sindresorhus mind if I try tackling this one?

**Comment by sindresorhus** [comment]
@bringking Go ahead :)
