### ISSUE TITLE
The cropper control icons looks like they have different sizes

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#564]
Would be good to visually unify them.

<img width="532" alt="screen shot 2018-10-04 at 13 03 40" src="https://user-images.githubusercontent.com/170270/46455587-ee9c9200-c7d5-11e8-8b5f-7662f65b859f.png">

Slack discussion:

<img width="868" alt="screen shot 2018-10-04 at 13 04 11" src="https://user-images.githubusercontent.com/170270/46455606-02e08f00-c7d6-11e8-9e3f-e3d25ab1098b.png">

**Comment by skllcrn** [comment]
Addressed in #644
