### ISSUE TITLE
Multiple screens - Kap doesn't record from the chosen screen

### ISSUE THREAD

**Issue by steveharman** [wulkano/kap#57]
This is a bit of an edge-case.  ;-)

// OSX 10.12
// 1 x GeForce dual-head PCI card
// 1 x internal graphics

I have three screens connected, I launch Kap from my main screen, move the recording-marquee to screen 2 where I want to record content and begin recording in Kap.   

The recording actually captures content from screen 1 and _not_ where my selection marquee is (on screen 2)

**Comment by matheuss** [comment]
#33 😄

**Comment by steveharman** [comment]
Aha!  :-)  Thanks Matheus.
