### ISSUE TITLE
Shortcut Overlaps with Mojave

### ISSUE THREAD

**Issue by Wdavery** [wulkano/kap#575]
macOS version: 10.14
Kap version: 2.2.0

#### Steps to reproduce
Use the ⇧⌘5 shortcut to start and stop recording.

#### Current behaviour
MacOS Mojave now has a dedicated screen capture shortcut on  ⇧⌘5.
The shortcut now launches the Mac screen grabber as well as triggering Kap.

#### Expected behaviour
Kap should default to  ⇧⌘6, or allow user customization.

#### Workaround
Change the default macOS shortcut away from  ⇧⌘5

**Comment by skllcrn** [comment]
You have the ability to customise keyboard shortcuts in the latest Kap Beta (#150), you can get it at [getkap.co ](https://getkap.co)
