### ISSUE TITLE
Unable to record Mac's menu bar?

### ISSUE THREAD

**Issue by steveharman** [wulkano/kap#58]
OSX 10.12

Is it expected behaviour that Kap doesn't permit the recording marquee to be drawn over the Mac's menu bar at the top of the screen?   That has often proved useful for me in the past, to grab the menu-bar options being chosen and is possible with QuickTime Player recordings.

Thanks,

Steve

**Comment by skllcrn** [comment]
It's expected, something we're looking into. Building it the way we do leads to some fun challenges!

**Comment by steveharman** [comment]
np.  You’re off to an excellent start, I’m using it daily now.

Steve

**Comment by sindresorhus** [comment]
Fixed by https://github.com/wulkano/kap/pull/92

It doesn't work on macOS El Capitan because of an Electron issue: https://github.com/electron/electron/issues/8141
