### ISSUE TITLE
Exporting does not work on High Sierra 10.13.6

### ISSUE THREAD

**Issue by saimonmoore** [wulkano/kap#583]
**macOS version:**
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65

**Kap version:**
Kap version:          Version 2.2.0 (2.2.0.880)

#### Steps to reproduce
- Record iterm2 window, hit GIF button, watch export dialogue not do anything.

#### Current behaviour
It fails to export to gif (or mp4)

#### Expected behaviour
Be able to export to gif or mp4

#### Workaround

None. It's a blocker for me.

**Comment by sindresorhus** [comment]
@saimonmoore We're currently working on finishing Kap v3. There will be no more development done on v2. Can you try out the beta of v3 and see if you still have this problem? https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.3

**Comment by saimonmoore** [comment]
Yep. Trying it now. Thanks

**Comment by saimonmoore** [comment]
Yep this version works! Thanks a lot.
