### ISSUE TITLE
how do you stop  kap from recording?

### ISSUE THREAD

**Issue by artivilla** [wulkano/kap#589]
**macOS version:**
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1212

Kap version: 2.2.0

#### Steps to reproduce
Click on the kap icon and then click on it again when you want to stop the recording.
#### Current behaviour
When you try to stop the recording nothing happens. For kap recordings with the dotted outline of the recorded viewport, it remains on screen until I force quit.
#### Expected behaviour
Show some indiciation of the recording being complete. The recorded outline should disappear.

**Comment by skllcrn** [comment]
This sounds like a bug @artivilla . Once you've started a recording, clicking the Kap icon in the menubar should stop the recording, hide the cropped area and open a new window with a preview of your capture. 

Can you please [download the latest Kap beta](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.3) and see if you're able to reproduce the behaviour you described?

**Comment by artivilla** [comment]
Yup, latest beta version works for me.
