### ISSUE TITLE
"Error" Symbol not found: _objc_readClassPair

### ISSUE THREAD

**Issue by dceddia** [wulkano/kap#59]
I tried to use Kap on OS X 10.9.5 (which I realize now is not supported...) but it threw an error when I attempted to start recording.

The error in the dev console is:

```
Uncaught (in promise) Error: Command failed: /Applications/Kap.app/Contents/Resources/app/node_modules/aperture.js/swift/main /var/folders/00/99h5s8bs2q782n1dcfv03ksw01560q/T/tmp-48053MS9O25wLRGu5.mp4 30 1024:486:512:512
dyld: lazy symbol binding failed: Symbol not found: _objc_readClassPair
  Referenced from: /Applications/Kap.app/Contents/Resources/app/node_modules/aperture.js/swift/main
  Expected in: /usr/lib/libobjc.A.dylib

dyld: Symbol not found: _objc_readClassPair
  Referenced from: /Applications/Kap.app/Contents/Resources/app/node_modules/aperture.js/swift/main
  Expected in: /usr/lib/libobjc.A.dylib




    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

If this is a 10.9 compatibility issue it might be nice to warn on launch that 10.9 is not supported (or just exit).

**Comment by doot0** [comment]
Hey @dceddia, thanks for the report!

This issue actually stems from upstream, within https://github.com/wulkano/aperture/. (cc @matheuss)

**Comment by sindresorhus** [comment]
Fixed by https://github.com/wulkano/aperture/commit/b20de27aa9aab025bb9049dafbc92ec24b5f7445. In the next Kap release, it will throw an error for anything below macOS 10.10.
