### ISSUE TITLE
Queued export gets stuck

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#590]
When cancelling an ongoing or queued export the next in queue gets stuck ("Waiting...").

**Comment by karaggeorge** [comment]
I've had this happen to me a couple of times too, but it was pretty sporadically and I couldn't figure out STR. Do you have any context of when it happened?

**Comment by karaggeorge** [comment]
I can't reproduce this in the current master branch 🤔

**Comment by skllcrn** [comment]
I can still recreate this on current `master`, if I have 2 or more exports and cancel the ongoing one, the waiting one gets stuck.
