### ISSUE TITLE
Option to add a progress bar to the final GIF

### ISSUE THREAD

**Issue by rsalesas** [wulkano/kap#591]
A progress bar added to the GIF export would allow viewers to gauge how much of the video they have seen. This is an example of adding on in a third-party product, but this could be done automatically.

https://www.excelcampus.com/library/add-progress-bar-to-gif/

**Comment by sindresorhus** [comment]
That's a cool idea, but outside the scope of Kap itself. We are considering adding a plugin API in the future that would make this possible: https://github.com/wulkano/kap/issues/550#issuecomment-425318838
