### ISSUE TITLE
Unhandled Error TypeError: unmaximizeBtn.onclick is not a function

### ISSUE THREAD

**Issue by kamranahmedse** [wulkano/kap#595]
**macOS version:** 10.14
**Kap version:** 2.2.0

#### Steps to reproduce

- Record a video
- Play the recording
- Maximize the screen by pressing 
![image](https://user-images.githubusercontent.com/4921183/48993311-6b087d00-f156-11e8-8afa-21eb0d9ee77d.png)
- Press escape to exit fullscreen

#### Current behaviour

```
Unhandled Error
TypeError: unmaximizeBtn.onclick is not a function
    at window.addEventListener.event (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/editor.js:280:23)
```

#### Expected behaviour
It should not throw the error.

**Comment by skllcrn** [comment]
Sentry issue: [KAP-131](https://sentry.io/wulkano-l0/kap/issues/500592132/?referrer=github_plugin)

**Comment by karaggeorge** [comment]
This is on 2.x. Do we want to make a fix? Are we releasing another 2.x version?

**Comment by skllcrn** [comment]
We'll only want to make sure this is handled in the next release. Can you see if you're able to recreate this issue using the [latest build](https://github.com/wulkano/kap/releases) @kamranahmedse?

**Comment by kamranahmedse** [comment]
Working fine in the latest build 👍
