### ISSUE TITLE
Direct Upload to Giphy

### ISSUE THREAD

**Issue by munvier** [wulkano/kap#60]
Maybe we can have in the app settings a place to link our giphy account api key and then directly upload them to giphy in order to have an easy integration with embed-friendly apps such as skype.

It's not an issue, more a request/evolution idea.

**Comment by CodeTheory** [comment]
Preferences and "save to services" are coming! ❤️

**Comment by munvier** [comment]
Nice ! Keep up the good work !

**Comment by skllcrn** [comment]
Shipping soon! Keeping the issue open to avoid duplicates https://github.com/wulkano/kap-giphy

**Comment by skllcrn** [comment]
Landed in the 2.0 Beta!

**Comment by sindresorhus** [comment]
https://github.com/wulkano/kap-giphy

**Comment by sindresorhus** [comment]
\o/
