### ISSUE TITLE
Drag and Drop dialog always empty

### ISSUE THREAD

**Issue by steven509** [wulkano/kap#601]
**macOS version:**
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391

**Kap version:**
3.x

#### Steps to reproduce
Record screen capture, choose any of the destinations (gif, mp4) and select "Drag and Drop" as the export option. Click export.

#### Current behaviour
Empty dialog box pops up where the preview should be. Nothing is drag and droppable. 

#### Expected behaviour
Dialog box should pop up with the preview which you can drag and drop

#### Workaround
Use 2.x

Works fine for me in 2.x but any version of 3.x doesn't work including the latest master build. It also works fine if I run Kap from the source code but if I compile it myself or use any of the prebuilt dmgs it doesn't work.

**Comment by skllcrn** [comment]
This sounds like an issue with the [`kap-draggable`](https://github.com/albinekb/kap-draggable) plugin, it's best if you move the issue to the repository for the plugin itself. Can you recreate this @albinekb?

**Comment by skllcrn** [comment]
After looking into this and discussing with @albinekb we've decided to make the `kap-draggable` functionality a feature in Kap itself, you can follow our progress here: #602

**Comment by albinekb** [comment]
Yes, `kap-draggable` has been broken since electron 3 upgrade & the new CSP/security features, I have a working version of it so I know it's possible to fix, I will try to get it fixed ASAP 🙂

**Comment by skllcrn** [comment]
That's great @albinekb, especially for everyone on < 3.0
