### ISSUE TITLE
Kap window doesn't close when clicking another icon in the menu bar

### ISSUE THREAD

**Issue by tom-sherman** [wulkano/kap#605]
**macOS version:** 10.14.2 (18C54)
**Kap version:** 2.2.0 

#### Steps to reproduce

1. Click on Kap icon in menu bar
2. Kap window opens
3. Click on another icon

#### Current behaviour
New menu opens, but Kap stays open underneath

#### Expected behaviour
New menu opens, Kap closes

**Comment by skllcrn** [comment]
This is related to #53

In the next version of Kap we've completely changed the way the app behaves in relation to the menubar, you can test it yourself—just leave your email at getkap.co or download the latest release via github.com/wulkano/kap/releases

Fixing this issue in older versions of Kap isn't at all trivial and we generally do not support old releases, so this likely won't be fixed.
