### ISSUE TITLE
Where is my currently recorded video?

### ISSUE THREAD

**Issue by pedromassango** [wulkano/kap#606]
I just recorded a video when I go to export it is taking too much time, and the counter (the white circle) doesn't show. Looks like it get stuck. Even trying to export the video three times it is not exporting my video.

Kap save a temporary video before I click the export button? Please help me, I do not want to record the video again.

Thank you.

**Comment by skllcrn** [comment]
We do generate a temporary file but I'm not sure how to access it and I'm mobile right now. Try looking through `~/Library/Application Support/Kap`. Some more details on which version of macOS and Kap you're on, and what format you're trying to export to would be great!

**Comment by skllcrn** [comment]
The original recording is stored in the [macOS temporary file system](https://apple.stackexchange.com/a/131080). We're using [`tempy`](https://github.com/sindresorhus/tempy) by @sindresorhus, so he'll be the best person to answer this question more in depth. From what I can tell it seems to create use/create a random folder under `/private/var/`: 

> For what it’s worth, /tmp in Mac OS actually just links to /private/tmp/ , so you can also just navigate to /private/tmp/ to find the same data, whether it’s a bunch of caches or contents of a ram disk or anything else contained therein.
