### ISSUE TITLE
Launch on Startup

### ISSUE THREAD

**Issue by bnb** [wulkano/kap#61]
Would be 💯 to see Kap be able to launch whenever I restart/power on my machine. There's a Node library that allows this pretty easily, which works with Electron: [node-auto-launch](https://github.com/Teamwork/node-auto-launch)

**Comment by matheuss** [comment]
@bnb 👌 🚢 🔜 
<img width="287" alt="screen shot 2016-10-22 at 9 00 08 pm" src="https://cloud.githubusercontent.com/assets/4721750/19623085/8e50213a-989a-11e6-9c34-f692aedbcd07.png">

**Comment by matheuss** [comment]
@bnb @65 🎉
