### ISSUE TITLE
Preference "Start automatically" is not saved

### ISSUE THREAD

**Issue by benmoose** [wulkano/kap#610]
**macOS version:**
```sh
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```

**Kap version:**
Kap v.2.2.0 (2.2.0.880)

#### Steps to reproduce
 - Start Kap (mine's started automatically on system startup)
 - Click on Kap in the menu bar
 - Click Cog > Preferences...
 - I turn off start automatically
 - Close the window
 - Reopen preferences, and the preference is still turned on

#### Current behaviour
"Start automatically" setting is not persisted

#### Expected behaviour
"Start automatically" setting is persisted

#### Workaround
Uninstall before turning computer off and reinstall when you want to use it 🤷‍♂️ 

#### Additional info
I'm aware of issue https://github.com/wulkano/kap/issues/491 – the author of that issue said the problem resolved after restarting. I've tried this but I'm still experiencing the problem.

💕 Kap is awesome x

**Comment by sindresorhus** [comment]
This is fixed in our latest beta: https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.4
