### ISSUE TITLE
Cannot read property "focus" of undefined: A JavaScript Error Occured in the Main Process

### ISSUE THREAD

**Issue by bnb** [wulkano/kap#611]
**macOS version:** 10.14.2
**Kap version:** 3.0.0-beta4

#### Steps to reproduce
¯\_(ツ)_/¯
#### Current behaviour
1. Click Kap icon in tray
2. (see screenshot)
3. Click OK
4. Kap works

![image](https://user-images.githubusercontent.com/502396/51749098-79064b80-207c-11e9-80c6-5a5f7d3a5466.png)

#### Expected behaviour
1. Click Kap Icon in tray
2. Kap works

**Comment by skllcrn** [comment]
Not the first time you find one of these elusive issues, thanks @bnb ❤️

**Comment by skllcrn** [comment]
Sentry issue: [KAP-3G4](https://sentry.io/wulkano-l0/kap/issues/826902789/?referrer=github_plugin)
