### ISSUE TITLE
Add keyboard shortcuts to resize the cropper from the center

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#612]
On macOS, you can resize while pressing <kbd>Shift</kbd> to resize from the center. And <kbd>Shift</kbd><kbd>Option</kbd> to resize from the center while keeping the aspect ratio. Would be useful if the cropper in Kap supported that. It could be useful for being able to expand the cropper for a window to also include the shadow or just more context.

These shortcuts are not even well known for most macOS users, so we need to document it somewhere. Maybe as a Tips section in the preferences?

**Comment by karaggeorge** [comment]
Right now, pressing shift maintains the aspect ratio. We could have <kbd>Option</kbd> resize from center and the combination would be the same, or we can switch to have each key do what macOS does, but that means whoever is using shift for aspect ratio will have to get used to the change. Either way doesn't really change the complexity of the implementation, just a decision we have to make

**Comment by karaggeorge** [comment]
For the tips section, maybe we could add a window for tips under the Help menu now that we have it

**Comment by sindresorhus** [comment]
> For the tips section, maybe we could add a window for tips under the Help menu now that we have it

👍 I would also add it to the menu bar menu so people will discover it.
