### ISSUE TITLE
Large GIF Assets

### ISSUE THREAD

**Issue by artivilla** [wulkano/kap#619]
**macOS version: 10.12.6 (16G1510)
**Kap version: 3.0.0-beta.3

#### Steps to reproduce
Create any GIF

#### Current behaviour
A ~30 second video takes ~30MB of file size. Screenshot included.
<img width="345" alt="screen shot 2019-01-31 at 5 09 06 pm" src="https://user-images.githubusercontent.com/2120159/52089032-89865c80-257b-11e9-812e-905197d36ffb.png">

#### Expected behaviour
Should expect something closer to ~3MB based on using other screen recorders.

**Comment by skllcrn** [comment]
The dimensions on your GIF are extremely large (1362 x 828) and it looks like you might not have set a lower FPS for the export, which isn't ideal for a GIF. Also looks like you might want to go with the WebM format for this.
