### ISSUE TITLE
Retain previous Kapture region

### ISSUE THREAD

**Issue by bnb** [wulkano/kap#62]
When using Kapture to get a gif _just right_, I attempted a GIF ~20 times. During this, I noticed that the Kapture region kept returning to the middle of the default location. Would be _awesome_ to have a setting/feature to retain the previously selected Kapture region.

**Comment by CodeTheory** [comment]
We've planned this and should be coming soon! Thanks for the issue. 😄

**Comment by stursby** [comment]
@CodeTheory maybe when a user defines a custom crop window, store the location & dimensions with `electron-settings` ? (https://github.com/wulkano/kap/blob/master/app/src/main/index.js#L6)

**Comment by matheuss** [comment]
@stursby exactly ☺️

**Comment by stursby** [comment]
Took at stab at this, seems to be working as expected for me! https://github.com/wulkano/kap/pull/75

**Comment by matheuss** [comment]
Closed via #76 🙌
