### ISSUE TITLE
Color problems

### ISSUE THREAD

**Issue by VivaliY** [wulkano/kap#620]
Hallo. I'm just wondering, why is the Kap-recorder changing the color after recording?

<img width="1484" alt="screen shot 2019-02-01 at 12 52 00 pm" src="https://user-images.githubusercontent.com/47244074/52119138-d708d500-2620-11e9-897c-ccd1cd6639c7.png">

**Comment by skllcrn** [comment]
Looks like you're working in a design tool of some sort, have you assigned a [colour profile](https://imageoptim.com/color-profiles.html) to your document? Your current profile might not be playing nicely with the codec used to record:

**https://github.com/wulkano/kap/issues/493#issuecomment-411969805**
