### ISSUE TITLE
Toggle accelerator behaviour

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#625]
Right now the default <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>5</kbd> shortcut opens a new cropper even if there's a concurrent recording. 

Options are to: 

- Not do anything if there's an ongoing recording
- Cancel the ongoing recording
- And/or start recording if it's ready

I suggest reserving this shortcut to toggle Kap and nothing else. Related: https://github.com/wulkano/kap/pull/616#issuecomment-460802449

**Comment by karaggeorge** [comment]
So, can you use that to stop an ongoing recording? (not sure what 'cancel' would be) If not, should we have a keyboard shortcut for that? I like not having to click the tray icon to stop it and then have to trim it from my recording

**Comment by skllcrn** [comment]
If we were to have a shortcut to stop the recording I think reusing the one used to start the recording makes the most sense, since Kap has already reserved it and it's unlikely to interfere with whatever workflow being recorded. Thoughts @sindresorhus?

**Comment by sindresorhus** [comment]
Yes, the shortcut set to start the recording should also stop the recording if it's currently recording.

**Comment by skllcrn** [comment]
So if we want the shortcut for toggling Kap to be <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>5</kbd>, what options do he have for a shortcut to start and stop a recording?

**Comment by msudgh** [comment]
That'd be more useful by having the [comment](https://github.com/wulkano/Kap/issues/625#issuecomment-461141596) noted here as part of the option's subtitle.

https://github.com/wulkano/Kap/blob/eaf8193b76ac6cd908f5da62584f1346c537cc24/main/common/settings.ts#L10
