### ISSUE TITLE
export issue

### ISSUE THREAD

**Issue by saddington** [wulkano/kap#627]
**macOS version:**    darwin x64 18.2.0
**Kap version:**      3.0.0-beta.4

#### Steps to reproduce

recording as normal

#### Current behavior

can't click export (doesn't respond)

#### Expected behavior

should save (open window to choose location, name), but never does.

**Comment by skllcrn** [comment]
Did this happen after updating Kap @saddington, and did a restart of the app and/or your system solve it?

**Comment by slice** [comment]
This is also happening for me. On Kap 3.0.0-beta.4, the export button doesn't do anything.

**Comment by slice** [comment]
Okay, this problem seems to be indeterminate. An app restart seemed to fix it, but it didn't earlier.

**Comment by skllcrn** [comment]
A few days ago we [released a new beta build ](https://github.com/wulkano/kap/releases), could you attempt updating to the latest release and see if you're still able to reproduce the issue @saddington and @slice?

**Comment by saddington** [comment]
Cool. I think we're good!
