### ISSUE TITLE
Kapture Sizing: Select Kapture Area

### ISSUE THREAD

**Issue by bnb** [wulkano/kap#63]
With OS X screenshots, my _killer feature_ over Windows is the built-in shortcut for region capture. Right now, I just `CMD`+`SHIFT`+`F4`, and I have instant region capture, selectable with my mouse. Would be _amazing_ to see this as an option with Kap.

There are a few way this could be set up - allow the user to set a default selection method (in addition to other possible options like the one in https://github.com/wulkano/kap/issues/62), set up with a configurable keyboard shortcut, or with another "Region Select" button in the UI.

Below is a quick example of what I mean - I know I can be slightly unclear/confusing on my intended meaning sometimes 😁
### Example of what region capture looks like

![Example of what region capture looks like](https://cloud.githubusercontent.com/assets/502396/19623144/5d7cd548-988c-11e6-92b5-e53fcf51c133.gif)
### Result of region Capture - OS X

![Result of region Capture - OS X](https://cloud.githubusercontent.com/assets/502396/19623138/201e5bcc-988c-11e6-9643-a32b8d4c9910.png)

**Comment by matheuss** [comment]
Thanks @bnb ☺️ [Easy to implement](https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md), we'll have it soon! 😄 (Not exactly like the `Cmd + Shift + 4`, but we'll have it 😛)

**Comment by matheuss** [comment]
@bnb kinda implemented via https://github.com/wulkano/kap/pull/96 😄 We'll improve it: the shortcut will be customizable. But for now I think it's a fix 💯
