### ISSUE TITLE
I can't download the dmg file?

### ISSUE THREAD

**Issue by ihaolin** [wulkano/kap#64]
Hello，

I located in China，I can't download the dmg file, it always be Network error on Chrome：

![kaperr](https://cloud.githubusercontent.com/assets/8662695/19889087/ed935fec-a06d-11e6-8c9d-1490daecaa73.png)

Could you place the dmg file on Github?

Thanks & Regards.

**Comment by matheuss** [comment]
Yo @ihaolin 👋 It's on GitHub 😄 Please try there: https://github.com/wulkano/kap/releases/download/v0.3.0/Kap-0.3.0.dmg

**Comment by ihaolin** [comment]
Thanks，it works😄。

**Comment by matheuss** [comment]
![dance](https://cloud.githubusercontent.com/assets/4721750/19889205/d63817c8-a01a-11e6-9f0c-38ea93123d1b.gif)
