### ISSUE TITLE
Filter out deprecated plugins from the plugin list

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#645]
We should allow plugins to be deprecated using `npm deprecate`, and filter them out when fetching the plugin list.

We also need to document how to deprecate a plugin in the plugin docs.

**Comment by Fahad-Mahmood** [comment]
I would like to work on it.

**Comment by skllcrn** [comment]
We’d love that @fahad-mahmood, has s there anything you need to get started? We’re here to help!

**Comment by skllcrn** [comment]
Kap requires macOS for some of its core libraries including Aperture, you might be able to work on this issue without running the app locally, but none of us work on Windows devices so we unfortunately can't help you with issues specific to your environment @Fahad-Mahmood.
