### ISSUE TITLE
Plugin discoverability

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#648]
It's hard for people to find plugins if they don't know to look for it. @karaggeorge suggested we add an option to view available plugins within the editor export options. 

I suggest only showing that hint if there are *no* plugins installed, just as a little nudge in the right direction. So we add e.g. a `Get plugins...` in the `select`, that when you click it opens preferences on the plugin overview.

**Comment by sindresorhus** [comment]
> So we add e.g. a Get plugins... in the select, that when you click it opens preferences on the plugin overview.

👍 That's a great idea.
