### ISSUE TITLE
Plugin Export GIF to clipboard exports as JPEG

### ISSUE THREAD

**Issue by kissaev** [wulkano/kap#652]
**macOS version:**
10.13.6
**Kap version:**
3 beta 5
#### Steps to reproduce
Record GIF and choose plugin to copy GIF to clipboard
#### Current behaviour
After use plugin for copy GIF to clipboard, in clipboard copied jpeg file
#### Expected behaviour
Expected that to clipboard copied GIF file
#### Workaround
not found

**Comment by albinekb** [comment]
See: https://github.com/kevva/kap-clipboard/issues/1 for more information on this issue :+1:
