### ISSUE TITLE
Exports for moderate-length video take unreasonably long time

### ISSUE THREAD

**Issue by ryanprior** [wulkano/kap#657]
Related to #437 but this issue is about overall video export throughput.

I tried to export a 27-minute video to WebM and then gave up after waiting 24 hours. I need to record 20+ minute videos and can't tolerate my computer exporting for so long, so this may mean I cannot use Kap at all, regardless of whether an accurate time estimate is provided. Taking 24+ hours to export a 27-minute video is just unacceptable.

**macOS version:**    darwin x64 18.5.0
**Kap version:**      3.0.0-beta.4

#### Steps to reproduce
* Record full-screen capture on a Macbook Pro (2018 model) for 27 minutes.
* Export to WebM
* Wait for the export to finish
#### Current behavior
export takes 24+ hours to finish
#### Expected behavior
video exports within a few hours

**Comment by skllcrn** [comment]
WebM is particularly slow, but this sounds strange. Can you try recreating the issue on the [latest beta](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.5) @ryanprior?

**Comment by karaggeorge** [comment]
@ryanprior I would try the new beta like @skllcrn suggested.

Also, you can use the `File -> Save Original...` option on the editor to grab the original `mp4` file, and either trying restarting Kap (in case something is stuck) and opening in the editor and trying again, or using some other software to do the conversion if that still doesn't work until we can get it fixed.

**Comment by cioccarellia** [comment]
Same here with 2019 macbook pro with 50 minutes long recording. 10 days expected time and Save original does not work.

**Comment by cioccarellia** [comment]
Where are original files stored? I really need those recording

**Comment by cioccarellia** [comment]
For anybody experiencing the same problem on a mac, and if you can not open your original files:
- Do not close `Kap`. It will delete your recordings. Just stop the export process from within the application.
- Run `htop` to figure out the `Kap` process details. You will have to install `htop` using [brew](https://formulae.brew.sh/formula/htop#default).  In my case the process was taking 99% of CPU my machine had. Notice that the virtual memory taken by that program reached 9GB at some point and my fans were spinning as if the computer were about to take off and fly around the room. <img src="https://imgur.com/XVfJBG3.png">
- Decompose the command like so:
    - `/Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg` is the ffmpeg binary used to actually "export" the video.
    - `/provate/var/folders/s1/iucnuwnce98j0493jwi/T/98wdjw98djiwod` is the directory where your raw mp4 files are. It will change for you, just copy it.
- Open your `/private/var/s1/iucnuwnce98j0493jwi/T/98wdjw98djiwod` directory. Here you will find your recorded mp4 files. Please, copy your files to a safe location.
- Close Kap and discard the videos you recorded. It will clean up the directory you have inspected in step 4.
- There may be some headless ffmpeg instances doing some work in the background, even after `Kap` is fully closed. Kill them via htop and reboot your system just to be sure.
- Run `brew uninstall kap && brew cleanup` from your terminal.
- Start using your built-in screen recorder. Or at least one which is not written in js.

**Comment by ryanprior** [comment]
I haven't used Kap for ages but it was a disaster trying to get anything longer than a couple minutes out of it. Sad to hear that it's still having this issue.

I switched to https://github.com/dr-Styki/ScreenRec and it's been fine.

**Comment by christiaanwesterbeek** [comment]
On my Mac, I just changed the export format in Kap from `MP4 (AVI)` (export took really long and I never actually waited for it to finish) to `MP4 (H264)` and problem fixed, took only 7 seconds to export.
