### ISSUE TITLE
Export should remember last location

### ISSUE THREAD

**Issue by calinoracation** [wulkano/kap#659]
**macOS version:**    18.5.0 (darwin)
**Kap version:**      3.0.0-beta.5

#### Steps to reproduce
Record a video, choose Gif as export target, hit export, it is always in the Kaptures folder.

#### Current behavior
No matter where I saved previously, it starts in the Kaptures folder.

#### Expected behavior
It remembers the previous save location.

#### Workaround
I use this to add gifs to PR's many times a day, and dragging from my desktop is just the easiest way for me to do that outside of always having a finder opened to the kaptures directory, which I don't. As it stands now, I have to remember to change the directory, or forget and hunt around to find that directory. It would be great to offer an option to not always preset to it but instead the last used directory.

**Comment by skllcrn** [comment]
Thanks for the detailed issue @calinoracation. Currently you can set a default save to location in preferences, would you prefer that to be overridden by your last save location for the duration of the session?

**Comment by calinoracation** [comment]
I think that's what I would personally prefer, until you told me I wouldn't of known to look in preferences. The UI for the new preference screen is really intriguing in that it wasn't immediately clear that it was vertically scrollable. I certainly appreciate that preference though and have switched to it now, I guess I wonder if most folks would know to look there.

**Comment by skllcrn** [comment]
Thank you @calinoracation, and hey, PR's are more than welcome 😌 

A related tip from our [Kap 1.0 announcement](https://medium.com/wulkano-friends/from-idea-to-product-and-beyond-a12850403c38): 

> Set your default save location to your cloud synced folder of choice for instant uploading and sharing! For example; create a Kaptures folder in Dropbox and choose it in Kap’s Preferences. Once you‘ve completed your recording and saved it, Dropbox will upload the file and easily let you grab a sharable link to it.
