### ISSUE TITLE
Option: hide cursor

### ISSUE THREAD

**Issue by martgnz** [wulkano/kap#66]
It would be great to have an option to hide the mouse in the video/gif.

**Comment by matheuss** [comment]
@martgnz it's coming 🔜 😄 Thanks for the issue 🙌

**Comment by matheuss** [comment]
Implemented via https://github.com/wulkano/kap/pull/110/commits/e1f18fe21c318f6bf4ec8f0199ef543f5c0a94cc 😄 🙌
