### ISSUE TITLE
White bar into the top

### ISSUE THREAD

**Issue by gianarb** [wulkano/kap#67]
Hello folks!!

Thanks for your work, I was really looking for a similar idea and I think that you are doing a really good job.
I don't understand why we have this white bar in the top of the screen when we start a record. 

<img width="870" alt="screen shot 2016-11-03 at 09 24 52" src="https://cloud.githubusercontent.com/assets/1630267/19960906/941d30ec-a1a7-11e6-9ee4-0f478cc9f206.png">

Can you help explain me why? :) Thanks a lot. It is also into the final video

**Comment by doot0** [comment]
Hey @gianarb!

Do you mean this white bar? http://i.imgur.com/ZujV39X.png

**Comment by gianarb** [comment]
Hello @doot0 no the white in the bottom

![download](https://cloud.githubusercontent.com/assets/1630267/19962084/e5c44ec0-a1ad-11e6-98b5-5b57817ade59.png)

**Comment by skllcrn** [comment]
Okay, this is interesting. Let's clear up a few things:

1. I presume this screenshot is taken while recording or before starting it?
2. Could you please share the actual exported file? 
3. What version is your OS? 

Thank you for the kind words!

**Comment by gianarb** [comment]
<img width="591" alt="screen shot 2016-11-03 at 10 24 52" src="https://cloud.githubusercontent.com/assets/1630267/19962484/c6a6a8b0-a1af-11e6-8d28-3c2121a039de.png">

When I select the size of the recording all is fine.. When I start to record in the bottom I have this bar.. And it's also in the final result..

![kapture 2016-11-03 at 10 28 12](https://cloud.githubusercontent.com/assets/1630267/19962587/52d7aabe-a1b0-11e6-888d-cc58ca9ee569.gif)

You can see a bar :) I am happy to know that it's not a feature but my problem :D

**Comment by doot0** [comment]
Will investigate this with @matheuss as the problem may _possibly_ be upstream in https://github.com/wulkano/aperture.js. 

Do you have any software installed on your machine that modifies screen output or anything similar? This is very strange. 🤔

**Comment by skllcrn** [comment]
We don't officially support OS X Yosemite. That being said we know quite a few people haven't upgraded yet, but we have not heard of this issue before. 

Just for the record, these bars on on the top and bottom of your screen, they show both **before you start recording** when using the crop tool to select the area you wish to record, and **while recording** as well as being present in the export as shown above?

**Comment by gianarb** [comment]
The bar is only in the bottom of my screen.
It appears when I start to record.
it is into the screen (I can see it) and also into the final file.
When I use the cropt tool I can not see the bar.

**Comment by skllcrn** [comment]
Thank you for clarifying! We'll update you here if and when we're able to reproduce and fix it. In the meantime you might want to [sign up for the newsletter](http://getkap.us14.list-manage.com/subscribe?u=318c21d4f80a3b46f22ad6ddd&id=f219da06bd) to see if the next beta solves the issue.

**Comment by doot0** [comment]
@gianarb I'm having a lot of trouble trying to reproduce this 👎. 

Can you [try an older version of Kap](https://github.com/wulkano/kap/releases/tag/v0.2.0) for me? You should uninstall your current version of Kap beforehand.

**Comment by gianarb** [comment]
I tried yesterday with the version 0.2.0 and version 0.3.0 and I have the same behavior

**Comment by doot0** [comment]
@gianarb In that case the issue is probably exclusive to your machine. 

Is there anything you're aware of about your Macbook related to your screen that could be interfering with the output?

**Comment by gianarb** [comment]
mm I am thinking but I can not see nothing strange.. I have a look and come back if I can notice something.. In the meantime I close the PR :) 

Thanks anyway!

**Comment by doot0** [comment]
Just in case somebody else ends up having this issue we're gonna leave this one open for now so we've got a bit of searchable paper trail on it. Thanks for your report!

**Comment by gianarb** [comment]
👍 thanks

**Comment by alisonmonteiro** [comment]
@gianarb @doot0 Exactly same issue here.

cc @matheuss

**Comment by skllcrn** [comment]
@alisonmonteiro @matheuss This is beyond weird, could you give us some more details about your setup please?

**Comment by polarity** [comment]
i have the exact same problem on yosemite.

**Comment by polarity** [comment]
added a video of the capture process. tried to delete the html, but looks like a wrapper/window problem (electron?): https://youtu.be/O0P5RycZaPs

**Comment by skllcrn** [comment]
@polarity @alisonmonteiro @gianarb Would you be willing to test a new build of the app to see if that solves the issue? Make sure to **not** replace your current working version of the app, this build is in development and has bugs and weird behaviour. Don't expect to rely on it for everyday use! https://65-65411043-gh.circle-artifacts.com/0/tmp/circle-artifacts.fxBO5IZ/Kap-0.3.0.dmg

**Comment by polarity** [comment]
@skllcrn the problem persists in the new build ( new video: https://youtu.be/GSi9SDO2UY8 )

**Comment by skllcrn** [comment]
@polarity Argh... Thank you for testing it. We've got one last thing to try, I'll let you know when it's ready!

**Comment by parkerpearson** [comment]
I'm also experiencing this issue. Also on Yosemite (10.10.5), experienced it with both Kap 0.2 and Kap 1.0.

**Comment by CodeTheory** [comment]
We should have a method to fix this soon. I'll be looking into it tonight.

**Comment by onbjerg** [comment]
Hey guys,

My co-worker used Kap and he experienced the same thing. He then upgraded from Yosemite to Sierra, and it works now without the bar. So highly likely that it's something with Kap on Yosemite.

**Comment by parkerpearson** [comment]
I've also upgraded to Sierra and no longer have this issue.

**Comment by joehand** [comment]
Also experiencing this issue on Yosemite. Tried building Kap from master and still see the issue (at https://github.com/wulkano/kap/commit/f9cc3b1cc98b8243012149962b9640e05e03cf24).

Maybe will give me incentive to finally upgrade to Sierra 😄 .

**Comment by KyleAMathews** [comment]
Upgrading to Sierra also fixed the problem for me.

**Comment by skllcrn** [comment]
Are you able to reproduce the issue on the [latest master](https://kap-artifacts.now.sh/master) @hanxue? If you're still seeing the issue, one alternative workaround seems to be to update your OS.

**Comment by skllcrn** [comment]
Are you able to reproduce the issue on [`master`](https://kap-artifacts.now.sh/master) @gianarb, @alisonmonteiro, @polarity, @parkerpearson @onbjerg and @joehand? If you're still seeing the issue, one alternative workaround seems to be to update your OS.

**Comment by alisonmonteiro** [comment]
@skllcrn upgrading my OS to Sierra fixed the problem for me

**Comment by skllcrn** [comment]
That's great @alisonmonteiro. Going forward we will support macOS 10.12 (Sierra) and up.
