### ISSUE TITLE
App crashes when starting a new screen recording

### ISSUE THREAD

**Issue by lepolt** [wulkano/kap#675]
**macOS version:** 10.14.5 (18F132)
**Kap version:** Version 3.0.0-beta.5

#### Steps to reproduce
- Start a new recording
- Drag to set window recording size
- Press record

#### Current behaviour
- Crash, Cannot destructure property `metaKey` of `undefined` or `null`.

#### Expected behaviour
- No crash :(

#### Workaround
n/a

**Comment by skllcrn** [comment]
Sentry issue: [KAP-3KR](https://sentry.io/organizations/wulkano-l0/issues/908567479/?referrer=github_plugin)

**Comment by karaggeorge** [comment]
I think this has been fixed in current master. 

@lepolt can you try reproducing using this build: http://kap-artifacts.now.sh/master

**Comment by lepolt** [comment]
👏 Works great! Thanks for the fix, I'll get back to using this as my primary screen capture tool!
