### ISSUE TITLE
Master builds not available anymore

### ISSUE THREAD

**Issue by levrik** [wulkano/kap#679]
Please update the readme or publish a new version.

**Comment by skllcrn** [comment]
Thanks for letting us know @levrik,looks like https://kap-artifacts.now.sh/master is down (404) @karaggeorge and @sindresorhus. As a workaround for now you can clone `master` from GitHub.

**Comment by karaggeorge** [comment]
This was fixed here: https://github.com/wulkano/kap-artifacts/commit/a82336736cea25ba05e5b459ad73ec63a9f92759
