### ISSUE TITLE
Set 60 fps as default when exporting, not 15

### ISSUE THREAD

**Issue by nicmar** [wulkano/kap#680]
**macOS version:** 10.14.4
**Kap version:** 2.2.0

#### Steps to reproduce
Export anything

#### Current behaviour
When exporting, it always chooses 15 fps

#### Expected behaviour
I want it to remember the last setting, and use 60 fps as in the preferences

#### Workaround
Select 60 fps each time i export

Sorry if this issue was reported before, but couldn't find it. Thanks for a great app! :)

**Comment by skllcrn** [comment]
There are very few instances where 60 FPS is a good default, which is why we record at 30 FPS by default. You can chose to record at 60 FPS in your settings, and we remember your last used FPS when exporting.

**Comment by nicmar** [comment]
I'm using Kap for recording videos of gameplay, where 60 fps makes very much sense. I have 60 in the settings, However for me it's always choosing 15 as default for each export. Should I file a bug report? Can I use Kap to capture a video of itself, so show the issue? :)

**Comment by skllcrn** [comment]
I think we might have introduced saving the last used FPS value in a newer version of Kap, could you test if you're still able to reproduce on the [newest release](https://github.com/wulkano/kap/releases)?

**Comment by nicmar** [comment]
It worked great in v3.0.0-beta.5, it didn't even show the 15 fps setting, but I noticed I can click it and adjust the frame rate. So perfect, will use this from now on :) Thanks!
