### ISSUE TITLE
Cannot upload video to Twitter

### ISSUE THREAD

**Issue by nicnocquee** [wulkano/kap#69]
I tried uploading video captured by Kap to Twitter, but cannot. Twitter says: The media you tried to upload was invalid.
Also cannot be played in VLC.

**Comment by skllcrn** [comment]
We're aware of the [VLC issue](https://github.com/wulkano/kap/issues/22), this sounds like it is part of that, even tho Twitter are rather specific about what kind of [videos they like](https://dev.twitter.com/rest/media/uploading-media
) 

We have a possible solution that we're still experimenting with, and hope to ship it with v1!
