### ISSUE TITLE
Ability to change filename template

### ISSUE THREAD

**Issue by ThisIsMissEm** [wulkano/kap#695]
**macOS version:**        10.14.6
**Kap version:**          2.2.0

#### Feature Request

Currently, when Kap exports files, it names them as `Kapture %date`, this is a great default, but it'd be awesome if I could customise this.

Rather than have separate screenshots and Kapture directories lying about, I just have a single screenshots directory where I put everything taken from my screen — video and images. Because of the naming of Kapture files by default, it means that files don't sort according to name nicely.

This is really just a nice to have, I can work around just by changing the file names manually. Thanks for making Kap, it's awesome.

**Comment by karaggeorge** [comment]
Would something like providing a text template that adheres to a date format like [this](https://date-fns.org/v1.30.1/docs/format) help? 

So the default would be `[Kapture] YYYY-MM-DD [at] HH.mm.ss` but the user would be able to enter their own.

Or to simplify even more, we could have a temlate that just contains `%date` or something that is the `YYYY-MM-DD [at] HH.mm.ss` as is.

**Comment by ThisIsMissEm** [comment]
@karaggeorge I'd probably go with just a simple `%date` — if people want, you can always add the date formatting to it later.

The only problem with that work-around is getting file pickers to actually remember it.

**Comment by skllcrn** [comment]
I guess we could surface the template in a `json` config file of some sort, but it'd need to be a very low maintenance solution. Is that something you'd want to look into adding @ThisIsMissEm?

**Comment by dfeuster** [comment]
Perhaps if there was a field you could fill in preferences to add a project name, and that appends to the filename:
`[projectname] + date + time`.

**Comment by karaggeorge** [comment]
I think we can close this, as now we have [kap-recording-name](https://github.com/karaggeorge/kap-recording-name) plugin, which can be installed with Kap 3.2.0
