### ISSUE TITLE
Blank popup when drag & drop exporting

### ISSUE THREAD

**Issue by apfelbox** [wulkano/kap#696]
**macOS version:**
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

**Kap version:** 
Version 3.0.0-beta.6

#### Steps to reproduce
1. Capture a video
2. Select Destination "Drag and Drop"
3. Press Export

#### Current behaviour
**Two** popups are opening, one is empty the other is the intended one.

#### Expected behaviour
The empty popup shouldn't appear

#### Workaround
You can just close the popup, but it appears every time. 🙈 

![2019-08-07 at 10 55](https://user-images.githubusercontent.com/1032411/62609549-462df180-b902-11e9-9820-21429aacbb17.png)

You can see the "wrong" popup in the front (the blank one) and the correct "Exports" one in the background

----

This looks like related to #601 but as this ticket is quite old, maybe it's a regression?

**Comment by skllcrn** [comment]
Hi @apfelbox, this is an issue in the [`kap-draggable`](https://github.com/albinekb/kap-draggable) plugin. 

https://github.com/wulkano/kap/issues/601#issuecomment-449004353

That being said, you no longer need to use `kap-draggable`, as we've implemented support for drag and drop right in the exports window. Simply drag an item from the export list and drop it where you wish to move it.

**Comment by apfelbox** [comment]
Hi @skllcrn,

thanks for the fast response! I uninstalled the plugin and although I now need to export it on disk, the drag & drop from the export list works as expected (I even always used that and thought it came from the plugin 😅 ).

Thanks again
