### ISSUE TITLE
Add ability for a plugin to override the file type it receives

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#698]
Use-case: I'm working on a Kap plugin for [Gifski](https://github.com/sindresorhus/Gifski) and need to present it as a GIF option in the export window, but I actually need the converted MP4 file, not GIF.

`context.filePath()` returns the chosen file format, so we could maybe add the ability to override that. Something like `await context.filePath({fileType: 'mp4'})`.

**Comment by karaggeorge** [comment]
Just a thought on this, I can add it, but that would only work if you're using that version of Kap or newer. But the plugin would show up in every version of Kap. Should we come up with a `package.json` schema where the plugin can say what Kap version is the minimum for it to work? And hide it if it's not? 

Otherwise the plugin will have to handle the case of the api not supported and receiving a gif anyway

**Comment by sindresorhus** [comment]
Yes, I was thinking about that too. Let’s add a “kapVersion” property that accepts a Denver range.

**Comment by karaggeorge** [comment]
Yeah I think that makes the most sense. 

A couple of points:
- Should it be in the `package.json` of the plugin, or the exported object?
- If that field (either way) is missing (every regular plugin as it stands) what should it default to? Any version? 
- If you have a plugin installed, and then somehow change your kap version (upgrade/downgrade) and suddenly it's not supported, what does the UX for that look like? 
- For not-installed plugins do we just hide them from the list, or do we show them as disabled with a message about the supported versions?

cc @skllcrn @sindresorhus

**Comment by sindresorhus** [comment]
> Should it be in the package.json of the plugin, or the exported object?

package.json

> If that field (either way) is missing (every regular plugin as it stands) what should it default to? Any version?

Any version.

> If you have a plugin installed, and then somehow change your kap version (upgrade/downgrade) and suddenly it's not supported, what does the UX for that look like?

Disabled and greyed out with a message about it not being supported.

> For not-installed plugins do we just hide them from the list, or do we show them as disabled with a message about the supported versions?

Show them greyed out with a message and also sort them last. I think it's important to show them so users can push the maintainer to update it.
