### ISSUE TITLE
Make the record button red in dark mode too

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#701]
Dark mode is too monotone, and it's not clear enough that the middle button is for recording when it's not red.

This is how it looks like now:
<img width="525" alt="Screenshot 2019-08-08 at 02 03 27" src="https://user-images.githubusercontent.com/170270/62665788-c3984700-b980-11e9-9055-9feb08db1821.png">

**Comment by skllcrn** [comment]
Agree, going full on monochrome didn't work out. Source is Abstract @karaggeorge 💅

![App](https://user-images.githubusercontent.com/8440026/62835789-9daec300-bc5c-11e9-9a3d-e9c7c0b5b6a6.png)
![App:Crop](https://user-images.githubusercontent.com/8440026/62835793-a1424a00-bc5c-11e9-8337-56e237993038.png)
![App:Focused](https://user-images.githubusercontent.com/8440026/62835794-a30c0d80-bc5c-11e9-93aa-d558e00f2cdd.png)
