### ISSUE TITLE
This app is not authorised to use Soundflower (2ch)

### ISSUE THREAD

**Issue by andylee1890** [wulkano/kap#704]
**macOS version:10.14.4 Mojave
**Kap version:2.2.0 (2.2.0.880)

 I used kap and soundflower to recording system sound ,but not success , always error.

![image](https://user-images.githubusercontent.com/12568851/62822603-74d4f200-bbb8-11e9-8f3d-6cd8421c9088.png)
![image](https://user-images.githubusercontent.com/12568851/62822608-828a7780-bbb8-11e9-93e7-a35fb51f6738.png)
![image](https://user-images.githubusercontent.com/12568851/62822570-ee201500-bbb7-11e9-8ccb-f09806dfe032.png)

**Comment by andylee1890** [comment]
"This app is not authorized to use soundflower(2ch)."
Maybe this message useful, but how to allow kap use soundflower. I tried the quicktime,seems it's intact.

**Comment by skllcrn** [comment]
I have limited knowledge about this setup @andylee1890, but I believe Soundflower uses a kernel extension that Kap might not be able to utilise. Could you try reproducing this issue on the [latest Kap Beta release](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.6)? Also, have you reached out to Soundflower?

**Comment by ldexterldesign** [comment]
+1

Hi @andylee1890!

**Comment by townmath** [comment]
Hi, in case someone else has this issue, I followed the instructions here: https://ihowto.tips/osx-apps-download-tutorials-tips-hacks-news/cum-facem-screen-recording-inregistrare-video-ecran-cu-audio-pe-macos-folosind-quicktime-player.html
Basically, you have to give the application permission to use the microphone.  That worked for me.
