### ISSUE TITLE
Plugin config modal should not be draggable

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#714]
**macOS version:** 10.14.6
**Kap version:** 3.0 Beta

#### Steps to reproduce
Go to Plugins, install one that requires configuration and open the config modal for it. 

#### Current behaviour
The modal behaves as a window.

#### Expected behaviour
Modal should be fixed to its parent window.

**Comment by sindresorhus** [comment]
Fixed https://github.com/wulkano/kap/commit/e82a16a7aa19bf51e217e75c4a40ccec82ae2df2
