### ISSUE TITLE
Confirm quitting if an export is running

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#715]
During an export, we allow closing the "Export" window and the export continues. But there's no warning when quitting Kap that an export is in progress. I think we should add a prompt. The buttons could be `Quit` and `Show Exports`.

**Comment by karaggeorge** [comment]
Where does the prompt open from? I was thinking opening the exports window and attaching it to that, but then the buttons would say Quit/Cancel. Also, what would the message be?
