### ISSUE TITLE
Export to gifs.com

### ISSUE THREAD

**Issue by vadimdemedes** [wulkano/kap#72]
Similar to #60, gifs.com could also be a service where you can export your gifs to. It doesn't require any API keys to upload, so it might be faster and easier to implement at this stage.

Our team is definitely interested in implementing this feature and helping you guys to ship it :)

P.S. I've been using Kap extensively over the last few weeks and absolutely loving it! Thank you for making a wonderful tool!

**Comment by CodeTheory** [comment]
Thanks for submitting this issue! The requests for exporting to services like gifs.com are probably the most popular thing we hear, and so we're working on it! 

We'll keep you up to date here when we can share more. 😄

**Comment by skllcrn** [comment]
Interested in creating plugins for Kap? Check out the documentation https://github.com/wulkano/kap/blob/master/docs/plugins.md

**Comment by sindresorhus** [comment]
Closing this as Vadim no longer works at gifs.com and I don't think there's a big demand for this plugin. And if there is, someone will implement it.
