### ISSUE TITLE
Toolbar disappears when selecting window

### ISSUE THREAD

**Issue by skllcrn** [wulkano/kap#722]
macOS version: 10.14.5
Kap version: 3.0 Beta 6

When selecting a window to record the Kap toolbar disappears while the cropper overlay remains. A click on the overlay brings the toolbar back.

**Comment by karaggeorge** [comment]
@skllcrn can you confirm the commits to master fixed this? 🙈

**Comment by skllcrn** [comment]
They do @karaggeorge 😬 Thank you for the quick fix!
