### ISSUE TITLE
Record Audio button missing in main bar

### ISSUE THREAD

**Issue by raabmar** [wulkano/Kap#727]
**macOS version:**    10.14.6 Mojave
**Kap version:**      3.0.0

#### Steps to reproduce
Start Kap
Try to enable/disable audio by checking the "Record Audio" button

#### Current behavior
Button not available in main bar
![image](https://user-images.githubusercontent.com/15885290/65803427-d78d4780-e17e-11e9-991c-ae6ffaccdfaf.png)

#### Expected behavior
Button as in version 2.2 available in main bar to immediately enable/disable for each recording
![image](https://user-images.githubusercontent.com/15885290/65803582-3d79cf00-e17f-11e9-8621-5367a03ae10b.png)

#### Workaround
Enable/disable globally in the preferences
Attention: it is not clear while recording if audio is recorded or not

**Comment by skllcrn** [comment]
Thanks for bringing this up @raabmar. In the next version of Kap you can decide to remove the audio channel in the editor after recording, or completely opt-out of audio recording in your preferences.

**Comment by raabmar** [comment]
Thanks a lot. Personally, I think a user knows beforehand if he/she would like to enable/disable audio. So having the opportunity to enable/disable quickly with one switch upfront sounds more logical to me. But I am sure you thought it through and tested the usability. Happy to have the option back soon - so far Kap 3.0.0 seems quite stable.

**Comment by MattieTK** [comment]
+1

I would really like this back, even though I trust that Kap will remove the audio on export if I choose, I have a headset that if it detects audio input is enabled will change the sound processor, which makes recording with audio default on (for the few times I need it) quite annoying.

Thanks :)

**Comment by karaggeorge** [comment]
Idea for this, that minimizes UI changes and pushing this around. We could add a shortcut to toggle audio recording in the menu that shows when you right-click the tray icon, or the `...` icon in the main bar:

![Screen Shot 2019-11-28 at 12 10 53 PM](https://user-images.githubusercontent.com/8822835/69823880-3c453c80-11d8-11ea-9b6e-e633086fd9bf.png)
![Screen Shot 2019-11-28 at 12 10 41 PM](https://user-images.githubusercontent.com/8822835/69823881-3c453c80-11d8-11ea-92b1-bb6c6540dcad.png)

It could be a checkbox item that would show toggled if audio is enabled, and could be clicked to toggle on/off.

Additionally we can also have a keyboard shortcut in the cropper (maybe `m`?)

**Comment by albinekb** [comment]
>Additionally we can also have a keyboard shortcut in the cropper (maybe m?)

Having a shortcut like that without a clear indicator if audio is recorded would be "dangerous" I can see myself hitting `m` by accident.

**Comment by karaggeorge** [comment]
This was fixed in #859
