### ISSUE TITLE
Fullscreen should select the current screen display

### ISSUE THREAD

**Issue by kud** [wulkano/kap#729]
**macOS version**: 10.14.6
**Kap version**: 2.2.0 (2.2.0.880)

When you've got multiple screen displays and you click on kap.app on the current display screen you want, "fullscreen" always selects the Display 1, not the screen display you clicked on the task bar.

**Comment by skllcrn** [comment]
Hi @kud, please complete the issue template including your macOS and Kap version. We'll label the issue, so no need to include that in the title. Thank you!

**Comment by kud** [comment]
- macOS: `10.14.6`
- Kap: `2.2.0 (2.2.0.880)`

**Comment by skllcrn** [comment]
Thanks again @kud. If I recall correctly, the intended behaviour here is to crop the active display if nothing else is defined. Can you test the [latest Kap beta release](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.6) to see if that is the case for you?

**Comment by kud** [comment]
It's more than ok with the latest beta yes, thank you!
