### ISSUE TITLE
Cancel processing

### ISSUE THREAD

**Issue by vadimdemedes** [wulkano/kap#73]
Would be very convenient to be able to cancel processing, if I see it's going too slow and obviously will result in a very large gif (162mb, in my case). My macbook's cooling fan was going like crazy :D

**Comment by doot0** [comment]
Hey @vdemedes, that sounds like a great idea. Seems silly not to add this. 👍

**Comment by delcore92** [comment]
Hi all, I wouldn't mind giving this issue a shot.
My plan is to store the save / convert action as deferred promise. Then adding a cancel button to the "progress"  view which will resolve the promise and perform all necessary clean up. 

Here's a screen grab of my proposed ui change:
<img width="309" alt="screen shot 2017-05-26 at 12 31 10 pm" src="https://cloud.githubusercontent.com/assets/3030010/26478442/a40cc536-420f-11e7-9da4-db42cd6a7a07.png">

**Comment by sindresorhus** [comment]
I think it would be better to use a cancelable promise. You could use https://github.com/sindresorhus/p-cancelable

**Comment by sindresorhus** [comment]
And awesome that you want to work on this 🙌

**Comment by delcore92** [comment]
Great suggestion, thank you! I'll try my best!

**Comment by sindresorhus** [comment]
@delcore92 I merged my big PR (https://github.com/wulkano/kap/pull/186), so you feel free to work on this whenever you see fit :)

**Comment by delcore92** [comment]
@sindresorhus great, i'll have a look now :)

**Comment by delcore92** [comment]
I've just raised a PR that includes the small UI change. I would love to get some conversation around how we can approach this issue. 

To be honest, i'm a bit lost with the latest refactor. I'm struggling to find a good place to wrap the export process in a cancelable promise.

**Comment by skllcrn** [comment]
Related to #263
