### ISSUE TITLE
Skip confirmations

### ISSUE THREAD

**Issue by haakonstorm** [wulkano/Kap#732]
# C'mon kap move faster faster skip all this

**macOS version:**    19.0.0 (darwin)
**Kap version:**      3.0.0-beta.6

## Current behavior:

# Lots and lots of steps just to grab some jiffy to file!

1. Invoke Kap2 with shortcut (with a hyper key modification via Karabiner-elements, my hyper key is called 💩 so hyper+2 has shorthand `💩2`) 
2. Kap2 appears, I can `click+drag` to select area of screen
3. I click on "Record"
4. ??? (but no profit!)
5. Kap2 moves to menu bar, but I don't really know when the first frame actually was recorded, because there is a lot of animation going on: 
  - Screen outside selected area is dimmed
  - The dimmed area fades out so everything is visible
  - Some sort of animation that has the Kap2 circle shrink and expand before it turns to a black square in the middle, this animation I think happens simultaneously as the dimming dissappearing, but I'm not sure this is rendered the same every time.  (See below feature request, a way to solve this better IMHO.) 
  - I take it when the icon turns to a black square in the middle the first frame is recorded, but running in HiDPI resolution on 27" iMac (pro) this square is visually *very* small, at least for my eyes.
6. I click on the  menu bar icon in order to stop the recording
7. Main window appears. I select, every time, the following information, to get it according to project requirements: width 320
8. FPS 12
9. Destination GIF and SAVE TO DISK is preselected from time to time which is great, now I click EXPORT
10. Filename. It is prepopulated with "Kapture 2019-10-07 at 13.03.19.gif" and I click SAVE

# That is 10 steps to create a GIF animation from start to finish. 

## Wanted behaviour

1. Invoke with `💩2`
2. Click+drag area of the screen, when I let go of the click, recording starts immediately, frame-perfect 
  - (meaning a recording-cache or similar activates as poop `💩2` is pressed and/or poop+drag  commences, then all frames before end of click+drag flushed). 
  - My poopkey is configured to `rightAlt+rightCmd+rightShift+Ctrl` simultaneously. So that means we can configure poop-drag `💩drag`  such that `💩mouse1ReleasedAfterDrag` have **Kap actually automatically start a recording just with the poopdrag.*

### That's it. Phew!

- ...was auto-configured to stop after 8 seconds unless stopped 
- After 8 seconds, autosave according to preset. 
- Filename  autopopulated just as today, but `xattr` metadata set correctly for each file: 
  - URL/URI to what was recorded (browser link, link to file system etc) correctly formatted and stored in the `com.apple.metadata:kMDItemWhereFroms` extended attribute. 
  - Because `Finder` is incredibly stupid, also add a plaintext copy of the above to `com.apple.metadata:kMDItemFinderComment` (*see below). 
- GIF properties: `fps`, `width`/`aspect`, `compression`, `dynamic color palette settings` and all other properties was already saved as a pre-set and was applied automatically.
- Sharing/export properties was already saved as pre-set and applied automatically. 

*notes:
> * because it is the only metadata field that can actually natively be added as a sortable column to Finders' `⌘2 list view`. 
> - This way you can see the file name and its source at the same time.
> - Kap2's job is to be really good at what it does (and it is! and getting better!) so all the logic of getting the file-name just the way people want it, should be deferred to other utilities, like `Hazel` or `DevonThink3` or some other Folder Action script. 
> - Just all the possible ways to write a date around the world in all short formats, long formats and muslim years and buddhist years and leap years and flat-earthers, ... Kap2 needs to write everything it knows about the scenario it recorded and stuff it in the file itself as extended attributes, and document this, the rest is the job of the community to contribute with. But source of recording (URL) and a real epoch time stamp should be provided at creation of file.

## This got long, but creation of GIF animations is serious business, better get it right so the liquid uranium doesn't start leaking everywhere.

> ## BONUS: Better visual menu bar representation
> - **Kap2 is not recording**: show circle as it is today but with a smaller, solid black circle in the middle if clickable. The ubiquitous symbol for _not recording, start recording when clicked_ `solid circle on outlined/not-solid background` 
> - **Kap2 is recording**: show circle filled red, with a smaller white filled square in the middle. Understood as now _recording in progress, click to stop_ `solid square on solid red background`
>   - alternatively show the "pause" icon smaller, in `white solid icon, on solid red background`. Understood as _recording in progress, click to pause_. [Optionally keep pressing and it will stop]

**Comment by skllcrn** [comment]
Thank you for the detailed issue and suggestions @haakonstorm! Have you tried the [latest Kap beta](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.6)? Would be great to hear your thoughts on it.

**Comment by haakonstorm** [comment]
<img width="992" alt="Screenshot of Snagit 2019 (07-10-2019, 13-57-54)" src="https://user-images.githubusercontent.com/193781/66309664-7bf35480-e90a-11e9-8680-012007b0f399.png">

**Comment by peppy** [comment]
I can agree this is pretty detrimental to app usability currently. I don't need the editor; I don't need the choice to export or not; I don't want the export history window to popup. Just hotkey, drag, capture, copy to clipboard automatically. No popups or confirmations.
