### ISSUE TITLE
[beta] drag'n'drop the dock from screen display to screen display

### ISSUE THREAD

**Issue by kud** [wulkano/kap#734]
**macOS version:** `macOS 10.14.6`
**Kap version:** `3.0.0-beta.6`

#### Steps to reproduce
Open Kap

#### Current behaviour
You can't drag'n'drop the dock from Display 1 to Display 2, etc

#### Expected behaviour
Working

**Comment by skllcrn** [comment]
Could you add a recording of the issue you're seeing, and some more information on what you're trying to acheive @kud?

**Comment by kud** [comment]
Yeah sure, sorry! :)

**Comment by skllcrn** [comment]
I still don't understand what is happening or what you're attempting to achieve. If you want to move the Dock from a screen to another, then this will help you do that: https://www.macobserver.com/tmo/article/os-x-mavericks-how-to-move-the-dock-to-a-second-display
