### ISSUE TITLE
Add ability to only record audio, with start/stop being activated by one hotkey

### ISSUE THREAD

**Issue by oudajosefu** [wulkano/Kap#735]
I'd like to suggest a feature that allows one to capture just audio. An example scenario would be whenever I want to record the audio of some video online in a different language to add to an Anki deck of that language, it would be nice to be able to start and stop a recording of that audio simply with two presses of a single hotkey. I don't necessarily want to capture the screen, I would just like to be able to record the audio. I have yet to find an application that fulfills these exact parameters that I want.

**Comment by karaggeorge** [comment]
Kap (and Aperture) currently records sound from your microphone or other input devices. I don't think we have an option to record system sound, so we'd have to look into that as a possibility before something like this would be feasible.

**Comment by oudajosefu** [comment]
Well actually, using apps like Loopback, I am able to use system sound as a custom input device, so that's not a problem for me. I would just like an option to only record the audio from the input device with no screen capture. And as said before, it would be nice to be able to start and stop the recording with one hotkey.

**Comment by evolutionxbox** [comment]
Curious, @oudajosefu are you using Anki + MIA Dictionary add on?

@karaggeorge this app won't need to worry about the input device, as this is solved by BlackHole.

I would also like an audio option only, and the ability to start/stop recording using a global keyboard shortcut.

**Comment by skllcrn** [comment]
We've decided not to pursue this feature for now. We want to remain focused on improving our current feature set, and from out point of view this adds overhead that would require resources we'd rather invest in making recording and sharing screen captures even faster, and to continue improving our plugin ecosystem. 

A dedicated audio recording tool paired with video editing software that allows you to manipulate the audio channels would serve your example use case better.

**Comment by evolutionxbox** [comment]
I can understand. Sadly there is no audio recording tool that starts/stops using a keyboard shortcut. They all require a convoluted interface and aren't made for "fast" recording workflows.

However, this app is perfect for this kind of workflow.

**Comment by sindresorhus** [comment]
I decided to build this tonight as I've been looking for a small project to finish in an evening.

[Recordia - build 1.zip](https://github.com/wulkano/Kap/files/5126841/Recordia.-.build.1.zip)

<img width="327" alt="Screen Shot 2020-08-26 at 02 01 36" src="https://user-images.githubusercontent.com/170270/91239546-20a79c00-e740-11ea-94a8-c022db6860ba.png"><img width="196" alt="Screen Shot 2020-08-26 at 02 01 44" src="https://user-images.githubusercontent.com/170270/91239548-23a28c80-e740-11ea-89d7-0edd46bcee27.png">


It records at 48000 hz to either M4A (AAC, compressed) or WAV (PCM, uncompressed). You can set a custom keyboard shortcut to toggle recording.

Some things missing (but planned):
- Launch at login preference.
- Set default output directory.
- Pause/resume recording (also with keyboard shortcut).

Feedback welcome if you notice anything else missing or things that could be improved.

I'm quite busy for the next month, but I plan to finish it and put it in the App Store in October (free).

**Comment by evolutionxbox** [comment]
I've spent two days _trying_ to make a mac automator workflow using nodejs, and you've built a functional app in an evening.
:sob:

**Comment by sindresorhus** [comment]
I decided to finish it, so it's now in the App Store: https://apps.apple.com/app/id1529006487

**Comment by oudajosefu** [comment]
@evolutionxbox Yes, this issue was originally opened because I was trying to find a way to record audio like Windows users do in ShareX for use in Anki and the MIA Dictionary add-on. I am really glad to see that it was finally completed. At one point, I also tried to make a dedicated app to accomplish this function, but unfortunately couldn't get over the learning curve with everything happening at the time. @sindresorhus Appreciate your help, I'll definitely be using it from now on!
