### ISSUE TITLE
Real Public Release 

### ISSUE THREAD

**Issue by L1cardo** [wulkano/kap#739]
May I ask you about the exact time of the real public version release?
Kap has been in beta for over a year!
And Homebrew keeps reinstalling my beta version, I need to manually reinstall kap every time after `brew  cask upgrade`

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by skllcrn** [comment]
Ha, I'm glad you asked. We've taken our time with this one, and we're almost done: https://github.com/wulkano/kap/projects/3

Hopefully won't be too much longer, but it won't be until it's ready 😌

**Comment by L1cardo** [comment]
OK I get it ,  thanks!
