### ISSUE TITLE
Unable to install plugins w/ 3.0.0 ?

### ISSUE THREAD

**Issue by Codelica** [wulkano/kap#753]
**macOS version:**
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103

**Kap version:**
3.0.0 (previously had beta, but removed it before installing 3.0.0)

#### Steps to reproduce
Try to install plugins via preferences

#### Current behaviour
"Something went wrong while installing xxxxx" on any plugin except *once* with the "transfer" plugin (which I don't need) 

<img width="358" alt="Monosnap 2019-11-20 11-58-52" src="https://user-images.githubusercontent.com/386101/69268873-25c23400-0b8d-11ea-8ed0-3782e35d08bc.png">

#### Expected behaviour
Plugin gets installed

#### Workaround
None known.

Not sure if this is some passing issue with downloads or something.  Is there a log I could check for further info?

Thanks!!

**Comment by karaggeorge** [comment]
@Codelica I think it has something to do with the old configurations we had in 2.0. If you quite Kap, delete your `~/Library/Application\ Support/Kap`, and try again.

I think it should work. 

Before you do that, do you mind sharing the contents of your `~/Library/Application\ Support/Kap/config.json` and `~/Library/Application\ Support/Kap/usage-history.json`? We're trying to locate the issue, and this will help a lot

**Comment by Codelica** [comment]
Thanks for the followup.. 

I don't think I ever had 2.x installed, just the last beta release.  

As you suspected, deleting the Kap directory didn't seem to help.  

This was my `config.json`:

```json
{
	"kapturesDir": "/Users/james/Movies/Kaptures",
	"allowAnalytics": false,
	"showCursor": true,
	"highlightClicks": true,
	"hideDesktopIcons": false,
	"record60fps": false,
	"loopExports": true,
	"recordKeyboardShortcut": true,
	"doNotDisturb": false,
	"recordAudio": false,
	"audioInputDeviceId": "AppleUSBAudioEngine:Unknown Manufacturer:Unknown USB Audio Device:C2B59AA0:1",
	"cropper": {
		"x": 1280,
		"y": 720,
		"width": 512,
		"height": 384,
		"ratio": [
			4,
			3
		],
		"displayId": 459094777
	},
	"actionBar": {
		"x": 1048,
		"y": 1152
	}
}
```

Didn't have a `usage-history.json` but did have an `export-usage-history.json`:

```json
{
	"apng": {
		"lastUsed": 1,
		"plugins": {
			"default": 1
		}
	},
	"webm": {
		"lastUsed": 2,
		"plugins": {
			"default": 1
		}
	},
	"mp4": {
		"lastUsed": 1574276026071,
		"plugins": {
			"default": 1,
			"undefined": 1574276026071
		}
	},
	"gif": {
		"lastUsed": 1574275985670,
		"plugins": {
			"default": 1,
			"undefined": 1574275985670
		}
	}
}
```

Thanks!

**Comment by karaggeorge** [comment]
@Codelica would you mind trying [this build](https://1422-65411043-gh.circle-artifacts.com/0/Users/distiller/project/dist/Kap.dmg) and see if the issue is resolved for you?

**Comment by Codelica** [comment]
Plugins install now :)  Can't seem to get the Nextcloud plugin to work (fails providing a share link), but I'll dig in there.   Thanks!
