### ISSUE TITLE
Unable to launch on Catalina

### ISSUE THREAD

**Issue by berlinjohnson** [wulkano/kap#754]
**macOS version:** 10.15.1
**Kap version:** 3.0.0

#### Steps to reproduce
Downloaded Kap from https://getkap.co/ and then tried to launch after installing macOS Catalina

#### Current behavior
When trying to launch I get a popup saying it needs to be updated by the developer:
![Screen Shot 2019-11-20 at 11 15 24 AM](https://user-images.githubusercontent.com/7475678/69270226-6454f000-0b87-11ea-95c9-7a49c861a0ae.png)

#### Expected behavior
It would let me open it and try it out :)

**Comment by karaggeorge** [comment]
Hey @berlinjohnson, as a workaround while we try to resolve this, you can Control + right click the app, and then click open. It should open the same window but with an extra "open" button. You should only need to do that once.
