### ISSUE TITLE
"Open Video" bugs

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#758]
1. Click the Kap menu bar icon, then in the floating controls view, click `...` and then select "Open Video". The open panel shows for a second and then disappears.
2. If I drag and drop a video on the Kap menu bar icon, the destination dropdowns in the editor are empty:  <img width="432" alt="Screenshot 2019-11-22 at 14 49 30" src="https://user-images.githubusercontent.com/170270/69407557-4ded9680-0d37-11ea-8a86-06d46210914e.png">
3. "Open Video" is missing in the "File" menu in the Kap editor.

**Comment by sindresorhus** [comment]
Ok, so `2` also happens when I record, so it's not related to "Open Video". I've managed to reduce it to having `~/Library/Application Support/Kap/plugins/package.json` with:

```json
{"dependencies":{"kap-transfer":"latest","kap-cloudinary":"latest","kap-giphy":"latest","kap-fanfou":"latest"}}
```

If I change the package.json to this it works:

```json
{"dependencies":{}}
```

**Comment by karaggeorge** [comment]
I'll be taking a look at this next. I had a small issue with the plugins after moving to yarn as well. I opened Preferences, and I got both the messages that I had all plugins, and that there were no plugins installed. I wasn't able to reproduce it again after that, but something is definitely up
