### ISSUE TITLE
Gifski doesn't finish enabling

### ISSUE THREAD

**Issue by MattieTK** [wulkano/kap#768]
**macOS version:** 10.15.1
**Kap version:** 3.0.0

#### Steps to reproduce
Try to toggle on gifski

#### Current behaviour
Gifski attempts to install (hangs in the toggled on state)
Gifski fails to enable (falls back to off state)

![Screen Recording 2019-11-28 at 16 45 32 2019-11-28 16_47_44](https://user-images.githubusercontent.com/125273/69822697-edf76400-11fe-11ea-83e3-eca3c2c53855.gif)

#### Expected behaviour
Gifski installs (hangs in toggled state)
Gifski enables (stays in toggled state)

**Comment by karaggeorge** [comment]
@MattieTK If you have Gifski installed, you can also find it in the editor, if you select `mp4`, and then for plugin, select `Open With` -> `Gifski`

**Comment by MattieTK** [comment]
Oh that's a great workaround thank you @karaggeorge

**Comment by karaggeorge** [comment]
@sindresorhus Not sure if there's any difference between the two paths. If not, the `Open With` might act as a replacement for the plugin itself

**Comment by skllcrn** [comment]
I'm glad the workaround solves it! You might still want to open an issue on the plugin repo: https://github.com/sindresorhus/kap-gifski

**Comment by sindresorhus** [comment]
@karaggeorge Mostly discoverability for people not already having Gifski installed. Since they'll see the plugin in the plugin list, install it, and also get a prompt to install Gifski.
