### ISSUE TITLE
“Kap” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by ishansingh28** [wulkano/kap#770]
**macOS version:**
**Kap version:**

**Comment by ishansingh28** [comment]
I am using OS Catalina version 10.15 and getting this error. Please help.

**Comment by skllcrn** [comment]
We have an upcoming release that addresses this. For now, press the control key while opening Kap to bypass the security prompt. I'm closing this issue due to lack of additional details, in the future, please use the issue template as described when submitting.

**Comment by sindresorhus** [comment]
There's a new update out that fixes this: https://github.com/wulkano/kap/releases/tag/v3.0.1
