### ISSUE TITLE
Bug when quitting while exporting

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#772]
Choose "Save to Disk" in the editor window, the export window shows, close it, and the press Command+Q, and you end up with this:

<img width="908" alt="Screenshot 2019-12-01 at 13 25 54" src="https://user-images.githubusercontent.com/170270/69910443-3cdf0c80-143e-11ea-8c79-e685e75a4fb4.png">

**Comment by karaggeorge** [comment]
I remember being able to reproduce this before, but I wasn't able to on the latest version.

Just to make sure, steps I tried are:
- Choose Save to Disk and export
- Cancel the pick a save location/name dialog
- Close the window
- Exit the app

**Comment by skllcrn** [comment]
I'm still able to reproduce by following the steps @sindresorhus provided.

**Comment by karaggeorge** [comment]
I was canceling the export instead of queueing it. I was finally able to repro. Will be working on this
