### ISSUE TITLE
Can not use under fullscreen app

### ISSUE THREAD

**Issue by zombieJ** [wulkano/kap#773]
**macOS version:**    19.0.0 (darwin)
**Kap version:**      3.0.1

#### Steps to reproduce

1. Open app like Chrome to make it fullscreen
2. Click kap in task bar

#### Current behavior

Nothing to show

#### Expected behavior

Show kap tool panel like old version

#### Workaround

Quit full screen to use kap

**Comment by topalavlad** [comment]
I've been trying to see what the options are to get kap to work on fullscreen apps, but from what I see [here](https://github.com/electron/electron/pull/21706#issue-360573065) there are no viable options at this point. 
Does anyone have any suggestions?

**Comment by karaggeorge** [comment]
Like the comment mentions it used to work, but then the implementation changed, but there's no new API from Electron yet, so I don't think there's much we can do until they make something else available
