### ISSUE TITLE
So, There is No Audio Anymore in 3.0.1

### ISSUE THREAD

**Issue by faxotherapy** [wulkano/kap#778]
**macOS version:** 10.14.6
**Kap version:** 3.0.1

#### Steps to reproduce
Just record the screen.

#### Current behaviour
No sound is recorded. Only screen.

#### Expected behaviour
I thought I could get the sound as well while recording the screen. Apparently, this feature is no longer available in this new version. Am I right? Just to make sure.

#### Workaround
(revert back to earlier version where sound capturing was available)

Thanks for your help.

**Comment by karaggeorge** [comment]
Can you try opening the Preferences and confirm that audio enabling is enabled and an input device is selected? The icon was moved from the recording UI and now exists only in the Preferences panel.

Related: https://github.com/wulkano/kap/issues/727

**Comment by faxotherapy** [comment]
OK. I see. I, indeed, looked at the Preference earlier, but missed the Audio recording option. So, UI-wise, making it (if you allow my user experience feedback) less striking or as important as other less critical options such “keyboard shortcuts” or “Silence notifications” made me to overlook it. But, anyway, it's only a feedback from a random user amongst millions having possibly no problem with that. I still like very much this, I believe, well-made app (although the unexpected mishap earlier with an earlier version)

Thanks for your help.
