### ISSUE TITLE
Add calculation support to size input

### ISSUE THREAD

**Issue by jkeussen** [wulkano/kap#788]
**macOS version:** 10.15.3
**Kap version:** 3.0.1

#### Steps to reproduce

1. Record video
2. In the size input fields I've tried to do math but it's not working. Example: `width: 1000, height: 600`. If I want to make this `500x300`, I have to manually type that but in other apps you can often type `1000/2` and it'll resize automatically.

#### Current behaviour

The size input can not take math commands, such as `/`, `*`, `+`, `-`.

#### Expected behaviour

I'd like to make simple calculations such as:
`1000*0.5` = `500`
`1000/4` = `250`
`300+50` = `350`
`500-100` = `400`
etc.

#### Workaround

Manually type in the value I want, which isn't too bad but I think this will be a nice improvement

I just started using the app and it's great so far! I just wanted to add that this small improvement would be appreciated 🙏. If you need any additional information, let me know!

**Comment by karaggeorge** [comment]
Hey @jkeussen 

I think we implemented that in #769 which was released as part of `3.0.1` which is the version you're on. I just tested it and it worked on macOS version 10.14, can't test on Catalina. Can someone else see if they can reproduce on 10.15?

One note is that you need to blur away from the input for it to actually make the calculations

**Comment by jkeussen** [comment]
@karaggeorge You're right, I see it now and it works on 10.15. Earlier I didn't blur the field, but tried to hit Enter on my keyboard. Maybe it's worth adding on Enter key press? Thanks for the quick reply 🙏

**Comment by jkeussen** [comment]
I'll close this in the meantime since it's not a missing feature nor a bug.

**Comment by karaggeorge** [comment]
@jkeussen that is a good idea. Coming soon: #789 😄

**Comment by jsejcksn** [comment]
I think this is actually a bug. I haven't looked at the source yet, but the behavior seems like the input values are being parsed on `change` events after a debounce rather than waiting for `blur`. Here's a screen capture in which I never press <kbd>Enter</kbd>, and only use <kbd>Tab</kbd> when you see the focus moving to different inputs:

![kap-math-bug](https://user-images.githubusercontent.com/868251/74502907-bec6c980-4eb4-11ea-9df5-035670881702.gif)


Software | Version
:---:|:---:
Kap | `3.0.1`
macOS | `10.15.3`

**Comment by karaggeorge** [comment]
@jsejcksn 

For those inputs it is also triggered on a timer (debounced). Also I'm not sure those support calculations. I think the calculations were only added to the Editor ones. If desired and of-value we can add them there as well
