### ISSUE TITLE
Retain export format between application restarts

### ISSUE THREAD

**Issue by oaleynik** [wulkano/kap#80]
Currently, if change export format from GIF -> MP4 and restart application, the export format will reset to GIF

**Comment by skllcrn** [comment]
This will be included in the next release! #76 🙌

**Comment by CodeTheory** [comment]
@skllcrn Leaving this open until the next release so we don't get duplicate issues.

**Comment by matheuss** [comment]
Implemented on https://github.com/wulkano/kap/pull/110/commits/1db890eddf424d1c17db8b04b8ceb2e30e4cdf0b 😄
