### ISSUE TITLE
Display time recorded while capturing the screen

### ISSUE THREAD

**Issue by Charay** [wulkano/Kap#805]
> It's better if I can see the time how long I have recorded when recording screen

**Comment by sindresorhus** [comment]
Where would you want to see it?

**Comment by karaggeorge** [comment]
Oh, I like that. Maybe along the Kap icon in the tray?

**Comment by Charay** [comment]
Yeah, along the Kap icon in the tray maybe a good idea. While the icon is too small, how to put the time recorded is a problem.

**Comment by karaggeorge** [comment]
Ended up implementing this as a recording plugin: https://github.com/karaggeorge/kap-recording-time

Any more feature/option requests can be opened there 😄
