### ISSUE TITLE
Exports stuck while exporting PM4

### ISSUE THREAD

**Issue by ngeshlew** [wulkano/kap#810]
**macOS version:** 10.15.3 (19D76)
**Kap version:** 3.1.0

#### Steps to reproduce
- Turn on audio recording and record browser for 29mins 14 seconds
- Export with MP4 with FPS as 60 and size: 3360 by 1974
- Select any folder

#### Current behaviour
- State is Waiting and has been stuck there for 2 hours now

#### Expected behaviour
- Show uploading state
- Upload and finish then notify user

#### Workaround
- File > Save Original > Folder > Exported

**Comment by skllcrn** [comment]
I'm not able to reproduce with a 2560 x 1440 29:18:75 long capture exported at MP4 at 60 FPS. The export is resource intensive and runs for several minutes, but progresses as expected: 
![image](https://user-images.githubusercontent.com/8440026/76998832-ff9f7b80-6955-11ea-8bac-d330f6b4d490.png)

How does your export window look while exporting @ngeshlew?

**Comment by ngeshlew** [comment]
Hey @skllcrn , you showed me a workaround on twitter:

> You might still have the original video recording open in one of the Kap windows, if not, see if you can find it in the export history window. From there, cancel the stuck export and open the original recording again.
Then use the File menu in the menubar andsave the original recording
It sounds like you may be converting a very large file to GIF, which is extremely resource intensive
With the original recording file handy, you can open it in Kap again if you wish to export with other settings

and it worked. Thanks!
