### ISSUE TITLE
Plugin idea: Hide date/time in menu bar while recording

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/kap#813]
This should be possible to implement when https://github.com/wulkano/kap/pull/804 is merged.

Idea from https://twitter.com/rauschma/status/1234155670036979712

I debugged the system preferences and discovered a way to hide the clock programmatically:

Hide:

```
defaults write com.apple.systemuiserver "menuExtras" "(\"/System/Library/CoreServices/Menu Extras/AirPort.menu\", \"/System/Library/CoreServices/Menu Extras/Volume.menu\")" && killall SystemUIServer
```

Show:

```
defaults write com.apple.systemuiserver "menuExtras" "(\"/System/Library/CoreServices/Menu Extras/AirPort.menu\", \"/System/Library/CoreServices/Menu Extras/Volume.menu\", \"/System/Library/CoreServices/Menu Extras/Clock.menu\")" && killall SystemUIServer
```

Actually, "Show" is not entirely correct. We need to first read what `menuExtras` contains before disabling and then restore that.

**Comment by karaggeorge** [comment]
Yeah that’s a good recording plugin idea and not very hard to implement. Just out of curiosity what is the use case for it? Not showing when you made the recording?

**Comment by sindresorhus** [comment]
@karaggeorge Two reasons:

1. You don't want to show that you recorded something at 4 AM.
2. If you edit a lot and leave out parts, the time will jump, which can be distracting.

**Comment by sindresorhus** [comment]
I think we should also send a global notification before and after recording, so third-party apps like [Dato](https://sindresorhus.com/dato) can be supported too.

Event names:

- `com.wulkano.kap.will-start-recording`
- `com.wulkano.kap.did-stop-recording`

https://www.electronjs.org/docs/api/system-preferences#systempreferencespostnotificationevent-userinfo-deliverimmediately-macos

**Comment by karaggeorge** [comment]
But that means the apps themselves would have to adapt to Kap. Wouldn't it make more sense for the apps to expose events that they listen to, that Kap can adapt to? Not sure what the standards are in macOS

**Comment by sindresorhus** [comment]
I think it makes more sense for Kap to define this as it's Kap that decides whether to send the events or not based on whether the user has the plugin installed and want this behavior. Kap could document these events and apps could add support for them if they want to. Either way, the apps have to add something for it to work. This doesn't matter much anyway, as I doubt any other apps will adopt this.

**Comment by karaggeorge** [comment]
But then how will Dato, for example, know to hide. willStart and didStop sound like events that should be sent out every recording. They would have to pass some other information as well, about wether the plugin was on or not. If it was a Dato specific event that it listens to, we could send those in the plugin's willStart/didStop hooks, only when it's enabled

**Comment by sindresorhus** [comment]
@karaggeorge The plugin would send those events.

**Comment by karaggeorge** [comment]
Hmm, then could they be less generic? Maybe `com.wulkano.kap.hidedate.willStartRecording` ?

Something to show that this event is specific to the plugin

**Comment by sindresorhus** [comment]
👍

**Comment by karaggeorge** [comment]
I'll implement this today hopefully 😄

**Comment by karaggeorge** [comment]
https://github.com/karaggeorge/kap-hide-clock
