### ISSUE TITLE
Unable to install plugins

### ISSUE THREAD

**Issue by bantic** [wulkano/kap#815]
**macOS version: 10.14.6**
**Kap version: 3.1.0**

#### Steps to reproduce

1. Launch Kap
1. Open prefs (cmd-,)
1. Click "Plugins" tab
1. Scroll down
1. Starting at "do-not-disturb", the toggle for it and all following plugins is disabled

#### Current behaviour

The toggle to install certain plugins is disabled, looks like:

![image](https://user-images.githubusercontent.com/2023/77556845-60b3db80-6e8f-11ea-808b-b177f81c0308.png)

#### Expected behaviour

Be able to click the toggle and install the plugin.

#### Workaround

I attempted to work around by navigating to `~/Library/Application Support/Kap/plugins` and adding the plugin to the dependencies in `package.json` (and installing), but even after that the plugin does not seem to show up in the "Plugins -> Installed" tab in Kap preferences.

**Comment by bantic** [comment]
Btw, I love Kap! Thanks for creating it.

**Comment by skllcrn** [comment]
Thank you @bantic! Please see https://github.com/wulkano/kap/issues/811#issuecomment-600258113 for more information.

**Comment by bantic** [comment]
Thank you! Apologies for not having found that duplicate issue. I'll give the test build a shot!
