### ISSUE TITLE
Can't record attached monitor

### ISSUE THREAD

**Issue by kavehhh** [wulkano/kap#818]
**macOS version:** Catalina 10.15.4
**Kap version:** 3.2.0

#### Steps to reproduce
I'm in full screen mode in Chrome on my monitor. I can't seem to record my monitor. Whenever I open Kapture it just opens on my laptop.

#### Expected behaviour
I want to be able to record any monitor

**Comment by skllcrn** [comment]
You can move the Kap toolbar between screens and then hit the fullscreen option to record, however, it's not possible to record a window set to fullscreen as that creates another single app desktop. Does that answer your question @kavehhh?

**Comment by kavehhh** [comment]
:/ yes.. too bad, but i appreciate the response.

**Comment by skllcrn** [comment]
Yes, it's unfortunate, but I'm glad I was able to answer your question. Thank you for the issue @kavehhh.
