### ISSUE TITLE
no control over where Kap exports recordings

### ISSUE THREAD

**Issue by lrdegeest** [wulkano/kap#819]
Kap 3.2.0.1540 does not export files to the desired location in Preferences

For instance, I tell Kap to export files to the Desktop:

<img width="471" alt="Screen Shot 2020-04-03 at 1 36 37 PM" src="https://user-images.githubusercontent.com/10857097/78389206-593bb300-75b0-11ea-84f5-532a68f7d235.png">

But instead it sends files to the hard disk's private folder. For instance:

```
/private/var/folders/5g/9zzrv1f16m99yxv77qsp4g7r0000gn/T/420873c8554dd618462e2173b5f58b9c
```

Any ideas?

**Comment by karaggeorge** [comment]
Hey @lrdegeest ,

the setting for `Save to...` actually applies to the Save file service. So in order for the recording to show up there, you have to export it and use the Save to disk option. 

By default all recordings originally start in the temp folder so they can be cleaned up by the system. If you need the original recording, without any modifications, you can also (while in an editor) click `File` -> `Save original`

**Comment by lrdegeest** [comment]
got it, thanks!
