### ISSUE TITLE
Unable to record screen in full-screen mode application after update Kap to 3.2.0

### ISSUE THREAD

**Issue by Cheng77777** [wulkano/kap#821]
**macOS version:**    19.4.0 (darwin) MacOS Catalina 10.15.4
**Kap version:**      3.2.0

#### Steps to reproduce
Open any application supporting full-screen mode, then switch it to full-screen mode, and try to use Kap to record the screen
#### Current behavior
The screen goes back to the desktop and comes back to the application instantly without any Kap window or pop out.
#### Expected behavior
There should be a pop out on the top of the full-screen application.

**Comment by skllcrn** [comment]
Thank you for the issue, this addresses it:   
https://github.com/wulkano/kap/issues/818#issuecomment-607362798
