### ISSUE TITLE
export and application no respond 

### ISSUE THREAD

**Issue by Yanniiiio** [wulkano/kap#823]
macOS version:  10.14.2    
Kap version:  3.2.0  
Step to reproduce:    
new recording done
location and format choices can't be showed properly 
can't press export button 
Current behavior:  The application doesn't respond totally 
Expected behavior:    at least I can save the original recording cuz I'm afraid they would be deleted once I restart the application or the system

**Comment by skllcrn** [comment]
Hi @Yanniiiio, thank you for opening an issue. First of all, your recording should be cached and we may be able to help you retrieve it later. For now, can you please screenshot the behaviour you are seeing, with the export options not displaying correctly. Are you seeing any error messages?

**Comment by Yanniiiio** [comment]
> Hi @Yanniiiio, thank you for opening an issue. First of all, your recording should be cached and we may be able to help you retrieve it later. For now, can you please screenshot the behaviour you are seeing, with the export options not displaying correctly. Are you seeing any error messages?

Hi @skllcrn Thank you for the prompt reply. There is no error messages and my Mac is still working. Sure can sent you the screenshot. Can I attach the picture in this chat though ?

**Comment by Yanniiiio** [comment]
<img width="1440" alt="Capture d’écran 2020-04-11 à 20 19 58" src="https://user-images.githubusercontent.com/63512699/79051775-64d34d80-7c32-11ea-9e44-f6aed8da1995.png">

**Comment by Yanniiiio** [comment]
<img width="1209" alt="Capture d’écran 2020-04-11 à 20 24 34" src="https://user-images.githubusercontent.com/63512699/79051794-7ddbfe80-7c32-11ea-8847-70557d549f26.png">

**Comment by Yanniiiio** [comment]
At first pictures of the two videos displayed correctly and the videos can be checked. It's just the export options not displaying. 

Then the pictures were gone, and application totally out of responce.

**Comment by skllcrn** [comment]
This looks like an issue with the apps configuration @Yanniiiio. A complete reinstall will likely resolve it, but before you do so; open your Terminal.app and run the following `find /private/var/folders -name '*.mp4' -type fs 2>/dev/null`. It will list all the cached Kap recordings, simply copy the returned path to the address bar of your browser to preview. 

lternatively, navigate to `/private/var/folders/`, there will be a number of system generated folders within. You will need to check the root level for each to find the original recording cache.

**Comment by Yanniiiio** [comment]
I think we are good now. Thank you.
