### ISSUE TITLE
ffmpeg equivalent of export

### ISSUE THREAD

**Issue by pog87** [wulkano/kap#826]
Thank you for this powerful tool!

Is there a command-line equivalent of the `Export` button?
like on `ffmpeg` or something similar?

thanks

**Comment by karaggeorge** [comment]
I'm not exactly sure what you mean. Kap does use ffmpeg with different options depending on the format/size/fps/options to export the recordings

**Comment by pog87** [comment]
I try to reformulate more properly...
Is it possible to have a bash script calling ffmpeg the same way you call it when exporting to mp4? with the options as inputs...something like
`function export {
ffmpeg -i ${1} .......
}`

**Comment by karaggeorge** [comment]
It is, but there's no way to do that through Kap. If you are interested in the options we pass to ffmpeg for each format you can take a look [here](https://github.com/wulkano/kap/blob/master/main/convert.js)

**Comment by pog87** [comment]
that is my guess

```bash
ffmpeg -i filein.mp4 -r 60 -threads 4 -deadline good b:v 1M -codec:v vp9 -codec:a vorbis -strict -2 -vf scale=-1:-1:flags=lanczos fileout.mp4
```
it that correct?

**Comment by karaggeorge** [comment]
For mp4 conversion? Our command is:
`ffmpeg -i input.mp4 -r {fps} output.mp4`
when there's a size set in the editor or trimming we also pass `-s {width}x{height} -ss {starttime} -to {endtime}`

**Comment by pog87** [comment]
thanks!
