### ISSUE TITLE
add hotkey support to start recording / finish recording

### ISSUE THREAD

**Issue by nikitavoloboev** [wulkano/kap#83]

**Comment by skllcrn** [comment]
Keyboard shorts are planned, they might even make it into the next release! Thanks for submitting an issue and let us know if there's anything else you'd like to see in the app!

**Comment by stursby** [comment]
https://github.com/wulkano/kap/pull/96 adds hotkey support.  @nikitavoloboev Here's the process:

1.  <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>5</kbd> : Bring cropperWindow to front / prepare for recording
2. <kbd>Enter</kbd> or <kbd>Spacebar</kbd> : Start recording
3. <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>5</kbd> : Stop recording

**Comment by nikitavoloboev** [comment]
Just tried it now, and cmd + shift + 5 didn't do anything.

**Comment by nikitavoloboev** [comment]
Also would be nice to have a way to customise the hotkey since command + shift + 5 is used in quite a few apps for other things thus can't really keep this hotkey be global for me at least.

**Comment by CodeTheory** [comment]
On latest master @nikitavoloboev?

**Comment by nikitavoloboev** [comment]
Well I got the release from here just now : 

![2016-12-09 at 23 53](https://cloud.githubusercontent.com/assets/6391776/21067319/ba0415a2-be6a-11e6-86db-a176ca970fa1.png)

**Comment by stursby** [comment]
@nikitavoloboev it's not in the release yet. To get it to work, you'll have to clone and build the version in `master`. And yes, the team has talked about adding user customizable hotkey in the future.

**Comment by CodeTheory** [comment]
@nikitavoloboev We're aiming for a new release _very_ soon. 😄

**Comment by nikitavoloboev** [comment]
Well I just I got a huge error trying to run yarn install to get all the dependencies :( 

![2016-12-09 at 23 58](https://cloud.githubusercontent.com/assets/6391776/21067436/7676e052-be6b-11e6-9772-2fa61be69c77.png)

Guess I will wait for a release then.

**Comment by CodeTheory** [comment]
@nikitavoloboev I'm not sure if we fully support yarn yet, try `npm install` instead?

**Comment by nikitavoloboev** [comment]
It doesn't allow me to : 

![2016-12-10 at 00 10](https://cloud.githubusercontent.com/assets/6391776/21067657/0a6c8284-be6d-11e6-8d11-4bc2802bce71.png)

**Comment by torifat** [comment]
@nikitavoloboev https://github.com/nikitavoloboev/dotfiles/blob/07a08770b30f79f5c3fa48f0fb291d0246494023/zsh/functions/zfunctions#L51

**Comment by nikitavoloboev** [comment]
oh my bad, forgot about this one, thank you

**Comment by philgyford** [comment]
Documenting these keyboard shortcuts somewhere in the app, or on the website, would be very useful.
