### ISSUE TITLE
Crashes on start with invalid scheme error

### ISSUE THREAD

**Issue by Stanzilla** [wulkano/kap#834]
**macOS version:** 10.15.4
**Kap version:** 3.2.0

#### Steps to reproduce

Open Kap

#### Current behaviour

Crashes with error
![image](https://user-images.githubusercontent.com/75278/80262802-e5f8fe80-868e-11ea-9f0e-d2884733fef7.png)

#### Expected behaviour

Starts normally

**Comment by karaggeorge** [comment]
It looks like there's an installed plugin that has an invalid config. A workaround for now would be to delete your `~/Library/Application\ Support/Kap/plugins` directory and start Kap again.

If you don't mind sharing the contents of `~/Library/Application\ Support/Kap/plugins/package.json` before you clear it, we can try and track down the plugin with the invalid config.

We'll also add a fix so the app provides the message, but runs normally after that

**Comment by Stanzilla** [comment]
Heya, thank you! I don't have a Kap directory in Application Support so I don't think I have any plugins installed?

**Comment by karaggeorge** [comment]
Have you checked both `/Library/Application\ Support` and `~/Library/Application\ Support` for the Kap directory? It should be in one of them. It's where we save all the settings

**Comment by Stanzilla** [comment]
ah, my bad, found it:

```jsom
{"dependencies":{"kap-gifski":"latest","kap-streamable":"latest"}}
```

**Comment by karaggeorge** [comment]
Yeah `kap-streamable` has been causing some issues. I'll open a PR with them to try and fix them. Until then if you remove that and restart you should be able to use Kap just fine :)

**Comment by Stanzilla** [comment]
Awesome, thank you!
