### ISSUE TITLE
Can't stop the recording

### ISSUE THREAD

**Issue by Yanniiiio** [wulkano/kap#836]
macOS version:     10.14.2
Kap version:        3.0.1
Step to reproduce:    Started the recording but can't stop the recording
Current behavior:     have found the incomplete recording file in the hidden folder
Expected behavior:    1. want to know if the complete recording has been done somewhere because this file is a very important work issue 
                                     2. how to be alerted if something went wrong  during the recording for example the stockage space isn't enough cuz I'm not at all informed that something went wrong during the process. 
 
Here in below is some screenshots. Thank you in advance for your help.

**Comment by Yanniiiio** [comment]
<img width="1005" alt="Capture d’écran 2020-04-26 à 18 24 00" src="https://user-images.githubusercontent.com/63512699/80314235-a8ac8200-87f0-11ea-9dc3-5daf6cf68450.png">
<img width="580" alt="Capture d’écran 2020-04-26 à 18 24 10" src="https://user-images.githubusercontent.com/63512699/80314236-a9ddaf00-87f0-11ea-8562-dbc79cd8af2b.png">
<img width="498" alt="Capture d’écran 2020-04-26 à 14 01 56" src="https://user-images.githubusercontent.com/63512699/80314245-b530da80-87f0-11ea-81f4-8a581e594a26.png">

**Comment by karaggeorge** [comment]
Hey @Yanniiiio it looks like the issue is that the hard drive ran out of space, so I don't think the recording is saved anywhere

**Comment by skllcrn** [comment]
Related: https://github.com/wulkano/kap/issues/762
