### ISSUE TITLE
Let plugins define the macOS version they support

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/Kap#841]
We currently support `"kapVersion": ">=3.2.0" in package.json.

I'm now thinking that we should namespace our custom package.json properties:

```json
{
	"kap": {
		"version": ">=3.2.0",
		"macosVersion": ">=10.15.4"
	}
}

**Comment by karaggeorge** [comment]
Should we have `macosVersion` follow the Release version instead? So, it's easier to compare to `os.release()` (based on https://en.wikipedia.org/wiki/Darwin_%28operating_system%29#Release_history)

Or is there a way to reliably get the mapped version?

**Comment by karaggeorge** [comment]
Never mind, there's https://github.com/sindresorhus/macos-version
