### ISSUE TITLE
Unable to add plugins

### ISSUE THREAD

**Issue by JonKrone** [wulkano/Kap#848]
Hi there!

Thanks for the App! I haven't been able to use it super successfully so far (mostly, big GIFs exceed the upload limits I encounter), but I think I can work around that. In the meantime, I've been unable to install any plugins. Details follow

**macOS version:** 10.15.2
**Kap version:** 3.2.2

#### Steps to reproduce
1. Open Kap's preferences
2. Attempt to install a plugin

#### Current behaviour
Receive a mac notification with: "Something went wrong while installing ${plugin name}"

I've tried a few different plugins: do-not-disturb, hide-desktop-icons, key-cast, playback-speed, progress-bar.

#### Expected behaviour
Installs the plugin :)

#### Workaround
None that I know of

#### Additional
plugins/package.json
```
{"dependencies":{}}
```

config.json
```
{
	"kapturesDir": "/Users/jkrone/Movies/Kaptures",
	"allowAnalytics": true,
	"showCursor": true,
	"highlightClicks": false,
	"record60fps": false,
	"loopExports": true,
	"recordKeyboardShortcut": true,
	"recordAudio": false,
	"audioInputDeviceId": "BuiltInMicrophoneDevice",
	"cropper": {},
	"actionBar": {}
}
```

**Comment by skllcrn** [comment]
Are you still able to reproduce @JonKrone?

**Comment by kjstart** [comment]
You may rename ~/.npmrc to try again.

**Comment by JonKrone** [comment]
Hey @skllcrn - sorry for the delay, missed the notification. Just re-downloaded Kap and installed some extensions - works great!
