### ISSUE TITLE
instagram video 0.01 seconds

### ISSUE THREAD

**Issue by bw1984** [wulkano/kap#85]
when i try to upload the MP4 files produced by kap onto instagram, instagram thinks that the videos are 1 second long and will only loop that first second regardless of the actual length. not sure if this is an issue with kap or instagram but it doesnt happen to any of my non-kap vids and im looking for an easy way to get nice screen recordings onto insta. problem with formatting, compression or keyframes perhaps?

**Comment by bw1984** [comment]
may be related to [#69](https://github.com/wulkano/kap/issues/69) ?

**Comment by skllcrn** [comment]
It is, which again is related to #22. We're working on it!

**Comment by bw1984** [comment]
excellent 👍
