### ISSUE TITLE
Recording error - Command failed

### ISSUE THREAD

**Issue by frozenpandaman** [wulkano/Kap#851]
**macOS version:** 10.14.6
**Kap version:** 3.2.2, installed via Homebrew cask

The 'Recording' icon in the status bar stopped working and soon after Kap gave this alert:
<img width="385" src="https://user-images.githubusercontent.com/7245874/82629718-6aaf3d80-9ba5-11ea-8bd3-c047f2bc5e69.png">

Can't reproduce, but it happened. 🙃

**Comment by skllcrn** [comment]
Closing in favour of #858
