### ISSUE TITLE
Add quick link to "record audio" in the dropdown

### ISSUE THREAD

**Issue by mesqueeb** [wulkano/Kap#855]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/3253920/83342521-76c89700-a32b-11ea-8c31-8fe1e1b9fc56.png">

I constantly have to switch to recording videos with and without audio.

In Quicktime this is an option in the "more dropdown menu" to toggle audio recording on/off.

Kap should have this too!

**Comment by frozenpandaman** [comment]
There could also maybe be an option just to save without audio when exporting?

**Comment by karaggeorge** [comment]
@frozenpandaman there is! In the editor, on the right hand side, there's a speaker icon, which will be enabled if the video has sound. Clicking that (muting) will also mute the exported file

![CleanShot 2020-06-09 at 12 02 30@2x](https://user-images.githubusercontent.com/8822835/84171714-24812780-aa49-11ea-98de-462c1ab95e77.png)
