### ISSUE TITLE
Use CMD+Shift+5 As keyboard Command

### ISSUE THREAD

**Issue by csi-lk** [wulkano/Kap#868]
**macOS version:** 10.15.5
**Kap version:** 3.2.2

#### Steps to reproduce / Current behaviour

Open System Preferences > Keyboard > Shortcuts > Screenshots > Un check "Screenshot and recording options Shift+CMD+5"
Open Kap preferences
Turn on "Keyboard Shortcuts"
Click on 'Trigger cap' input box
Type combination "CMD+Shift+5"
Box becomes red outlined and shakes

#### Expected behaviour

To be able to set combo as "CMD+Shift+5"

#### Workaround

Different keyboard command

Relates to #483

**Comment by karaggeorge** [comment]
So, I tried this and indeed I couldn't bind it, but I couldn't find any reason Kap would be preventing it. I also noticed that I couldn't bind cmd + shift + 6, but I could do cmd + shift + 7. So I tried something else, I went on https://keycode.info/ and tried the combination. When trying the combination with 7 it shows the keycode correctly, but with 5 and 6 it doesn't. It seems like even though the screen recorder tool shortcut is turned off, macos doesn't send the event for that combination to the apps. So even though we probably could programmatically bind it to the global accelerator, we can't capture it with our shortcut-input component.

Not sure if there's a workaround, but I'll keep looking a bit further. In any case it probably won't be a Kap specific fix, as it seems it's on an OS level
