### ISSUE TITLE
Reviews Page

### ISSUE THREAD

**Issue by sumnermic** [wulkano/kap#87]
Hello,

I was wondering if there is a webpage for all of your ✪✪✪✪✪✪ reviews for the app? I need to write mine down with the fancy six-star rating if possible? This is the best thing since sliced 🍞.

This needs to go the extra rating.

Kind regards,

Mic

**Comment by matheuss** [comment]
@sumnermic 😍 ❤️ Thank you ☺️ BTW, this is a great idea – we'll make sure to discuss it in our next meeting – thank you!

**Comment by sumnermic** [comment]
Cool thank you @matheuss .

**Everyone**, I was messaged back within 2 minutes. Evidence right above me lol 👍

Cheers matheuss

**Comment by CodeTheory** [comment]
Hi, again! 
I'm going to close this issue for now since we decided to keep our landing page clean and simple. If you want to show support for Kap, you can share on social media and that'll be enough thanks for us ❤️ 

Thanks again!
