### ISSUE TITLE
Set export resolution the same as crop size

### ISSUE THREAD

**Issue by yuyangchee98** [wulkano/Kap#870]
**macOS version:** 10.15.5
**Kap version:** 3.2.2.1577

#### Steps to reproduce
1. Crop frame for recording at 700*700
2. When it's ready to be exported the setting for output resolution is always 1400*1400

#### Current behaviour
Export resolution is 1400*1400

#### Expected behaviour
Export resolution is 700*700, as specified when recording

#### Workaround
Type in the resolution I want manually every time.

**Comment by karaggeorge** [comment]
Hey @yuyangchee98 , that is because your screen's pixel density is 2x (probably built-in retina), so even thought the cropper size on screen is 700x700, the resulting recording has twice the pixels.

If you were recording on an external monitor with 1x pixel density, the resolutions would match.

**Comment by yuyangchee98** [comment]
I see. I’ll try it on my ext monitor. Thanks!
