### ISSUE TITLE
Ability to zoom in and out of specific portions of the screen

### ISSUE THREAD

**Issue by connecteev** [wulkano/Kap#876]
It would be great if we could zoom in and out of specific portions of the screen, as shown in the example here:

Perhaps we could support multiple levels of zoom
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/64816/86284657-1d58bf80-bb98-11ea-9a55-881b3a297757.gif)

Suggested configuration options (these settings can be changed from the defaults below):

- Step size: 20%
- Zoom in one level (based on current step size): Cmd and '+' key together + click on the portion of the screen you want to zoom in to
- Zoom out one level (based on current step size): Cmd and '-' key together
- Zoom back (to 100%): Cmd and '0' key together

Note: If multiple zoom steps is difficult to do, then even one zoom in / zoom out would suffice.

macOS version: MacOS Catalina 10.15.5
Kap version: 3.2.2

**Comment by karaggeorge** [comment]
Hmmm, not sure how we would zoom the screen like that live while we are recording an area.. The only way I can see that happening is by taking a screenshot of the area and zooming it in place, but then it's a set image and not a recording

Only way I can see this happening is using editing software after exporting

**Comment by connecteev** [comment]
@karaggeorge I see, and what you said makes sense. If this is not achievable at the recording stage, then I guess editing software is the only way to do this. Should we close this ticket?
