### ISSUE TITLE
Enhance Google Analytics 

### ISSUE THREAD

**Issue by matheuss** [wulkano/kap#89]

**Comment by doot0** [comment]
I've finished a basic implementation of a highly simplified API for dispatching events to Google Analytics which I will place in its own `npm` module which I'll add here when I've published it. 

I'll integrate it into Kap after we've confirmed a list of events we want to track inside the app. We should also think seriously about making tracking events opt-in only, even though every session is still completely anonymized.

**Comment by CodeTheory** [comment]
Amazing job @doot0 ❤️

**Comment by skllcrn** [comment]
**Events**

- [ ] Toggled Controls
- [ ] Recording started
- [ ] Recording ended
- [ ] Accessed Editor
- [ ] Saved file
- [ ] Discarded file
- [ ] Accessed General Preferences 
- [ ] Accessed Advanced Preferences 
- [ ] Checked for updates

Sentry should cover any errors, so we'll leave those out.

**Comment by doot0** [comment]
Split the implementation off to this: https://github.com/doot0/gadispatcher

**Comment by skllcrn** [comment]
Could look into https://github.com/google/google-api-objectivec-client-for-rest

> This is the recommended library for accessing JSON-based Google APIs for iOS and Mac OS X applications. The library is compatible with applications built for iOS 7 and later, and Mac OS X 10.9 and later.
