### ISSUE TITLE
How do I stop Recording?

### ISSUE THREAD

**Issue by yukoninfo** [wulkano/Kap#894]
It is recording but I don't see Kap icon active and there is no way to force quit it. Is there a hot key to stop recording?

**Comment by frozenpandaman** [comment]
It should show up in the status bar, no? You can force quit via Activity Monitor too, if you need.

**Comment by karaggeorge** [comment]
The Kap tray icon turns into the stop button once recording has started. If you have set a keybind for opening the cropper in the settings, you can also use that same keybind to stop the recording while it's in progress.

Hope that helps!

**Comment by skllcrn** [comment]
Sorry, didn't mean to close this issue prior to replying. It looks like this may be related to #905
