### ISSUE TITLE
Error Recording error Error: Could not start recording within 5 seconds at Timeout._onTimeout

### ISSUE THREAD

**Issue by jonodjlee** [wulkano/Kap#909]
**macOS version:** 10.15.6
**Kap version:** 3.2.2

Kap sometimes inexplicably does not start recording and throws the following error:

Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)

I also noticed that when Kap refuses to work, the native MacOS screen recorder also won't run 🤔

**Comment by matthewl20** [comment]
Has there been any progress on this issue? I'm running into the same problem. I'm currently running Kap 3.2.2.1577 on: 

- Macbook Pro (2020) 
- Catalina 10.15.6

Screen recording works when I record the whole screen only. When I choose to record a cropped portion of my screen or one of my open applications I get the following error message:

Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)

I tried QuickTime and I experience the same issues there as well, but no error message is displayed. QuickTime just crashes without explanation. 

Thank you for taking the time to review!

**Comment by karaggeorge** [comment]
Hmm, I still don't know what's causing this, but if QuickTime had the same issue, I think this might have been a system issue

**Comment by jonodjlee** [comment]
@karaggeorge I agree that this might have been a system issue, although I'm not sure why. On another note, when I export recordings, I don't get an estimate of how long it'll take to convert and export. Could this be tweaked in the next update?

<img width="162" alt="Screen Shot 2020-08-17 at 10 18 27 am" src="https://user-images.githubusercontent.com/41406384/90347761-9db67f80-e075-11ea-9d1e-ace25c756acd.png">

**Comment by karaggeorge** [comment]
@jonodjlee yeah that has been fixed but not released yet. We'll be releasing a new version very soon with a bunch of fixes

**Comment by jonodjlee** [comment]
sweet, looking forward to that 😎

**Comment by skllcrn** [comment]
Closing this issue in favour of #921. Feel free to leave a 👍  there.
