### ISSUE TITLE
Input devices crash on 10.13

### ISSUE THREAD

**Issue by tiagorocha1979** [wulkano/Kap#913]
**Sentry Issue:** [KAP-7C9](https://sentry.io/organizations/wulkano-l0/issues/1769949136/)

**macOS version:**    High Sierra (10.13)
**Kap version:**      3.3.0

```
Unhandled Promise Rejection

TypeError: Cannot read property 'some' of undefined
    at /Applications/Kap.app/Contents/Resources/app.asar/main/common/settings.js:126:18
```

**Comment by karaggeorge** [comment]
Fixed in #915 

In the meantime you can get it to work by following this:

> Requires macOS 10.12 or later. macOS 10.13 or earlier needs to download the [Swift runtime support libraries](https://support.apple.com/kb/DL1998).
