### ISSUE TITLE
Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by mcvicar** [wulkano/Kap#914]
**macOS version:** 10.13.6
**Kap version:** v3.3.0

#### Steps to reproduce
Was a fresh install on a mac running OSX 10.13.6
Once OSX security allowed the app to run as an unsigned developer, start-up would fail with the following dialogue. 
![Screen Shot 2020-08-19 at 20 33 21](https://user-images.githubusercontent.com/83877/90683170-052f2380-e25e-11ea-87fc-a4abea01f147.png)

#### Current behaviour
Kap will not start, error dialogue box is broken and can not be interacted with (e.g. the buttons can not be pressed)

#### Expected behaviour
Kap to start up

#### Workaround
No workaround found. 

Couldn't really spot how `getAudioDevices()` isn't returning an array. 
https://github.com/wulkano/Kap/blob/35f18894b3c77fe710acf4507d45e920498877cf/main/utils/devices.js#L9

Installed https://github.com/karaggeorge/macos-audio-devices locally and got the following;
```
apple$ audio-devices
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /usr/local/bin/audio-devices
  Reason: image not found
Abort trap: 6
```

**Comment by karaggeorge** [comment]
Sorry about that, fixed in #915 

In the meantime you can get it to work by following this:

> Requires macOS 10.12 or later. macOS 10.13 or earlier needs to download the [Swift runtime support libraries](https://support.apple.com/kb/DL1998).

**Comment by mcvicar** [comment]
That seemed to fix it. Thanks!

**Comment by karaggeorge** [comment]
@mcvicar just out of curiosity for a different feature we released:

When you got the error dialog, did you click on the collect & report? If so, how did it go?
Or did you just copy the error and create the issue manually?

**Comment by mcvicar** [comment]
I couldn't interact with the error dialog at all, and had to create the issue manually. 
When the dialog appeared the cursor was "precision select", none of the buttons could be pressed and the text in the toolbar was all messed up.

**Comment by karaggeorge** [comment]
Thank you for the info! We'll try to fix that
