### ISSUE TITLE
Link to Kap download binaries in README does not work

### ISSUE THREAD

**Issue by metodribic** [wulkano/Kap#920]
Apparently ZEIT/Vercel changed some stuff on their side and link https://kap-updates.now.sh/download is now broken

**Comment by skllcrn** [comment]
Where did you come across this link @metodribic? You can always download the latest Kap release at http://getkap.co/download

**Comment by metodribic** [comment]
Apparently this was fixed with 5709458f5f9fa9811d931ed45d72ade1ea08c875
