### ISSUE TITLE
Performance problems exporting Kap recording

### ISSUE THREAD

**Issue by akd-io** [wulkano/Kap#924]
Hi guys, hope you are okay with me deviating from the standard issue format for this discussion!

I did a talk at work this Friday, and used Kap to record my screen and audio so I could send it to coworkers that weren't able to attend. Now, since after the talk, I have had an incredible amount of difficulty saving my recording to disk. The recording is 30 minutes long, in 1080p at 30 fps, and is estimated to export in between 17-20 hours. I would love to know if I have missed something trivial, so Kap and ffmpeg won't be using 4 GB of ram for the next several days until it's finished and I can shut down my computer again.

I am under the impression that the Kap recorder stores the video in RAM, and then allows you to save, convert and/or export it to disk afterwards. Is this correct or is my recording saved somewhere on my machine as part of the recording process, already?

I am observing that the ffmpeg process that is saving/converting/exporting my video is only using ~15% of my 6-core i7 processor and not my dedicated GPU. Do you know if this is normal behaviour?

I chose AV1 as the output codec, after a quick google search that suggested it was the latest and greatest. Am I trading a lot of time for a good compression-to-quality ratio here, and other codecs might be more performant?

Thanks a lot in advance!

**Comment by akd-io** [comment]
Okay, I actually think I solved my problem. Recordings are saved directly to disk, in my case to:

```/private/var/folders/m8/ct_ttlw950gbyhzndm4zj4bm0000gn/Teb46d7b5125a6adc170b455770cd9de0.mp4```

I was able to find this path by double clicking the `ffmpeg` process in Activity Monitor and inspecting "Open Files and Ports".

**Comment by akd-io** [comment]
The `ffmpeg` process seems to keep running after canceling the export, just FYI 👍

**Comment by sindresorhus** [comment]
AV1 is currently very slow to encode. That's outside our control, but we should add a warning somewhere.

**Comment by akd-io** [comment]
That's totally cool! Just tried exporting to H.264 and it's indeed much quicker.

I just found out that it's possible to save the original video via cmd+s. I'd maybe consider adding a Save Original button to the UI, so users are told about that possibility, instead of finding out via cmd+s or seeing it under `File > Save Original...`

Anyway, sorry for this messy issue, and thank you for this cool tool!

**Comment by skllcrn** [comment]
Thank you for the detailed report @akd-io! You can save the original recording via the File menu.
