### ISSUE TITLE
Swarm of error windows overnight

### ISSUE THREAD

**Issue by hoto** [wulkano/Kap#926]
I've left my macbook overnight and came to this:

**Sentry Issue:** [KAP-7P0](https://sentry.io/organizations/wulkano-l0/issues/1850041104/)

**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.1

```
RequestError

RequestError: getaddrinfo ENOTFOUND kap-sentry-tracker.vercel.app
    at ClientRequest.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/got/source/request-as-event-emitter.js:178:14)
    at ClientRequest.origin.emit (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/@szmarczak/http-timer/source/index.js:37:11)
```

I think my wifi broke over the night or something, which would explain the `RequestError` maybe?
Those window alerts are from Kap (I should have taken a screenshot of one up close, sorry...).

![image](https://user-images.githubusercontent.com/3105832/92082224-2a727480-edbc-11ea-89d6-c7eb9b4519e0.png)

**Comment by jacobbuck** [comment]
I often turn my laptop WiFi off when I'm not using it, and this morning was surprised by many window alerts and a very sluggish macOS. Also I have "Allow analytics" turned off.

**macOS version:** Catalina (10.15.6)
**Kap version:** 3.3.1

![Screen Shot 2020-09-09 at 09 30 57](https://user-images.githubusercontent.com/830470/92531415-555c3d00-f282-11ea-882a-d7d09b0444fd.png)
![Screen Shot 2020-09-09 at 09 28 58](https://user-images.githubusercontent.com/830470/92531416-568d6a00-f282-11ea-9ed9-ec1b2fa8bb0e.png)
