### ISSUE TITLE
ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by arisbond** [wulkano/Kap#927]
**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.1

#### Workaround

Unhandled Promise Rejection
Error: net::ERR_CONNECTION_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2519:21)

**Comment by sindresorhus** [comment]
We should avoid showing an error at all for this. It doesn't matter if an update check failed temporarily.

**Comment by marlukcz** [comment]
Similar issue I guess. It makes kap unuseable. This will show up just after launching the app and I have to kill it to remove these pop-ups. 
![image](https://user-images.githubusercontent.com/21190078/92557474-947f9380-f26c-11ea-95eb-bdb1702e626c.png)

**Comment by karaggeorge** [comment]
@sindresorhus is there a way to filter out those errors? I'm sure there's more electron errors we don't really want to show. Or should I just add this one for now and then we expand the list as we go?

**Comment by sindresorhus** [comment]
> is there a way to filter out those errors?

Not that I know of. Node.js has recently been good at adding `.code` for different errors. I would recommend opening an Electron issue for them to do the same.

> Or should I just add this one for now and then we expand the list as we go?

👍🏻
