### ISSUE TITLE
stop capture shortcut key request

### ISSUE THREAD

**Issue by 0x11-dev** [wulkano/Kap#933]
**macOS version:**    19.5.0 (darwin)
**Kap version:**      3.2.2

![image](https://user-images.githubusercontent.com/7822875/92699545-4e1b5900-f380-11ea-8a1a-8872de4642c1.png)
It's difficult to find Cap stop icon. A shortcut key would help.

**Comment by karaggeorge** [comment]
Hey, you can configure a global shortcut in the preferences window. The same shortcut that triggers Kap can be used to stop the recording

**Comment by 0x11-dev** [comment]
Awesome！Thanks a lot.
