### ISSUE TITLE
Infinite error reporting windows force me to reboot

### ISSUE THREAD

**Issue by bobvandenberge** [wulkano/Kap#937]
**macOS version:**
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
**Kap version:**
Version 3.3.1 (3.3.1.1699)

#### Steps to reproduce
1. Install a program like `Tripmode` (disallows certain apps to access the internet when using a hotspot) and don't allow Kap acces to the internet
2. I think you have to wait for it to update or something? Atleast the error I saw was something with an URL...

#### Current behaviour
1. You get a error window telling you making a connection failed which you can click away
2. A few seconds later, you get the window again, but this time it keeps popping up so fast that you can't click them away or use your system so you have to reboot the computer. 

#### Expected behaviour
1. No errors 🚀 

#### Workaround
1. Quit Kap before enabling programs like `Tripmode`.

**Comment by karaggeorge** [comment]
Hey @bobvandenberge , sorry about that experience. We have fixed this and released a patch in 3.3.2

Can you allow Kap to access the internet for a bit, so it can receive that update? You should not see this error after that.

**Comment by bobvandenberge** [comment]
Seems to have fixed problem. Thanks @karaggeorge!
