### ISSUE TITLE
No AUDIO settings in Preferences 

### ISSUE THREAD

**Issue by bailarin2020** [wulkano/Kap#943]
First off, thanks a lot for this wonderful app...the most elegant I've seen so far. But, I can only save Video WITHOUT any chance to set the desired Audio input.
Please help me!
Best,

**macOS version:**
10.14.6 (18G6032)
**Kap version:**
3.3.2
#### Steps to reproduce
Every time I launch the app and go to preferences!

#### Current behaviour
There isn't any option to select the Audio Input, as can be seen in the next images:

<img width="599" alt="Screen Shot 2020-10-07 at 9 08 05 PM" src="https://user-images.githubusercontent.com/67200466/95407014-7d6ea880-08e1-11eb-85d3-e48c643eae3d.png">

<img width="592" alt="Screen Shot 2020-10-07 at 9 04 04 PM" src="https://user-images.githubusercontent.com/67200466/95407032-8eb7b500-08e1-11eb-967b-564c1924726c.png">

#### Expected behaviour
There's an old issue [No audio recorded on videos #489]...
![](https://user-images.githubusercontent.com/1002811/42880520-1f5f6d98-8a84-11e8-9521-96ae1ed80e28.png)
...where -in spite of the actual issue- I can see a Microphone to set the audio up as needed; however, there is NO such option in the version of Kap I have.

I have a MIDI Multi-Output Device driver installed that works perfectly with other screen recorders; even with clumsy QuickTime Player I am able to choose the input and record audio besides to video.

#### Workaround
I do not know how to make any Sound Record Option to appear.

**Comment by bailarin2020** [comment]
Sorry! I've found it...No sound in the recording, however
I'm closing this ticket by now

**Comment by cipri-tom** [comment]
@bailarin2020  where is it ? :)

**Comment by djmtype** [comment]
On M3 Arm the option to choose any audio input is gone!
