### ISSUE TITLE
Big Sur

### ISSUE THREAD

**Issue by luckyywastaken** [wulkano/Kap#946]
**macOS version:** Big Sur Beta 11
**Kap version:** 18:24:19.581 › Checking for update
18:24:20.649 › Update for version 3.3.2 is not available (latest version: 3.3.2, downgrade is disallowed).

is there a working version for my OS?

**Comment by skllcrn** [comment]
Hope you're enjoying the macOS 11 beta! Support for it should be covered in #934.

**Comment by luckyywastaken** [comment]
Thanks!
