### ISSUE TITLE
Documentation on saving recording

### ISSUE THREAD

**Issue by smooJitter** [wulkano/Kap#949]
**macOS version: 10.15
**Kap version: Latest

#### Steps to reproduce:
Record 50 screen capture

#### Current
Export says 350d to left

#### Expected behavior
The recording automatically saved to disk, no converting.

#### Workaround

It could be that I am doing something wrong.   Is there any documentation of how to use this package?

**Comment by karaggeorge** [comment]
Hey @smooJitter , if I'm understanding correctly, you would like just the video itself, without any edits? 

If so, when you are on the editor screen, you can click `File -> Save Original` which will allow you to just save the original recording
