### ISSUE TITLE
God damn you, guys, put somewhere the list of hotkeys.

### ISSUE THREAD

**Issue by 123abceng** [wulkano/Kap#962]
**macOS version:**
**Kap version:**

#### Steps to reproduce
1. install the app
2. give the permission to read the screen
3. push the button to start record
4. make the record
5. realize that you don't have any info about how to stop the record.
5. kill the process
6. Google the "mac kap hotkeys" to figure out that developers were too busy to put this info somewhere.

**Comment by vesper8** [comment]
I can't even find any info on Google.. there's just the one configurable shortcut to toggle Kap but can't find any info on how to start/stop recordings with a hotkey. What did you find @123abceng ?

**Comment by sicahjes** [comment]
Three years later and I found this discussion because I can’t find the hotkeys. Can anyone point me in the right direction?
