### ISSUE TITLE
Green bar after screen recording

### ISSUE THREAD

**Issue by rubenbuijs** [wulkano/Kap#964]
**macOS version:**
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
**Kap version:**
Version 3.3.2 (3.3.2.1718)

#### Steps to reproduce
Make a screen recording

#### Current behaviour
Green bar is added to the gif. Happens for all gifs and is visible after capturing the screen. See attached.
![name_field](https://user-images.githubusercontent.com/9210390/101267717-23148b80-375c-11eb-8d04-cf88a275ac2d.gif)

#### Expected behaviour
No green bar, because there is none on my screen.

#### Workaround
None :(
After a restart, I was able to have 1 recording without the green bar. A little later, it is back.

**Comment by sindresorhus** [comment]
This sounds like https://github.com/sindresorhus/Gifski/issues/64

**Comment by skllcrn** [comment]
I'm closing this issue as it's upstream and the I'll jot be fixed by us, as mentioned in the issue @sindresorhus linked you should be able to work around this by making sure the recording dimensions are divisible by 4.

**Comment by rubenbuijs** [comment]
> sindresorhus/Gifski#64

Thanks a lot, this was indeed the issue! Have resolved it using the suggested solution.
