### ISSUE TITLE
For Windows PC's?

### ISSUE THREAD

**Issue by paaljoachim** [wulkano/Kap#969]
Hey

We are thinking of adding a link to your web site to this Github issue creator for Gutenberg issues in WordPress:
https://github.com/WordPress/gutenberg/pull/27570

But it looks like the software only works on the Mac and that there is no version for PC or Linux.

Are there plans on supporting additional operating systems?

**Comment by sindresorhus** [comment]
macOS-only. No plans for other platforms.

---

https://github.com/wulkano/Kap/issues/270

**Comment by paaljoachim** [comment]
Takk for svar Sindre!
Ha en nydelig dag!
