### ISSUE TITLE
Native Apple Silicon support

### ISSUE THREAD

**Issue by sungkhum** [wulkano/Kap#970]
On my new Mac mini with the M1 processor, encoding videos is super slow with Kap. I was wondering if there were any plans to support the new M1 processor. If there are, I would be happy to beta test and give feedback. Thanks!

**Comment by sindresorhus** [comment]
Yes, but it's probably not happening soon. Some pieces need to fall into place first:

- [ ] https://github.com/kribblo/node-ffmpeg-installer/issues/50
- [ ] New version of https://github.com/wulkano/Aperture that includes an Apple Silicon slice in the binary.
- [ ] Upgrade to Electron 11, which is blocked by https://github.com/electron/electron/issues/23757.
- [ ] Configure electron-builder to also do an Apple Silicon build.

---

*All the other binaries we use don't need an Apple Silicon to build yet as they wouldn't benefit from it.*

**Comment by sungkhum** [comment]
Thanks for the update @sindresorhus  - totally makes sense. But glad that it could be possible! Kap is a great tool!

**Comment by raulrpearson** [comment]
It does seem like it could become a long wait. `node-ffmpeg-installer` seems to be [relying on evermeet.cx](https://github.com/kribblo/node-ffmpeg-installer#the-binaries) for macOS binaries, but they in turn seem to have [no intention of supporting those binaries](https://evermeet.cx/ffmpeg/apple-silicon-arm) in the foreseeable future. There is [that cypress-io fork](https://github.com/kribblo/node-ffmpeg-installer/issues/50#issuecomment-774237083), though.

@sindresorhus, in the meantime, is there a workaround that we could use? Building our own ffmpeg and inserting into the Kap.app folder? Saving the un-encoded video capture and converting it ourselves? A 2-minute capture took 40 minutes of encoding and a reasonable amount of heat on my M1 which is a bit disappointing 😅.

I'm happy to help fix this, but I'm not sure how to.

**Comment by tortuetorche** [comment]
Hi folks,

>@sindresorhus, in the meantime, is there a workaround that we could use? Building our own ffmpeg and inserting into the Kap.app folder?

Great idea 💡! Here what I did to work around the encoding issue:

Firstly you need to [install Homebrew](https://brew.sh/) or your Mac, then run these commands in a terminal:
```bash
brew install ffmpeg
mv /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg-x64
ln -s $(which ffmpeg) /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64

brew install gifsicle
mv /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor/gifsicle /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor/gifsicle-x64
ln -s $(which gifsicle) /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor
```
Try again to record a video, now Kap works like a charm with Apple Silicon M1, encoding videos is now fast ⚡ as it should without heat 🌡️ 🤩

Have a good day,
Tortue Torche

**Comment by fyoosh** [comment]
> Hi folks,
> 
> > @sindresorhus, in the meantime, is there a workaround that we could use? Building our own ffmpeg and inserting into the Kap.app folder?
> 
> Great idea @raulrpearson💡! Here what I did to work around the encoding issue:
> 
> Firstly you need to [install Homebrew](https://brew.sh/) on your Mac, then run these commands in a terminal:
> 
> ```shell
> brew install ffmpeg
> mv /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg-x64
> ln -s $(which ffmpeg) /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64
> 
> brew install gifsicle
> mv /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor/gifsicle /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor/gifsicle-x64
> ln -s $(which gifsicle) /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor
> ```
> 
> Try again to record a video, now Kap works like a charm with Apple Silicon M1, encoding videos is fast ⚡ as it should, without heat 🌡️ 🤩
> 
> Have a good day,
> Tortue Torche

Hey @tortuetorche just wondering, is there anyway to do this without installing/using Homebrew?

**Comment by tortuetorche** [comment]
Hi @fokusferit,

> Hey @tortuetorche just wondering, is there anyway to do this without installing/using Homebrew?

🤷‍♂️

Maybe you can download a `ffmpeg` and `gifsicle` build for macOS M1 somewhere...

**Comment by jackblk** [comment]
Seems like the path to `/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg` is not correct anymore (I'm using Kap 3.4.2)

I changed it to `/node_modules/ffmpeg-static/ffmpeg`, ffmpeg is showed as Apple kind in Activity Monitor and it converts 
pretty fast now.

Here's my commands

```shell
brew install ffmpeg
mv /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/ffmpeg-static/ffmpeg /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/ffmpeg-static/ffmpeg-x64
ln -s $(which ffmpeg) /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/ffmpeg-static

brew install gifsicle
mv /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor/gifsicle /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor/gifsicle-x64
ln -s $(which gifsicle) /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/gifsicle/vendor

```

**Comment by rakleed** [comment]
@sindresorhus why didn't you release the new version on [GitHub](https://github.com/wulkano/Kap/releases), but only added it to Homebrew?

**Comment by jackblk** [comment]
> @sindresorhus why didn't you release the new version on [GitHub](https://github.com/wulkano/Kap/releases), but only added it to Homebrew?

The commands to install `ffmpeg` and `gifsicle` is not Kap itself, they are dependencies for Kap. Kap needs its dependencies to be updated for Apple Silicon, aside from these, we will need Electron v12 (done in #1051 ) and further testing.

New version for Kap to support native Apple Silicon is not there yet, it will be released soon™. Be patient 😄
