### ISSUE TITLE
Shortcuts to use for Kap

### ISSUE THREAD

**Issue by Rechellevermaak** [wulkano/Kap#974]
New to GitHub and new to Kap. Not a programmer.

What shortcuts do you use to start and stop recording in Kap on Mac Catalina v 10.15.7?

Please help.
Thanks
Rechelle

**Comment by skllcrn** [comment]
Welcome @Rechellevermaak! You can find the answer to your question in #933: https://github.com/wulkano/Kap/issues/933#issuecomment-690773379
