### ISSUE TITLE
Scrollbar visible in cropper window on OSX

### ISSUE THREAD

**Issue by doot0** [wulkano/kap#98]
When you start a recording on an OSX (Sierra) machine with scrollbars always turned on, a scrollbar is visible in the cropper window before you start a recording.

<img width="608" alt="screen shot 2016-12-09 at 03 45 33" src="https://cloud.githubusercontent.com/assets/1171137/21037317/c6388958-bdc4-11e6-9348-829ad2bd03d2.png">

**Comment by matheuss** [comment]
Cant' reproduce 😮 🤔 
<img width="591" alt="screen shot 2017-01-01 at 3 46 14 pm" src="https://cloud.githubusercontent.com/assets/4721750/21582976/c47e72b2-d039-11e6-931f-1d20df71b429.png">

[This] _should_ prevent any scrollbars from being shown 🤔 

[This]: https://github.com/wulkano/kap/blob/a8a3180c23111127098bce05c8b20bcf7098f8ec/app/src/renderer/css/cropper.css#L6

**Comment by doot0** [comment]
@matheuss As far as I can remember, it only occurred if you actually had a mouse plugged in. However, since the time the issue was filed it's probably been fixed. Can you confirm w/ a mouse plugged in to your machine?

**Comment by skllcrn** [comment]
No scrollbars here!

**Comment by CodeTheory** [comment]
I think this was during the development of the style updates and I messed something up. If I remember correctly, I fixed it but must have forgot to update this issue.

If you can't reproduce @doot0, please close 🙌

**Comment by doot0** [comment]
Will check this right now and close if I can't recreate.
