### ISSUE TITLE
Support for only record Internal Audio

### ISSUE THREAD

**Issue by jet10000** [wulkano/Kap#980]
QuickTime player can support record internal audio, but just support Audio Recroding, not support Screen Recroding.

**Comment by sindresorhus** [comment]
Kap is a screen recorder. We don't have any plans to only record audio.

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/wulkano/Kap/issues/735

**Comment by jet10000** [comment]
> Kap是一个屏幕录像机。我们没有计划只录制音频。

I expect to be able to record internal sounds while recording the screen, not external sounds.

**Comment by jet10000** [comment]
> Duplicate of #735

I expect to be able to record internal sounds while recording the screen, not external sounds.

**Comment by skllcrn** [comment]
To record system audio, you can install the Soundflower plugin for Kap via Preferences @jet10000!
