### ISSUE TITLE
Using mp4(h.264) as default export format instead of av1

### ISSUE THREAD

**Issue by link89** [wulkano/Kap#984]
After pending on the exporting several times, I find that the default format mp4(av1) would take much longer time (about 5min) than mp4(h.264) (less than 10 secs).  

And I also find that the mp4(av1) format cannot be played by the QuickTime player on Mac. 

So I think it would be better to use mp4(h.264) format as the default export format.

**Comment by karaggeorge** [comment]
It should default to the one you last used (they get ordered by last used) but yeah when you first run the app, they are alphabetical with av1 going to the top. We can give them a custom initial order to avoid that

**Comment by link89** [comment]
I think it would be better to put the recommended format as the default value for the first time as I found quite a lot of people complain about the slow exporting issue due to this.

**Comment by karaggeorge** [comment]
Yeah I can make the update in #955 

For the default order, maybe:
- gif
- mp4 (h264)
- webm
- mp4 (av1)
- apng

based on usage from our analytics, although the first two are close and way more than the last 3

Or would it be better for the first one to be mp4 same as the original file?
