### ISSUE TITLE
Cancelling Kap camera permissions - UX workflow bug and Error on recording stop

### ISSUE THREAD

**Issue by SgtPooki** [wulkano/Kap#992]
**macOS version:**
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524

**Kap version:**
3.3.2

#### Quick explanation:

I'm using the https://github.com/karaggeorge/kap-camera plugin, but i'm not sure how much of this is for them (see https://github.com/karaggeorge/kap-camera/issues/38), and how much is for core Kap.

#### Steps to reproduce
1. Make sure Kap does not have access to your camera in system preferences
2. Open Kap and click record
3. It will prompt you to give kap permission to use your camera (every time you click record when kap doesn't have permission)
4. Click cancel instead of granting access. Recording will start
5. Record your video and then click stop.

#### Current behavior

The video will have recorded successfully, and you can export/save or do whatever you normally do, but a message will pop up with this error after you click stop:

```
Unhandled Promise Rejection
CancelError: Promise was canceled
    at PCancelable.cancel (/p-cancelable/index.js:99:17)
    at Object.didStopRecording (/kap-key-cast/index.js:54:17)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:56:28
    at Array.map (<anonymous>)
    at callPlugins (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:53:66)
    at cleanup (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:74:9)
    at Tray.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:218:5)
```

#### Expected behavior
1. No prompt (for anything) between me clicking record and the recording starting. 
    * Prompt users when opening Kap for permissions, and then never again
    * or at least before the "recording initialization" loo. NOT as a pitstop between 1. clicking record and 2. recording start.
2. Do not prompt me for the same permissions each time I try to record. If i've declined them once, I probably don't want to enable it.
    
The permissions pop-up is unexpected and unnecessary once, but especially more than once. Once a user hits record, recording should start. If you need to check permissions on record button hit, then do so, but prompt the user to hit record again.

#### Workaround

No workaround needed, error seemed to have no impact except to provide me with an error message that Kap didn't handle a promise rejection.

**Comment by karaggeorge** [comment]
Hey @SgtPooki ,

To address the two issues described:

1. For the error dialog, this actually has nothing to do with the camera plugin, but rather the kap-key-cast plugin https://github.com/karaggeorge/kap-key-cast/issues/7

2. For the permission dialog, if you have the kap-camera plugin installed and enabled, the expectation is that you want to use it, so it'll ask for the permission every time. The plugin is obviously useless without that permission, so you can either disable it (using the `...` menu on the cropper -> `Plugins` -> uncheck camera plugin) or by uninstalling it all-together using the preferences window.

Then when you do want to use it at some point, you can always re-install or re-enable and accept that permission
