### ISSUE TITLE
Kap not working on Mac OS 11.2.3 

### ISSUE THREAD

**Issue by nicol-hawkins** [wulkano/Kap#995]
**macOS version:**
11.2.3
**Kap version:**
Can't tell because it wont open.

#### Steps to reproduce
Download Kap on Mac Big Sur 11.2.3
Restart
Open Kap

#### Current behaviour
Kap wont open

#### Expected behaviour
Kap would open

**Comment by sindresorhus** [comment]
I'm on the same macOS version and it works fine for me.

Try restarting your computer just to rule that out. If it's still not working, [please share the crash report](https://support.apple.com/guide/console/reports-cnsl664be99a/mac).
