### ISSUE TITLE
Takes forever to export the recording...

### ISSUE THREAD

**Issue by imflash217** [wulkano/Kap#996]
**macOS version:** `11.2.3 (Big Sur)`
**Kap version:** `Version 3.3.2 (3.3.2.1718)`

#### Workaround: Could not find one yet.

Thanks

**Comment by skllcrn** [comment]
MP4 (AV1) will not be the default following the next release. For now you will need to manually select MP4 (h264) when exporting your capture.

**Comment by sindresorhus** [comment]
AV1 is unfortunately extremely slow as it's a new format, which is not yet been optimized. It also doesn't have hardware encoding, which makes the biggest difference.

**Comment by imflash217** [comment]
Thank you @skllcrn @sindresorhus . Just tested it with MP4(H264). It’s extremely faster than AV1.
Also, I noticed that QuickTime Player fails to open the AV1 version of the exported video. But, H264 works fine.
Thanks.
