### ISSUE TITLE
System Audio is low in recording

### ISSUE THREAD

**Issue by ashishpatel1992** [wulkano/Kap#998]
**macOS version:** 10.15.7 (19H2)
**Kap version:** 3.3.2 (3.3.2.1718)

#### Steps to reproduce
1. Record any part of the screen
2. Play some audio file or youtube from your system
3. Stop the recording and test the recorded audio.

#### Current behaviour
microphone audio is great. But audio recording from system sounds (i.e. from google meet/youtube) is not that great.

#### Expected behaviour
System audio in recording can be enhanced.

#### Workaround
Not seen yet

**Comment by sindresorhus** [comment]
This should be opened on https://github.com/karaggeorge/kap-soundflower
